### ISSUE TITLE
Build Failed -  ResourceNotReady

### ISSUE THREAD

**Issue by blackumbrella1** [aws-amplify/amplify-cli#10045]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d137eew8ktssjc

### Region

us-east-1

### Amplify Hosting feature

Backend builds

### Describe the bug

the building app was working properly two days ago, then we did a small change on our frontend files, when we did a git push on our repository, the AWS Amplify tried to build but stops on ResourceNotReady error.
We didn't change anything on our backend environment, but it keeps failing without any changes.

I hope you guys can help us on this issue.

Log file is attached.
[log (9).txt](https://github.com/aws-amplify/amplify-hosting/files/8312759/log.9.txt)

### Expected behavior

Build the frontend and backend environment without errors.

### Reproduction steps

1 - git add .   (with last changes on our frontend files)
2 - git commit -m "small change text..."
3 - git push.

On Amplify Panel it shows  build failed after a few minutes after start to builld the app (admireme-mvi)

[log (9).txt](https://github.com/aws-amplify/amplify-hosting/files/8312769/log.9.txt)

### Build Settings

```yaml
version: 1
env:
  variables:
    APP_URL: https://${AWS_BRANCH//[_\/]/-}.admireme.com
    ENV_NAME: ${AWS_BRANCH//[_\/]/}
    NEXT_PUBLIC_APPLICATION_BASE_URL: https://${AWS_BRANCH//[_\/]/-}.admireme.com
    NEXT_PUBLIC_APP_URL: https://${AWS_BRANCH//[_\/]/-}.admireme.com
backend:
  phases:
    preBuild:
      commands:
        - yum install -y jq
        - if [[ ${#AWS_BRANCH} -gt 10 ]]; then ENV_NAME=$(echo ${AWS_BRANCH} | base64 | tr -cd 'a-z' | fold -w 10 | head -n 1); fi
        - export USER_BRANCH=$ENV_NAME
    build:
      commands:
        - jq -e '.[env.ENV_NAME]' ./amplify/team-provider-info.json
        - amplifyPush --environment $ENV_NAME --simple
frontend:
  phases:
    build:
      commands:
        - nvm install 14.18.1
        - nvm use 14.18.1
        - npm install
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
#  cache:
#    paths:
#      - node_modules/**/*
```
