### ISSUE TITLE
Resolvers in src/graphql not updating correctly on amplify push

### ISSUE THREAD

**Issue by poppybank** [aws-amplify/amplify-cli#1011]
** Which Category is your question related to? **
API, GraphQL 

** What AWS Services are you utilizing? **
amplify cli, S3, DynamoDB, GraphQL, Cognito

** Provide additional details e.g. code snippets **
I'm currently running version 1.1.7 of the amplify CLI.

 I made a change to the graphql.schema and did amplify push but the files in src/graphql are not being updated to reflect that I removed a @model declaration. Is there a way to force rebuild those? Doing amplify api gql-compile does not do it.  To be clear, mutations.js, queries.js, subscriptions.js and schema.json are all unchanged.  My expectation is that they would be updated automatically whenever a change in graphql.schema is pushed.

I also just added a new model to my schema.grapql file, did `amplify push`, all of the services were updated with the new model but the files in src/graphql were not updated to reflect this change.

Is there a way to force this to happen?

**Comment by poppybank** [comment]
@kaustavghosh06, this is the new issue that you asked me to create from the question in #992.
thanks.

**Comment by poppybank** [comment]
OK - I found amplify add codegen --apiId <xxx> so that solves my problem. My question is why that isn't automatically running when I make changes, I think it did previously.

**Comment by jkeys-ecg-nmsu** [comment]
Is `graphql.schema` also reverting itself to the previous schema after `amplify push`?

**Comment by poppybank** [comment]
do you mean schema.graphql? It is not.

**Comment by jkeys-ecg-nmsu** [comment]
Yes, sorry. I was experiencing a similar issue, but the actual schema file itself reverted also (which led to me rewriting the same schema a couple of times before I realized what was happening lol). What is your development platform, Linux, Windows, WSL?

**Comment by poppybank** [comment]
I'm developing on Mac

**Comment by yuth** [comment]
@poppybank could you share your `<project-root>/.graphqlconfig.yml` file. Please redact sensitive info before sharing them.

Also when you do a push do you get asked if you want to generate code?

**Comment by poppybank** [comment]
@yuth I do not get asked if I want to generate code on a push.

Here's the .graphqlconfig.yml file.
```

projects:
  tweedcaseapi-dev:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: <xxxx>
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-west-2
        maxDepth: 3
      endpoints:
        prod: >-
          https://<xxx>.appsync-api.us-west-2.amazonaws.com/graphql


```
