### ISSUE TITLE
WARNING! CLI v8.x - Broken #current-cloud-backend zip file via Amplify Console build

### ISSUE THREAD

**Issue by biller-aivy** [aws-amplify/amplify-cli#10258]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

17

### Amplify CLI Version

8.x

### What operating system are you using?

macOS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

nope

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

Broken #current-cloud-backend zip file via Amplify Console. 

I have several frontends that I have connected to my backend app via the Amplify Console. If i use the CLI version: latest, in the build settings, the deploy still works, the frontend app pulls the aws-export.js, and then uploads something. 
From this moment I can deploy the same version again and it aborts. The #current-cloud-backend uploaded by the CLI is corrupted. It does not open (unzip) when loading it directly from the deployment bucket. 
Additionally, data is missing when you look at it more closely. 

I had no backup and had to use the #current-cloud-backend file of my production environment from Develop several times now and replaced the amplify-meta.json here, which luckily still worked. 

### Expected behavior

s3 Bucket versions could be help here? Or a check of the uploaded zip folder before. 

### Reproduction steps

connect an frontend app to an backend and deploy with latest cli

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @biller-aivy :wave: thanks for raising this! Can you provide more information on how the zip was corrupted and what steps were taken prior to noticing it was corrupted?

**Comment by josefaidt** [comment]
Hey @biller-aivy based on the case and for transparency in case others encounter something similar, it appears the `amplify-meta.json` file was empty after pushing which caused issues when uploaded to #current-cloud-backend in the app's deployment bucket. Then, it appears the `backend-config.json` was empty in your other environment. Would you say that's accurate?

Can you elaborate on the steps taken prior to noticing the issue? Were there any resource changes? Are you able to capture the git diff of the changes prior to the Amplify Hosting pipeline running?

By providing this information and reproduction steps it helps gather additional context around the issue and troubleshoot effectively.

**Comment by biller-aivy** [comment]
The support staff member had been able to open the broken zip and take a look. She found that the meta.json was empty, correct. 

Since we fixed a frontend bug, we pushed this to 3 ENV. develop. staging and production. 
So all 3 Env did not have a working #current-cloud-backend.zip anymore. 
So it was not possible for me to run amplify pull anymore. 
since the #current-cloud-backend is in the gitignore, i have no comparison on git. 

The solution now was that we repacked the amplify folder with the meta-json and then uploaded it as #current-cloud-backend to the s3. 


The changes that led to the broken upload were only on the frontend side. During the build, the was-export.js is pulled. 
<img width="837" alt="Bildschirmfoto 2022-04-21 um 16 42 03" src="https://user-images.githubusercontent.com/88539760/164483353-15974e78-ccf9-44e6-8507-f95e0afc1659.png">

**Comment by biller-aivy** [comment]
@josefaidt it was not empty after pushing the backend! amplify push was working. we fixed the current-cloud-backend.zip, and tried more than one time to amplify push, this was working. After some time, it was not working again, and I recognized that someone is pushed to the frontend and after the auto build deploy, it was broken again. So I uploaded the backup file #current-cloud-backend and it was working again. (amplify pull / get was-export.js on build)

**Comment by josefaidt** [comment]
Hey @biller-aivy thanks for that clarification! Would you mind sharing your buildspec file (`amplify.yml`)? I'd like to get a better understanding of the setup to reproduce this issue

**Comment by biller-aivy** [comment]
@josefaidt 

```
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - nvm use 12
        - npm install --silent --global expo-cli
        - |-
          if [ -f yarn.lock ]; then
            yarn install
          elif [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
           npm ci
          else
           npm install
          fi
    build:
      commands:
        - 'expo build:web'
  artifacts:
    baseDirectory: web-build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - $(npm root --global)/**/*

```
