### ISSUE TITLE
Deployment of custom CDK resource containing AWS Step Function fails

### ISSUE THREAD

**Issue by pbv0** [aws-amplify/amplify-cli#10306]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v17.8.0

### Amplify CLI Version

8.0.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

custom

### Amplify Commands

push

### Describe the bug

When adding a Step Function resource to a CDK stack generated by `amplify add custom` (and updating the CDK dependencies of the stack to the latest `1.153.1`), the following error comes up during `amplify deploy`:

`CREATE_FAILED               customcustomResource73fbfaba  AWS::CloudFormation::Stack Wed Apr 27 2022 22:14:08 GMT+0200 (Central European Summer Time) Template error: Mapping named 'ServiceprincipalMap' is not present in the 'Mappings' section of template.`

### Expected behavior

Step Function resource should be deployed.

### Reproduction steps

1. `amplify init`.
2. `amplify add custom`.
3. Update CDK dependencies of the custom resource to latest CDK v1 version (`1.153.1`) by changing `package.json` to:

```
{
  "name": "custom-resource",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "@aws-amplify/cli-extensibility-helper": "^2.0.0",
    "@aws-cdk/core": "~1.153.1",
    "@aws-cdk/aws-stepfunctions": "~1.153.1"
  },
  "devDependencies": {
    "typescript": "^4.2.4"
  }
}
```

and running `npm install`.

4. Insert minimal AWS Step Function in the CDK stack by updating `cdk-stack.ts` to:

```
import * as cdk from "@aws-cdk/core";
import * as AmplifyHelpers from "@aws-amplify/cli-extensibility-helper";
import * as sfn from "@aws-cdk/aws-stepfunctions";

export class cdkStack extends cdk.Stack {
  constructor(
    scope: cdk.Construct,
    id: string,
    props?: cdk.StackProps,
    amplifyResourceProps?: AmplifyHelpers.AmplifyResourceProps
  ) {
    super(scope, id, props);
    /* Do not remove - Amplify CLI automatically injects the current deployment environment in this input parameter */
    new cdk.CfnParameter(this, "env", {
      type: "String",
      description: "Current Amplify CLI env name",
    });

    const startState = new sfn.Pass(this, "StartState");

    const exampleSfn = new sfn.StateMachine(this, "StateMachine", {
      definition: startState,
    });
  }
}
```

6. Run `amplify deploy` and confirm deployment to produce error.

### Additional information

The CDK stack above deploys without issue ouside of Amplify with CDK v1 and v2.

The CDK stack above also deploys without issue with CDK v1 versions `1.124.0` and `1.128.0` (but not the latest version `1.153.1`) as an amplify custom resource.

The stack also deploys if we add an IAM role to the Step Function which should not be necessary according to the CDK docs (and is not necessary when using the other CDK versions mentioned above):

```
import * as cdk from "@aws-cdk/core";
import * as AmplifyHelpers from "@aws-amplify/cli-extensibility-helper";
import * as sfn from "@aws-cdk/aws-stepfunctions";
import * as iam from "@aws-cdk/aws-iam";

export class cdkStack extends cdk.Stack {
  constructor(
    scope: cdk.Construct,
    id: string,
    props?: cdk.StackProps,
    amplifyResourceProps?: AmplifyHelpers.AmplifyResourceProps
  ) {
    super(scope, id, props);
    /* Do not remove - Amplify CLI automatically injects the current deployment environment in this input parameter */
    new cdk.CfnParameter(this, "env", {
      type: "String",
      description: "Current Amplify CLI env name",
    });

    const serviceRole = new iam.Role(this, "Role", {
      assumedBy: new iam.ServicePrincipal("states.eu-west-1.amazonaws.com"),
    });

    const startState = new sfn.Pass(this, "StartState");

    const exampleSfn = new sfn.StateMachine(this, "StateMachine", {
      definition: startState,
      role: serviceRole,
    });
  }
}

```

**Comment by ykethan** [comment]
hey @pbv0, Thank you for reaching out. I observed that currently the Amplify managed policy[1] for the IAM profile does not provide the  `ServiceprincipalMap` and `service principal` permission by default . Could you please let us know if `ServiceprincipalMap` and `service principal` have been added to your IAM role? REF:  https://docs.aws.amazon.com/step-functions/latest/dg/tutorial-lambda-state-machine-cloudformation.html#lambda-state-machine-cfn-create-role
if not could you please add the permissions and try deploying the application.

[1] https://docs.amplify.aws/cli/reference/iam/

**Comment by johnf** [comment]
I'm seeing the same issue and I suspect it is a cdk issue rather than an amplify one

**Comment by MtthwBrwng** [comment]
I'm also experiencing this issue, I've attempted to do some digging into how to provide `ServiceprincipalMap` & `service principal` to no avail. Is this something that needs to be configured in the IAM console? Are there any code examples showing how to fix this issue using the CDK SDKs using Amplify?

**Comment by dreamorosi** [comment]
> I'm seeing the same issue and I suspect it is a cdk issue rather than an amplify one

Trying to deploy the same kind of component in CDK (`1.153.1`) alone (so without Amplify involved) doesn't show the same issue though:

<img width="753" alt="Screenshot 2022-04-27 at 16 44 04" src="https://user-images.githubusercontent.com/7353869/166295516-aea36630-a8b9-4363-b95c-260962237a18.png">

```yaml
Resources:
  StateMachineRoleB840431D:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                Fn::Join:
                  - ""
                  - - states.
                    - Ref: AWS::Region
                    - .amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: CdkSfnTestStack/StateMachine/Role/Resource
  StateMachine2E01A3A5:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn:
        Fn::GetAtt:
          - StateMachineRoleB840431D
          - Arn
      DefinitionString: '{"StartAt":"PassState","States":{"PassState":{"Type":"Pass","End":true}}}'
    DependsOn:
      - StateMachineRoleB840431D
    Metadata:
      aws:cdk:path: CdkSfnTestStack/StateMachine/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/02MTQrCMBCFz9J9OjWIiDuha0HqCcJ0xGntRDKJLkLublM3rt4f37NgD3uwzdl9tMVx7jL6QJBv0eFsei8aQ8Jo+rsMpD4FpOrXYeTIXoqpYNZIr3sSrJVCvjpVs15Eujh8sGzMfy6G3QJ58M9tqlpKMeJHgkm7tz3CCXbNpMxtSBJ5IRh++gW2retksgAAAA==
    Metadata:
      aws:cdk:path: CdkSfnTestStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
```
