### ISSUE TITLE
Hosting - Creating a nested amplify project is not supported

### ISSUE THREAD

**Issue by chris-mds** [aws-amplify/amplify-cli#10832]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.10.0

### Amplify CLI Version

7.6.7

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Amplify Categories

hosting

### Amplify Commands

Not applicable

### Describe the bug

Since today our hosting CI/CD crashes when building the backend with the error message:
_Creating a nested amplify project is not supported. Project root detected: /codebuild/output/srcxxxxxxx/src/xxxxxx_
Because the only change from our successful build was a little bit of frontend code, we already thought that this bug cant be due to our latest change, so for testing we rolled back to the last successful build, but the error still occurs.

Any ideas?

### Expected behavior

CI/CD pipeline should build it like normal

### Reproduction steps

Redeploy a version in CI/CD pipeline 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @chris-mds :wave: thanks for raising this! Based on the repo I have a few follow-up questions:

- I see Amplify CLI version 7.6.7 is reported here, is this also the version used in Amplify Hosting? (by default Hosting will use `latest`)
- can you provide a minimal reproduction for this issue?
- looking at this path `/codebuild/output/srcxxxxxxx/src/xxxxxx`, did anything change in the buildspec (`amplify.yml`) that would cause the root path to be duplicated?

**Comment by chris-mds** [comment]
Hey @josefaidt,

Thank you for your help. Indeed we forgot to set the amplify build to our version and it was set to latest. After downgrading to our version it works again. Maybe this case might still be of interest to you.

BR Chris

**Comment by foobarnes** [comment]
I am also getting this error on the latest CLI version. Should I open a new issue or reopen this one?

No changes to `amplify.yml` in the last 24 hours.

- `npm i -g @aws-amplify/cli`
- Node 16.14.2
- Amplify CLI 9.2.0
- Mac

**Comment by lazpavel** [comment]
Hi @foobarnes, @bkmulusew can you check the path printed in the error message after `Project root detected:` and look for an `amplify` directory in that path? If exists it might be that at some point an attempt was made to initialize an amplify project in the path printed in the error message? Can you remove/rename that `amplify` directory and retry the `amplify init` command?

**Comment by phoenixbeats01** [comment]
Getting this problem too

**Comment by jeffearthx** [comment]
@lazpavel I am having the same issue.  It appears to be related to your commit #10744 .    

I am using an Nx Monorepo with the following amplify.yml.

```
version: 1
applications:
  - appRoot: apps/earthxapp
      backend:
        phases:
          build:
            commands:
              - amplifyPush --simple
      frontend:
        phases:
          preBuild:
            commands:
              - npm config set @gsap:registry https://npm.greensock.com/
              - npm config set //npm.greensock.com/:_authToken=XXXXXXXXXXXXXXXX
              - npm ci
              - amplify pull -y
          build:
            commands:
              - npx nx build --prod
      artifacts:
        baseDirectory: ../../dist/apps/earthxapp
          files:
            - '**/*'
```

The error I am getting is: 

```
Creating a nested amplify project is not supported. Project root detected: /codebuild/output/src098391460/src/earthx
2022-08-16T05:09:10.815Z [INFO]: Error: Creating a nested amplify project is not supported. Project root detected: /codebuild/output/src098391460/src/earthx
                                 at checkForNestedProject (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/helpers/projectUtils.js:9:15)
                                 at Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/pull.js:69:50)
                                 at Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:292:29)
                                 at processTicksAndRejections (internal/process/task_queues.js:95:5)
                                 at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:64:3)
                                 at Function.runMain (pkg/prelude/bootstrap.js:1848:13)
                                 at internal/main/run_main_module.js:17:47
                                 at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:142:5)
                                 at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:40:9)
                                 at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:165:13)
````

It appears someone else is also having this issue when using a monorepo.  [See #2908](https://github.com/aws-amplify/amplify-hosting/issues/2908)

Does this commit break Monorepos, or am I doing something wrong?

Thanks

**Comment by lazpavel** [comment]
Hi @jeffearthx, is the `amplify pull -y` the command that is causing the issue? can you get the output of `pwd` where the `amplify pull -y` command is executed?

**Comment by jeffearthx** [comment]
Hi @lazpavel , This is happening in the backend during the "amplifyPush --simple" command.  I modified my amplify,yml file to run pwd before and after the "amplifyPush --simple" script.

```
version: 1
applications:
    -   appRoot: apps/earthxapp
        backend:
            phases:
                build:
                    commands:
                        - pwd
                        - amplifyPush --simple
                        - pwd
        frontend:
            phases:
                preBuild:
                    commands:
                        - npm config set @gsap:registry https://npm.greensock.com/
                        - npm config set //npm.greensock.com/:_authToken=XXXXXXXXXXXX
                        - npm ci
                        - amplify pull -y
                build:
                    commands:
                        - npx nx build --prod
            artifacts:
                baseDirectory: ../../dist/apps/earthxapp
                files:
                    - '**/*'
```

The output in the AWS Amplify console is:

![Screen Shot 2022-08-16 at 10 54 53 AM](https://user-images.githubusercontent.com/67924375/184946617-957374b9-5dd5-4fa1-9988-778da22470a5.png)

I think "earthx/apps/earthxapp" should be correct for the Nx Monorepo setup.  "aws-exports.js" gets placed in "apps/earthxapp/src" on my system.

My "amplify/.config/project-config.json" file contains:

```
{
  "providers": [
    "awscloudformation"
  ],
  "projectName": "earthx",
  "version": "3.1",
  "frontend": "javascript",
  "javascript": {
    "framework": "angular",
    "config": {
      "SourceDir": "apps/earthxapp/src",
      "DistributionDir": "dist/apps/earthxapp",
      "BuildCommand": "nx build --prod",
      "StartCommand": "nx serve"
    }
  }
}
```

Note that if I change the following Environment variable in the AWS Amplify console from (latest):

![Screen Shot 2022-08-16 at 11 07 37 AM](https://user-images.githubusercontent.com/67924375/184948906-5c3e8662-9065-4ad1-8028-bcb162547d2f.png)

to (9.1.0):

![Screen Shot 2022-08-16 at 11 09 31 AM](https://user-images.githubusercontent.com/67924375/184949242-6e99ebac-6d17-4358-9f44-38b922e52b9b.png)

Then everything compiles and deploys correctly.

Thanks for looking into this.

**Comment by lazpavel** [comment]
I am trying to understand your folder structure, it looks that the `amplifyPush --simple` which triggers the `Running amplify pull to generate aws-exports.js file for frontend` is executed in the `/codebuild/output/src098391460/src/earthx/apps/earthxapp` but we detect an amplify project initialized in `/codebuild/output/src098391460/src/earthx/` (this one contains the `amplify` directory and `amplify/.config`). 
This is prevented in the >9.2.0 versions as it was creating a nested copy of the amplify project in the `/codebuild/output/src098391460/src/earthx/apps/earthxapp`. Please send us an email at `amplify-cli@amazon.com` and reference this ticket so I can schedule a call, I would like to better understand your case before I can tell if this is a bug or a configuration issue. Thank you

**Comment by NickEast12** [comment]
Just an FYI I was running 9.2.1 and having this issue, I downgraded to my colleague's version at 9.1.0 and it worked

**Comment by amorimrafael** [comment]
@NickEast12 it worked for me. For any reason the amplify version 9.2.1 broken for me...


thanks

**Comment by brianlenz** [comment]
We experienced the same issue in trying to set up front end hosting (Next.js) for our existing backend. Downgrading Amplify CLI to `9.1.0` worked around this error for us, too 👍

**Comment by agilxpgeoffrey** [comment]
Same issue for me. Downgrading to 9.1.0 solved it.

**Comment by gcmerz** [comment]
Wanted to +1 here. Also was trying to set up front end hosting for our existing backend. Downgrading to 9.1.0 solved this issue.

**Comment by AndresCreator** [comment]
For me the mistake was that for some reason I had different appIds from the project. Steps to solve

1. Delete `team-provider-info.json`
2. Get the appid of amplify project 
3. `amplify init --appId [id]`

**Comment by josefaidt** [comment]
Hey folks :wave: I've marked this as a documentation issue to improve the Hosting docs for monorepos. From your feedback here, it has become clear that the monorepo support with the buildspec `amplify.yml` file is confusing in that the `appRoot` is where `amplifyPush --simple` will run, which expects an `amplify/` directory in that root.

```
|- my-project/
|-- apps/
|--- my-react-app/
|---- amplify/
|---- package.json
|--- my-svelte-app/
```

**Comment by brianlenz** [comment]
Hi @josefaidt! It's possible documentation can be improved, but was there an intentional, breaking change from Amplify CLI `9.1.0` to the current Amplify CLI version? The behavior has changed, which is forcing us to stay pinned on an old CLI version.

The Monorepo setup works great in Amplify CLI `9.1.0`. Upgrading beyond it breaks the Amplify frontend build with [this error](https://github.com/aws-amplify/amplify-cli/issues/10832#issuecomment-1225879252).

Here's our setup:

```
|- repo/
|-- amplify.yml
|-- amplify/
|-- app/ (React Native project)
|--- package.json
|-- web/ (Next.js project)
|--- package.json
```

The `amplify.yml` sets the `webRoot` to the `web` directory where the front end is built and deployed. It would be great if this can continue to be supported in the CLI as it was in `9.1.0`. Are you suggesting that we need to _duplicate_ the `amplify` directory in the `web` directory in order to have compatibility with the latest CLI versions? Is there some reason that this stopped working in a minor CLI version release?

Thanks!

**Comment by brianlenz** [comment]
@josefaidt, thanks much for the quick response! We don't do any automated backend builds or pushes (we have **Enable full-stack continuous deployments (CI/CD)** turned _off_). We have an Amplify backend configured, but we manage it purely through the Amplify CLI (with manual invocations of `amplify push`). We are using the Amplify Hosting to build the front end, and that's where the monorepo issue lies for us (and I suspect other people here).

Contrary to the use case you mentioned, we have a _single_ Amplify project (so, a single backend) that we use with multiple Amplify "front ends" (one React Native, one Next.js). React Native is built manually, of course, but the Next.js uses automated builds through Amplify Hosting, which is where our Amplify CLI option is forced to `9.1.0`. Our `amplify.yml` is pretty standard. There are a couple of trivial custom commands, but it otherwise just does a `yarn run build` for Next.js with `appRoot: web`.

It seems that your suggestions are focused on automated backend builds and pushes, which we don't do. Our problem is _purely_ with the Amplify Hosting build process for the Next.js front end. As such, I'm not sure the options that you suggested are relevant to our use case?

Does this added context give you any other ideas as to how we might upgrade to the latest Amplify CLI?

FWIW, this:

> Previously the functionality would have _pulled_ your `amplify/` directory into `repo/web/amplify/` and initialize from there rather than using the `amplify/` directory at your monorepo root.

sounds like exactly what we want and need. It's unfortunate that it's no longer supported on the latest versions of the Amplify CLI 😕

**Comment by khandaresuyash** [comment]
Error: Creating a nested amplify project is not supported. Project root detected: /Users/suyashkhandare
Getting the same error for my newly created flutter project

Downgrading to 9.1.0. Won't work

**Comment by neal3000** [comment]
I am getting this error on amplify init  ,  try to add amplify to a new Xcode project
Error: Creating a nested amplify project is not supported. Project root detected: /Users/xxxxx
    at checkForNestedProject (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/helpers/projectUtils.js:9:15)
    at Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/commands/init.js:28:50)
    at Object.executeAmplifyCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:292:29)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async executePluginModuleCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:142:5)
    at async executeCommand (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/execution-manager.js:40:9)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:165:13)
npm -v
8.19.2
 node -v
v17.2.0
 amplify -v
10.0.0
pwd
/Users/xxxx/Development/Notify1

**Comment by josefaidt** [comment]
Hey @neal3000 do you have an `amplify` directory at `/Users/xxxxx`?

**Comment by hirveakshata** [comment]
> Getting this problem too when running `amplify init` inside a blank directory

I'm also facing the same problem.

**Comment by israx** [comment]
I had an `amplify` directory created by mistake on a parent root. I deleted it and worked.

**Comment by Tstepro** [comment]
I had an `amplify` directory created at `/Users/xxxx`. Deleting that resolved it.

**Comment by hadils** [comment]
I am having this problem. I have tried all the suggestions above to no avail. I have a monorepo with my web pages in the web/ subdirectory of the repo. I cannot find another instance of `amplify` anywhere in my system.

**Comment by islalr** [comment]
I had the same issues as above, a mono repo with the /amplify directory above the /artifacts/web appRoot. Managed to solve it this way with the recommendations above by changing the build.yml file in Amplify Console to this. Here's the complete build script. Didn't want to change my structure or downgrade. 

```

version: 1 
applications:
  - appRoot: artifacts/web
    env:
      variables:
        key: value
    frontend:
      phases:
        # IMPORTANT - Please verify your build commands
        build:
          commands: []
      artifacts:
        # IMPORTANT - Please verify your build output directory
        baseDirectory: /
        files:
          - '**/*'
      cache:
        paths: []
    backend:
      phases:
        preBuild:
          commands:
            - cd ..; amplifyPush --simple; cd -

```

**Comment by OperationalFallacy** [comment]
Didn't they retire `amplifyPush` script?

https://github.com/aws-amplify/amplify-hosting/blob/main/scripts/amplifyPush.sh

**Comment by thegrandpoobah** [comment]
This might not be useful, but I just started experiencing this issue as well.

Amplify CLI version on my workstation: 12.10.0
Amplify CLI version on the CI: 12.10.1 (i assume)

project structure:

```
/repo
  /amplify
  amplify.yml
  allll the other files for a vue.js frontend here (/src, /public, package.json, etc etc etc)
```

Up until todays push, everything was working fine, but I pushed a bunch of changes to backend (updated functions, changed schema etc) AND the amplify.yml file and receive that error now.

I tried a couple of the solutions here to no avail. Now I'm not sure what the next step is.

The amplify.yml file:
```yaml
 version: 1
backend:
  phases:
    # IMPORTANT - Please verify your build commands
    preBuild:
      commands:
        - npm install -g @aws-amplify/cli
    build:
      commands:
        - ln -fs /usr/local/bin/pip3.8 /usr/bin/pip3
        - ln -fs /usr/local/bin/python3.8 /usr/bin/python3
        - pip3 install --user pipenv
        #- pip3 install --upgrade setuptools
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands: 
        - echo "VUE_APP_RECAPTCHA=$RECAPTCHA" >> .env
        - echo "VUE_APP_GOOGLE_SITE_KEY=$GOOGLE_SITE_KEY" >> .env
        - npm run build
  artifacts:
    baseDirectory: dist/spa
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  phases:
    preTest:
      commands:
        - if [ "${AWS_BRANCH}" = "test" ]; then echo "test branch"; fi
    test:
      commands:
        #-if [ "${AWS_BRANCH}" = "test" ]; then curl -X POST https://app.testsigma.com/api/v1/execution_results -H '"Content-type:application/json"' -H "Authorization:$TESTSIGMA_API_KEY"  -d '{"executionId":"651"}'; fi
    postTest:
      commands:
        - if [ "${AWS_BRANCH}" = "test" ]; then echo "test completed"; fi
  artifacts:
    baseDirectory: dist/spa
    files:
      - '**/*'
```
