### ISSUE TITLE
@manyToMany join table should include data from the entire model

### ISSUE THREAD

**Issue by mikev10** [aws-amplify/amplify-cli#11233]
### Is this feature request related to a new or existing Amplify category?

api

### Is this related to another service?

Graphql

### Describe the feature you'd like to request

When using the @manyToMany relationship between @model types, it would be great if model data was returned in the get query for the model.  

### Describe the solution you'd like

When I use `@manyToMany` relationship between `@model` types and run a get query for one of the models, I would like the join table to return the details of the model.

For example, lets say I set up 2 models like this:
```
type Person @model {
  id: ID!
  firstName: String!
  lastName:` String!
  events: [Event] @manyToMany(relationName: "PersonEvents")
}
```

```
type Event @model {
  id: ID!
  eventName: String!
  eventDate: String!
  people: [Person ] @manyToMany(relationName: "PersonEvents")
}
```
This will create a join table, `PersonEvents` where I can insert the PersonID and EventID.
When I query `Person` I will get something like this:
```
id: "7f5253ef-32f2-44b5-8551-5f0814450b04"
firstName: "John"
...
events:
  items:
    0:
      createdAt: "2022-10-20T01:15:34.695Z"
      personID: "7f5253ef-32f2-44b5-8551-5f0814450b04"
      id:  "ff97267c-ff6c-4b15-9c81-fa9b109a772e"
      eventID: "173a709b-246d-4def-bf45-47c48d7050e3"
      owner: "3e5d5c22-07ca-4c06-ab50-fd85273b05e4"
      updatedAt: "2022-10-20T01:15:34.695Z"
```
This is not that useful, as I will need to make another API call to get the event data for this person.

It would be ideal when I query `Person` it would include the `Event` model data in the response. This is very similar to how `@hasMany` works.

for example:
```
id: "7f5253ef-32f2-44b5-8551-5f0814450b04"
firstName: "John"
...
events:
  items:
    0:
      createdAt: "2022-10-20T01:15:34.695Z"
      personID: "7f5253ef-32f2-44b5-8551-5f0814450b04"
      id:  "ff97267c-ff6c-4b15-9c81-fa9b109a772e"
      eventID: "173a709b-246d-4def-bf45-47c48d7050e3"
      event:
         eventName: String!
         eventDate: String!
      owner: "3e5d5c22-07ca-4c06-ab50-fd85273b05e4"
      updatedAt: "2022-10-20T01:15:34.695Z"
```
or the events items should only include data for the event so as not to include the `Person` data again.

### Describe alternatives you've considered

One alternative that I tried was creating a new model for all of the data I needed and using @hasMany as that did what I needed to.

For example:
```
type PersonEvent @model {
  id: ID!
  personId: ID! @index(name: "byPerson", sortKeyFields: ["id"])
  person: Person @belongsTo(fields: ["personId"])
  eventId: ID! @index(name: "byEvent", sortKeyFields: ["id"])
  event: Event @belongsTo(fields: ["eventId"])
}
```

```
type Person @model {
  id: ID!
  firstName: String!
  lastName:` String!
  personEvent : [PersonEvent ] @hasMany(indexName: "byPerson", fields: ["id"])
}
```

```
type Event @model {
  id: ID!
  eventName: String!
  eventDate: String!
  personEvent : [PersonEvent ] @hasMany(indexName: "byEvent", fields: ["id"])
}
```

This is not ideal at all and has redundant data.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change
