### ISSUE TITLE
CLI uses windows-style paths on Mac, and breaks everything

### ISSUE THREAD

**Issue by devxpy** [aws-amplify/amplify-cli#1142]
```
$ amplify codegen
✔ Downloaded the schema
✔ Generated GraphQL operations successfully and saved at app\src\main\graphql\com\amazonaws\amplify\generated\graphql
```

The output is stored in a folder with that name, not that path!

![image](https://user-images.githubusercontent.com/19492893/55186765-54823900-51bd-11e9-8041-1b04e8d97924.png)

```
$ ls app\src\main\graphql\com\amazonaws\amplify\generated\graphql
ls: appsrcmaingraphql\017m\amazonaws\amplifygeneratedgraphql: No such file or directory

$ ls app/src/main/graphql/com/amazonaws/amplify/generated/graphql
ls: app/src/main/graphql/com/amazonaws/amplify/generated/graphql: No such file or directory

$ ls "app\src\main\graphql\com\amazonaws\amplify\generated\graphql"
mutations.graphql     queries.graphql       subscriptions.graphql
```

---

```
$ amplify --version
1.1.8
$ node --version
v10.15.3
$ screenfetch 
                 -/+:.          dev@Devs-MacBook-Pro
                :++++.          OS: 64bit Mac OS X 10.14.4 18E226
               /+++/.           Kernel: x86_64 Darwin 18.5.0
       .:-::- .+/:-``.::-       Uptime: 1d 2h 26m
    .:/++++++/::::/++++++/:`    Packages: 73
  .:///////////////////////:`   Shell: fish 3.0.2
  ////////////////////////`     Resolution: 2880x1800
 -+++++++++++++++++++++++`      DE: Aqua
 /++++++++++++++++++++++/       WM: Quartz Compositor
 /sssssssssssssssssssssss.      WM Theme: Blue
 :ssssssssssssssssssssssss-     CPU: Intel Core i7-4750HQ @ 2.00GHz
  osssssssssssssssssssssssso/`  GPU: Intel Iris Pro
  `syyyyyyyyyyyyyyyyyyyyyyyy+`  RAM: 8525MiB / 16384MiB
   `ossssssssssssssssssssss/
     :ooooooooooooooooooo+.
      `:+oo+/:-..-:/+o+/-

```

**Comment by UnleashedMind** [comment]
Maybe it's because of the shell? I was not able to reproduce in bash or zshell on my Mac running macOS Sierra version 10.12.16

**Comment by yuth** [comment]
@devxpy could you paste the content from your `<project-root>/.graphqlconfig.yml` file. Make sure you obfuscate sensitive information before pasting it

**Comment by devxpy** [comment]
@yuth Looks like the `.graphqlconfig.yml` was the offender. It got transferred to me over a shared repo by my colleague (who uses windows).

Here's what it looked like, before I deleted it and ran `$ amplify add codegen ..` again.

```yaml
projects:
  My AppSync App:
    schemaPath: app\src\main\graphql\schema.json
    includes:
      - app\src\main\graphql\**\*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: ******************
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app\src\main\graphql\com\amazonaws\amplify\generated\graphql
        region: us-east-1
        maxDepth: 2
      endpoints:
        prod: >-
          **************************
```

So we should not commit this to source control, right??
