### ISSUE TITLE
Codegen desn`t download schema

### ISSUE THREAD

**Issue by psycura** [aws-amplify/amplify-cli#116]
**Describe the bug**
On use of amplify codegen generate --download
or amplify codegen generate

Messages in console:
```
✔ Downloaded the schema
✔ code generated successfully and saved in file API.js
```

but the file API.js is empty:
```
/* @flow */
/* eslint-disable */
//  This file was automatically generated and should not be edited.
```

**Comment by yuth** [comment]
Amplify codegen uses graphql operations (query, mutation and subscription) as input and generates the code. Do you have the graphql operations defined?

Could you clarify/update the following
1. list of files inside the`graphql` folder of your project
2. Can you share the content inside the `.graphqlconfig.yml` inside the root of your project.

**Comment by devautor** [comment]
@yuth Is this process documented somewhere, or an example maybe? I too can't find relevant resources, and have the same issue. Thanks!

**Comment by psycura** [comment]
@yuth 
1. I`m not sure what do you call `graphql` folder. I`m using default settings when added amplify api, ant as a result was created:
`amplify/backend/api/###projectName/` folder that include in root:
`build` folder
and list of files:
```
cloudformation-template.json
parameters.json
schema.graphql
schema.json
```

2.  `.graphqlconfig.yml `

```
proposalis:
  schemaPath: amplify/backend/api/proposalis/schema.json
  includes:
    - graphql/**/*.graphql
  excludes:
    - amplify/**
  extensions:
    amplify:
      graphQLApiId: xxxxxxxxxxxx
      codeGenTarget: flow
      generatedFileName: API.js
    endPoints: >-
      https://xxxxxxxxxxx.appsync-api.eu-central-1.amazonaws.com/graphql

```
