### ISSUE TITLE
About schemaPath in .graphqlconfig.yml

### ISSUE THREAD

**Issue by tamutamu** [aws-amplify/amplify-cli#11623]
### Amplify CLI Version

10.5.1

### Question

I am confused about schemaPath in .graphqlconfig.yml.

When run `amplify push`, schemaPaht is set to `src/graphql/schema.json`.

But, Once delete codegen settings by `amplify remove codegen` and add it by `amplify add codegen` then schemaPaht is set to `amplify/backend/api/[my app name]/build/schema.graphql`.

```
projects:
  amplifytypemui:
    schemaPath: amplify/backend/api/amplifytypemui/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
...
```

Which is correct?

How do I use those separately?
For example, is it when you want to reflect graphql code with amplified code generation without amplify push?
