### ISSUE TITLE
How to upgrade Node.js runtime of Lambda@edge, which is created by Next.js deployment?

### ISSUE THREAD

**Issue by hiroki-yoneda** [aws-amplify/amplify-cli#11939]
### Amplify CLI Version

Use amplify with subcommand AWS CLI(aws-cli/1.19.101).

### Question

How to upgrade Node.js runtime of Lambda@edge, which is created by Next.js deployment?

I know that the runtime can be changed in the management console. However, I would like to upgrade Lambda@edge via CloudFormation, CLI, etc.

![image](https://user-images.githubusercontent.com/40882629/217440929-97d89bbf-2fd9-4e17-a959-e1e4edef2f3a.png)

Does anyone know a good way to upgrade?

## Background

I deployed my Nextjs application to Amplify. I would like to upgrade the nodejs12.x used in Lambda@edge created by Amplify as it will be out of support. Therefore, I would like to know how to upgrade the Lambda@edge runtime.

## template.yml

Here is AWS CloudFormation template.

```YAML
AWSTemplateFormatVersion: "2010-09-09"
Description: "..."

Resources:
  IAMRoleForAmplify:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: amplify.amazonaws.com
            Action: "sts:AssumeRole"
      Description: "..."
      Policies:
        - PolicyName: "..."
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Resource: "*"
                Effect: Allow
                Action:
                  - "..."
  AmplifyConsole:
    Type: AWS::Amplify::App
    Properties:
      AccessToken: "..."
      Name: "..."
      Repository: "..."
      IAMServiceRole: !GetAtt IAMRoleForAmplify.Arn
      BasicAuthConfig:
        EnableBasicAuth: false
      EnvironmentVariables:
        - Name: AMPLIFY_MONOREPO_APP_ROOT
          Value: "..."
        - Name: AMPLIFY_DIFF_DEPLOY
          Value: "false"

      BuildSpec: |
        version: 1
        applications:
          - frontend:
              phases:
                preBuild:
                  commands:
                    - yarn install
                build:
                  commands:
                    - yarn run build
              artifacts:
                baseDirectory: .next
                files:
                  - '**/*'
              cache:
                paths:
                  - node_modules/**/*
            appRoot: "..."
  AmplifyDomain:
    Type: AWS::Amplify::Domain
    Properties:
      AppId: !GetAtt AmplifyConsole.AppId
      DomainName: example.com
      SubDomainSettings:
        - BranchName: !GetAtt AmplifyBranchProd.BranchName
          Prefix: ""
        - BranchName: !GetAtt AmplifyBranchProd.BranchName
          Prefix: master

  AmplifyBranchProd:
    Type: "AWS::Amplify::Branch"
    Properties:
      AppId: !GetAtt AmplifyConsole.AppId
      BranchName: master
      EnableAutoBuild: false


```

## Deploy

```sh
$ aws cloudformation deploy \
              --stack-name <STACK_NAME> \
              --template template.yaml \
              --capabilities CAPABILITY_IAM \
              --region <REGION> \
              --no-fail-on-empty-changeset

$ aws amplify start-job \
              --region <REGION> \
              --app-id=<APP_ID> \
              --branch-name=master \
              --job-type=RELEASE
```
