### ISSUE TITLE
Couldn't build correctly because of monorepo

### ISSUE THREAD

**Issue by ylilarry** [aws-amplify/amplify-cli#11956]
### Amplify CLI Version

10.7.1

### Question

After reading the documentation I am still confused how to use amplify to build my monorepo. My directory structure is
```
projectRoot/:
  package.json
  amplify.yml
  - reactapp/
       - package.json 
  - graphqlapp/
       - package.json
```

Now I only want amplify to build and publish the reactapp, because the graphqlapp is legacy that has been manually deployed with AWS sam. I ran `amplify publish` from the reactapp, but it seems that amplify always picks up my graphqlapp, tries to build it, and fails with an error, which is what I don't want. Moreover, amplify doesn't seem to be able to recognize the existence of the react app, because after it failed to publish, I went to the console and was only able to see the "backend", and the "frontend" says waiting to be deployed.

I have set the `amplify.yml` at the root directory with the content:

```
version: 1
applications:
  - appRoot: ./reactapp
    frontend:
      phases:
        preBuild:
          commands:
            - cd react-app
            - npm ci
        build:
          commands:
            - npm run build
      artifacts:
        files:
            - "**/*"
        discard-paths: yes
        baseDirectory: ./build
```

And also I've set the `AMPLIFY_MONOREPO_APP_ROOT` env in the command-line to `AMPLIFY_MONOREPO_APP_ROOT=/projectRoot/reactapp`.

What am I doing wrong?

How do I make it ignore the existence of graphqlapp entirely?
