### ISSUE TITLE
Analytics.record not working

### ISSUE THREAD

**Issue by dabit3** [aws-amplify/amplify-cli#12]
Do you want to request a feature or report a bug?
bug

What is the current behavior?
Analytics.record not registering events in Pinpoint

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
I've reproduced twice. Here are the steps I took to reproduce on the web:
1. create-react-app testing-analytics-app
2. amplify init
3. amplify add analytics
4. Add Amplify configuration to the app
5. Register event in the app:

```js
onClick = () => {
    console.log("triggered click event")
    Analytics.record({
      name: 'button press from web'
    })
  }
```

What is the expected behavior?
Events show up in Pinpoint console

Which versions of Amplify CLI, and which  OS are affected by this issue? Did this work in previous versions?
Amplify CLI: 0.1.13
OS: MacOS
Yes, this did work in previous versions

**Comment by dabit3** [comment]
Also, when I run the app, this is logged out to the console a couple of times:

`Get item: key is AWSPinpoint_0e2ef7de115e4413958625f7e10ec1c3 with options undefined`

**Comment by kaustavghosh06** [comment]
Hey Nader, could you please paste your CFN template?

**Comment by dabit3** [comment]
Sure, I have two that I've tested. Here is the first:

```
{
	"AWSTemplateFormatVersion": "2010-09-09",
	"Description": "Root stack for the Amplify AWS CloudFormation provider",
	"Parameters": {
		"DeploymentBucketName": {
			"Description": "Name of the common deployment bucket provided by the parent stack",
			"Type": "String",
			"Default": "DeploymentBucket"
		},
		"AuthRoleName": {
			"Type": "String",
			"Default": "AuthRoleName"
		},
		"UnauthRoleName": {
			"Type": "String",
			"Default": "UnauthRoleName"
		}
	},
	"Resources": {
		"DeploymentBucket": {
			"Type": "AWS::S3::Bucket",
			"DeletionPolicy": "Retain",
			"Properties": {
				"BucketName": {
					"Ref": "DeploymentBucketName"
				}
			}
		},
		"AuthRole": {
			"Type": "AWS::IAM::Role",
			"Properties": {
				"RoleName": {
					"Ref": "AuthRoleName"
				},
				"AssumeRolePolicyDocument": {
					"Version": "2012-10-17",
					"Statement": [
						{
							"Sid": "",
							"Effect": "Allow",
							"Principal": {
								"Federated": "cognito-identity.amazonaws.com"
							},
							"Action": "sts:AssumeRoleWithWebIdentity",
							"Condition": {
								"ForAnyValue:StringLike": {
									"cognito-identity.amazonaws.com:amr": "authenticated"
								}
							}
						}
					]
				}
			}
		},
		"UnauthRole": {
			"Type": "AWS::IAM::Role",
			"Properties": {
				"RoleName": {
					"Ref": "UnauthRoleName"
				},
				"AssumeRolePolicyDocument": {
					"Version": "2012-10-17",
					"Statement": [
						{
							"Sid": "",
							"Effect": "Allow",
							"Principal": {
								"Federated": "cognito-identity.amazonaws.com"
							},
							"Action": "sts:AssumeRoleWithWebIdentity",
							"Condition": {
								"ForAnyValue:StringLike": {
									"cognito-identity.amazonaws.com:amr": "unauthenticated"
								}
							}
						}
					]
				}
			}
		},
		"authcognito67f97637": {
			"Type": "AWS::CloudFormation::Stack",
			"Properties": {
				"TemplateURL": "https://s3.amazonaws.com/deletethis-20180824103338-deployment/amplify-cfn-templates/auth/cognito67f97637-cloudformation-template.yml",
				"Parameters": {
					"identityPoolName": "deletethis_identitypool_cbc3c54b",
					"allowUnauthenticatedIdentities": true,
					"thirdPartyAuth": false,
					"lambdaLogPolicy": "deletethis_lambda_log_policy",
					"openIdLambdaRoleName": "deletethis_openid_lambda_role",
					"openIdRolePolicy": "deletethis_openid_pass_role_policy",
					"openIdLambdaIAMPolicy": "deletethis_openid_lambda_iam_policy",
					"openIdLogPolicy": "deletethis_openid_lambda_log_policy",
					"authSelections": "identityPoolOnly",
					"resourceName": "cognito67f97637",
					"unAuthRoleName": "deletethis-20180824103338-unauthRole",
					"authRoleName": "deletethis-20180824103338-authRole",
					"unAuthRoleArn": "arn:aws:iam::557458351015:role/deletethis-20180824103338-unauthRole",
					"authRoleArn": "arn:aws:iam::557458351015:role/deletethis-20180824103338-authRole"
				}
			}
		},
		"analyticsdeletethis": {
			"Type": "AWS::CloudFormation::Stack",
			"Properties": {
				"TemplateURL": "https://s3.amazonaws.com/deletethis-20180824103338-deployment/amplify-cfn-templates/analytics/pinpoint-cloudformation-template.json",
				"Parameters": {
					"appName": "deletethis",
					"roleName": "pinpointLambdaRoleef9325ee",
					"cloudWatchPolicyName": "cloudWatchPolicyef9325ee",
					"pinpointPolicyName": "pinpointPolicyef9325ee",
					"authPolicyName": "pinpoint_amplify_ef9325ee",
					"unauthPolicyName": "pinpoint_amplify_ef9325ee",
					"authRoleName": "deletethis-20180824103338-authRole",
					"unauthRoleName": "deletethis-20180824103338-unauthRole",
					"IAMPrefix": "557458351015"
				}
			}
		}
	},
	"Outputs": {
		"Region": {
			"Description": "CloudFormation provider root stack Region",
			"Value": {
				"Ref": "AWS::Region"
			},
			"Export": {
				"Name": {
					"Fn::Sub": "${AWS::StackName}-Region"
				}
			}
		},
		"StackName": {
			"Description": "CloudFormation provider root stack ID",
			"Value": {
				"Ref": "AWS::StackName"
			},
			"Export": {
				"Name": {
					"Fn::Sub": "${AWS::StackName}-StackName"
				}
			}
		},
		"StackId": {
			"Description": "CloudFormation provider root stack name",
			"Value": {
				"Ref": "AWS::StackId"
			},
			"Export": {
				"Name": {
					"Fn::Sub": "${AWS::StackName}-StackId"
				}
			}
		},
		"DeploymentBucketName": {
			"Description": "CloudFormation provider root stack deployment bucket name",
			"Value": {
				"Ref": "DeploymentBucketName"
			},
			"Export": {
				"Name": {
					"Fn::Sub": "${AWS::StackName}-DeploymentBucketName"
				}
			}
		},
		"AuthRoleArn": {
			"Value": {
				"Fn::GetAtt": [
					"AuthRole",
					"Arn"
				]
			}
		},
		"UnauthRoleArn": {
			"Value": {
				"Fn::GetAtt": [
					"UnauthRole",
					"Arn"
				]
			}
		},
		"AuthRoleName": {
			"Value": {
				"Ref": "AuthRole"
			}
		},
		"UnauthRoleName": {
			"Value": {
				"Ref": "UnauthRole"
			}
		}
	}
}
```

**Comment by dabit3** [comment]
Here is the second:

```yaml
{
	"AWSTemplateFormatVersion": "2010-09-09",
	"Description": "Root stack for the Amplify AWS CloudFormation provider",
	"Parameters": {
		"DeploymentBucketName": {
			"Description": "Name of the common deployment bucket provided by the parent stack",
			"Type": "String",
			"Default": "DeploymentBucket"
		},
		"AuthRoleName": {
			"Type": "String",
			"Default": "AuthRoleName"
		},
		"UnauthRoleName": {
			"Type": "String",
			"Default": "UnauthRoleName"
		}
	},
	"Resources": {
		"DeploymentBucket": {
			"Type": "AWS::S3::Bucket",
			"Properties": {
				"BucketName": {
					"Ref": "DeploymentBucketName"
				}
			}
		},
		"AuthRole": {
			"Type": "AWS::IAM::Role",
			"Properties": {
				"RoleName": {
					"Ref": "AuthRoleName"
				},
				"AssumeRolePolicyDocument": {
					"Version": "2012-10-17",
					"Statement": [
						{
							"Sid": "",
							"Effect": "Allow",
							"Principal": {
								"Federated": "cognito-identity.amazonaws.com"
							},
							"Action": "sts:AssumeRoleWithWebIdentity",
							"Condition": {
								"ForAnyValue:StringLike": {
									"cognito-identity.amazonaws.com:amr": "authenticated"
								}
							}
						}
					]
				}
			}
		},
		"UnauthRole": {
			"Type": "AWS::IAM::Role",
			"Properties": {
				"RoleName": {
					"Ref": "UnauthRoleName"
				},
				"AssumeRolePolicyDocument": {
					"Version": "2012-10-17",
					"Statement": [
						{
							"Sid": "",
							"Effect": "Allow",
							"Principal": {
								"Federated": "cognito-identity.amazonaws.com"
							},
							"Action": "sts:AssumeRoleWithWebIdentity",
							"Condition": {
								"ForAnyValue:StringLike": {
									"cognito-identity.amazonaws.com:amr": "unauthenticated"
								}
							}
						}
					]
				}
			}
		},
		"authcognito72b5a335": {
			"Type": "AWS::CloudFormation::Stack",
			"Properties": {
				"TemplateURL": "https://s3.amazonaws.com/amplifyexpo-20180822160552-deployment/amplify-cfn-templates/cognito72b5a335-cloudformation-template.yml",
				"Parameters": {
					"identityPoolName": "cognito72b5a335_identitypool_72b5a335",
					"allowUnauthenticatedIdentities": true,
					"thirdPartyAuth": false,
					"lambdaLogPolicy": "cognito72b5a335_lambda_log_policy",
					"openIdLambdaRoleName": "cognito72b5a335_openid_lambda_role",
					"openIdRolePolicy": "cognito72b5a335_openid_pass_role_policy",
					"openIdLambdaIAMPolicy": "cognito72b5a335_openid_lambda_iam_policy",
					"openIdLogPolicy": "cognito72b5a335_openid_lambda_log_policy",
					"userPoolName": "cognito72b5a335_userpool_72b5a335",
					"autoVerifiedAttributes": "email",
					"mfaConfiguration": "OFF",
					"mfaTypes": "SMS Text Message",
					"roleName": "cognito72b5a335_sns-role",
					"roleExternalId": "cognito72b5a335_role_external_id",
					"policyName": "cognito72b5a335-sns-policy",
					"smsAuthenticationMessage": "Your authentication code is {####}",
					"smsVerificationMessage": "Your verification code is {####}",
					"emailVerificationSubject": "Your verification code",
					"emailVerificationMessage": "Your verification code is {####}",
					"defaultPasswordPolicy": false,
					"passwordPolicyMinLength": 8,
					"passwordPolicyCharacters": "Requires Lowercase,Requires Uppercase,Requires Numbers,Requires Symbols",
					"requiredAttributes": "email",
					"userpoolClientName": "cognito72b5a335_app_client",
					"userpoolClientGenerateSecret": true,
					"userpoolClientRefreshTokenValidity": 30,
					"userpoolClientReadAttributes": "email",
					"mfaLambdaRole": "cognito72b5a335_totp_lambda_role",
					"mfaLambdaLogPolicy": "cognito72b5a335_totp_lambda_log_policy",
					"mfaPassRolePolicy": "cognito72b5a335_totp_pass_role_policy",
					"mfaLambdaIAMPolicy": "cognito72b5a335_totp_lambda_iam_policy",
					"userpoolClientLambdaRole": "cognito72b5a335_userpoolclient_lambda_role",
					"userpoolClientLogPolicy": "cognito72b5a335_userpoolclient_lambda_log_policy",
					"userpoolClientLambdaPolicy": "cognito72b5a335_userpoolclient_lambda_iam_policy",
					"userpoolClientSetAttributes": false,
					"useDefault": "default",
					"unAuthRoleName": "amplifyexpo-20180822160552-unauthRole",
					"authRoleName": "amplifyexpo-20180822160552-authRole",
					"unAuthRoleArn": "arn:aws:iam::557458351015:role/amplifyexpo-20180822160552-unauthRole",
					"authRoleArn": "arn:aws:iam::557458351015:role/amplifyexpo-20180822160552-authRole",
					"resourceName": "cognito72b5a335",
					"authSelections": "identityPoolAndUserPool"
				}
			}
		},
		"apiamplifyexpotest": {
			"Type": "AWS::CloudFormation::Stack",
			"Properties": {
				"TemplateURL": "https://s3.amazonaws.com/amplifyexpo-20180822160552-deployment/amplify-cfn-templates/cloudformation-template.json",
				"Parameters": {
					"AppSyncApiName": "amplifyexpotest",
					"schemaGraphql": "s3://amplifyexpo-20180822160552-deployment/amplify-appsync-files/schema.graphql.1535048336276",
					"MutationCreatePetResponse": "s3://amplifyexpo-20180822160552-deployment/amplify-appsync-files/Mutation.createPet.response.1535048336276",
					"MutationCreatePetRequest": "s3://amplifyexpo-20180822160552-deployment/amplify-appsync-files/Mutation.createPet.request.1535048336276",
					"MutationDeletePetRequest": "s3://amplifyexpo-20180822160552-deployment/amplify-appsync-files/Mutation.deletePet.request.1535048336276",
					"QueryGetPetRequest": "s3://amplifyexpo-20180822160552-deployment/amplify-appsync-files/Query.getPet.request.1535048336276",
					"QueryListPetResponse": "s3://amplifyexpo-20180822160552-deployment/amplify-appsync-files/Query.listPet.response.1535048336276",
					"QueryGetPetResponse": "s3://amplifyexpo-20180822160552-deployment/amplify-appsync-files/Query.getPet.response.1535048336276",
					"MutationUpdatePetResponse": "s3://amplifyexpo-20180822160552-deployment/amplify-appsync-files/Mutation.updatePet.response.1535048336276",
					"MutationUpdatePetRequest": "s3://amplifyexpo-20180822160552-deployment/amplify-appsync-files/Mutation.updatePet.request.1535048336276",
					"MutationDeletePetResponse": "s3://amplifyexpo-20180822160552-deployment/amplify-appsync-files/Mutation.deletePet.response.1535048336276",
					"QueryListPetRequest": "s3://amplifyexpo-20180822160552-deployment/amplify-appsync-files/Query.listPet.request.1535048336276"
				}
			}
		},
		"apimylambdaapi": {
			"Type": "AWS::CloudFormation::Stack",
			"Properties": {
				"TemplateURL": "https://s3.amazonaws.com/amplifyexpo-20180822160552-deployment/amplify-cfn-templates/mylambdaapi-cloudformation-template.json",
				"Parameters": {
					"functionmylambdaapifunctionName": {
						"Fn::GetAtt": [
							"functionmylambdaapifunction",
							"Outputs.Name"
						]
					},
					"functionmylambdaapifunctionArn": {
						"Fn::GetAtt": [
							"functionmylambdaapifunction",
							"Outputs.Arn"
						]
					}
				}
			}
		},
		"functionmylambdaapifunction": {
			"Type": "AWS::CloudFormation::Stack",
			"Properties": {
				"TemplateURL": "https://s3.amazonaws.com/amplifyexpo-20180822160552-deployment/amplify-cfn-templates/mylambdaapifunction-cloudformation-template.json",
				"Parameters": {}
			}
		},
		"analyticsamplifyexpoanalytics": {
			"Type": "AWS::CloudFormation::Stack",
			"Properties": {
				"TemplateURL": "https://s3.amazonaws.com/amplifyexpo-20180822160552-deployment/amplify-cfn-templates/pinpoint-cloudformation-template.json",
				"Parameters": {
					"appName": "amplifyexpoanalytics",
					"roleName": "pinpointLambdaRolecac20dcd",
					"cloudWatchPolicyName": "cloudWatchPolicycac20dcd",
					"pinpointPolicyName": "pinpointPolicycac20dcd",
					"authPolicyName": "pinpoint_amplify_cac20dcd",
					"unauthPolicyName": "pinpoint_amplify_cac20dcd",
					"authRoleName": "amplifyexpo-20180822160552-authRole",
					"unauthRoleName": "amplifyexpo-20180822160552-unauthRole",
					"IAMPrefix": "557458351015"
				}
			}
		}
	},
	"Outputs": {
		"Region": {
			"Description": "CloudFormation provider root stack Region",
			"Value": {
				"Ref": "AWS::Region"
			},
			"Export": {
				"Name": {
					"Fn::Sub": "${AWS::StackName}-Region"
				}
			}
		},
		"StackName": {
			"Description": "CloudFormation provider root stack ID",
			"Value": {
				"Ref": "AWS::StackName"
			},
			"Export": {
				"Name": {
					"Fn::Sub": "${AWS::StackName}-StackName"
				}
			}
		},
		"StackId": {
			"Description": "CloudFormation provider root stack name",
			"Value": {
				"Ref": "AWS::StackId"
			},
			"Export": {
				"Name": {
					"Fn::Sub": "${AWS::StackName}-StackId"
				}
			}
		},
		"DeploymentBucketName": {
			"Description": "CloudFormation provider root stack deployment bucket name",
			"Value": {
				"Ref": "DeploymentBucketName"
			},
			"Export": {
				"Name": {
					"Fn::Sub": "${AWS::StackName}-DeploymentBucketName"
				}
			}
		},
		"AuthRoleArn": {
			"Value": {
				"Fn::GetAtt": [
					"AuthRole",
					"Arn"
				]
			}
		},
		"UnauthRoleArn": {
			"Value": {
				"Fn::GetAtt": [
					"UnauthRole",
					"Arn"
				]
			}
		},
		"AuthRoleName": {
			"Value": {
				"Ref": "AuthRole"
			}
		},
		"UnauthRoleName": {
			"Value": {
				"Ref": "UnauthRole"
			}
		}
	}
}
```
