### ISSUE TITLE
Create Custom Attributes in cognito from amplify cli

### ISSUE THREAD

**Issue by achutkiran** [aws-amplify/amplify-cli#1204]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
Amplify Auth

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
Is there a way to create custom attributes in cognito during 
`amplify auth add`
or by editing parameters.json

**Comment by kaustavghosh06** [comment]
@achutkiran Are you referring to the social provider custom attributes?

**Comment by achutkiran** [comment]
User pool custom attributes  like customer type

**Comment by jarrettj** [comment]
+1

**Comment by timkuilman** [comment]
You can manually change the `cognito-cloudformation-template.yml` file after adding the authentication (but before running `amplify push`.

[AWS properties Cognito UserPool](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-schemaattribute.html)


_Snippet cognito-cloudformation-template.yml_
```   
....
# BEGIN USER POOL RESOURCES
  UserPool:
  # Created upon user selection
  # Depends on SNS Role for Arn if MFA is enabled
    Type: AWS::Cognito::UserPool
    UpdateReplacePolicy: Retain
    Properties:
      UserPoolName: !If [ShouldNotCreateEnvResources, !Ref userPoolName, !Join ['',[!Ref userPoolName, '-', !Ref env]]]
      Schema:
        - Name: myCustomAttribute
          Required: true
          Mutable: true
          AttributeDataType: String

        - Name: myOtherCustomAttribute
          Required: false
          Mutable: true
          AttributeDataType: String

      AutoVerifiedAttributes: !Ref autoVerifiedAttributes
      Policies:
        PasswordPolicy:
          MinimumLength: !Ref passwordPolicyMinLength
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      MfaConfiguration: !Ref mfaConfiguration
      SmsVerificationMessage: !Ref smsVerificationMessage
      SmsConfiguration:
        SnsCallerArn: !GetAtt SNSRole.Arn
        ExternalId: !Ref roleExternalId
...

```

**Comment by achutkiran** [comment]
Presently I am editing cloudFormationTemplate and parameters.json to add custom Attributes and groups. But problem is for any reason whenever i update auth i have to update template manually. So it will be better if custom Attributes are included in amplify cli.

**Comment by kaustavghosh06** [comment]
@achutkiran You're right, we don't have in-built support for custom attributes yet and what you're trying out is currently the best way to go about it, but I'll tag this as a feture request and prioritize work on this.

**Comment by jarrettj** [comment]
@timkuilman @achutkiran Yes I figured that out. I prefer editing the CF templates as well. Been a while since I've been in there. But not too hard to follow. And it would be impossible to have all the AWS service options in the cli anyways. Thanks.

**Comment by achutkiran** [comment]
Thanks

**Comment by yukitaka13-1110** [comment]
I tried https://github.com/aws-amplify/amplify-cli/issues/1204#issuecomment-482028480 and update auth, but an update error occured.

cloudformation.yml
```yml
        - Name: custom:store_name
          Required: true
          Mutable: true
          AttributeDataType: String
```

parameter.json
```json
    "requiredAttributes": [
        "...",
        "custom:store_name"
    ],
```

Am I wrong in specifying?
