### ISSUE TITLE
codegen statements no longer generating graphql files

### ISSUE THREAD

**Issue by sebekz** [aws-amplify/amplify-cli#12195]
### Amplify CLI Version

10.8.1

### Question

I am upgrading CLI from **6.1.1** to **10.8.1** (it's quite a leap!) and running into issues with with `queries.graphql`, `mutations.graphql` and `subscriptions.graphql` file generation.

### Configuration
Amplify CLI 10.8.1

`.graphqlconfig.yml`

```yaml
projects:
  acme-project:
    schemaPath: amplify/backend/api/acme-project/build/schema.graphql
    includes:
      - amplify-generated/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        docsFilePath: amplify-generated/graphql
        region: us-west-2
        apiId: abcdefg
        maxDepth: 11        
extensions:
  amplify:
    version: 5
```

### Problem
When `codeGenTarget: typescript` is specified in `.graphqlconfig.yml`, none of these work to generate `.graphql` files:

- `amplify codegen` generates only `.ts` files
- `amplify codegen statements` generates only `.ts` files

`queries.graphql`, `mutations.graphql` and `subscriptions.graphql` files are not generated/updated in the path specified by `docsFilePath` or in any other path in the system.

I was able to confirm that with amplify CLI version **6.1.1** running 

`amplify codegen statements` 

works as intended. With **6.1.1** all three `.graphql` files are being generated and put in `amplify-generated/graphql` alongside `mutations.ts`, `queries.ts` and `subscriptions.ts` files.

However, if I change `codeGenTarget` to say 

`codeGenTarget: graphql`

`queries.graphql`, `mutations.graphql` and `subscriptions.graphql` files are correctly generated. But then `mutations.ts`, `queries.ts` and `subscriptions.ts` are not generated. 

And I need both `.graphql` and `.ts` files. That's how greedy I am!

The only way to currently work around this problem for me was creating a script and swapping `codeGenTarget` values in the `.graphqlconfig.yml` file on the fly so that it says `codeGenTarget: graphql` before running `amplify codegen statements` and then change it back to `codeGenTarget: typescript` before running `amplify codegen` again. 

That way I had all six files created/updated correctly, but it's a nasty workaround.

### Question
Is it an expected behavior in the current CLI version or am I missing something obvious? The documentation was not particularly helpful in this case.
