### ISSUE TITLE
Custom resolver: should not worry about resolver resource

### ISSUE THREAD

**Issue by YikSanChan** [aws-amplify/amplify-cli#1272]
**Is your feature request related to a problem? Please describe.**
According to doc https://aws-amplify.github.io/docs/cli/graphql#add-a-custom-resolver-that-targets-a-dynamodb-table-from-model, users can add a custom resolver by:
1. Add a resolver resource to a stack in the stacks/ directory.
2. Add a resolver template in resolvers/ directory.

Doing above has the same effect as adding a custom resolver in AppSync console, but it gains the benefit of version control.

However, I do notice that adding a custom resolver in AppSync console doesn't ask me to add a resolver resource manually. That's why I propose: adding a custom resolver via resources/ should not, either. 

**Describe the solution you'd like**
Write the resolver file in VTL only, and do not have to worry about implementing the resolver resource file.

**Comment by mikeparisstuff** [comment]
@YikSanChan We have discussed something like this in the past and I'm curious how you would like to see this done. A few things to consider:

1. How does this work with pipeline resolvers?
2. If a unit resolver, how do you specify the data source? 
3. If I write a req.vtl and not a res.vtl what happens? Vice versa?

Open to suggestions here. I think one option would be to consider using a structured file with good support for multi-line strings such as toml or yaml. Use one file per resolver and likewise one function per function. A single resolver might look like this:

In toml:

```toml
# Query.getPost.toml
[resolver]
request = """
{
  "operation": "GetItem",
  "key": { "id": { "S": "$ctx.args.id" } }
}
"""
response = """
$util.toJson($ctx.result)
"""
datasource = PostTable
```

In yaml:

```yaml
# Query.getPost.yaml
resolver:
  request: >
    {
      "operation": "GetItem",
      "key": { "id": { "S": "$ctx.args.id" } }
    }
  response: "$util.toJson($ctx.result)"
  datasource: PostTable
```
