### ISSUE TITLE
New python issue with 'egg_info'

### ISSUE THREAD

**Issue by pm98zz-c** [aws-amplify/amplify-cli#12879]
### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

16.19 (but irrelevant)

### Amplify CLI Version

latest (from AWS deploy)

### What operating system are you using?

amazon linux 2 container (from AWS deploy)

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Describe the bug

One python function part of the project stopped being able to build since last week and this week, with no change whatsoever in amplify.yml nor amplify folder or the function itself

### Expected behavior

Expected the function continue to build as usual.

### Reproduction steps

I suppose (but can't be certain) any python using 3.8 as runtime would be affected.
My amplify.yml looks like this
```
backend:
  phases:
    preBuild:
      commands:
        - nvm install $VERSION_NODE_16
    build:
      commands:
        - '# Make sure we prefetch needed packages'
        - set -xe
        - yarn install
        - '# Change the current version of python'
        - ln -fs /usr/local/bin/pip3.8 /usr/bin/pip3
        - ln -fs /usr/local/bin/python3.8 /usr/bin/python3
        - ln -fs /usr/local/bin/pip3.8 /usr/bin/pip # not originally there, added to try to fix the issue in question
        - pip3 install --upgrade pip setuptools # not originally there, added to try to fix the issue in question
        - pip3 install pipenv
        - amplifyPush --simple
```

### Log output

<details>

```
2023-06-29T08:18:25.824Z [WARNING]: Successfully created virtual environment!
2023-06-29T08:18:25.930Z [WARNING]: Virtualenv location: /root/.local/share/virtualenvs/cerfa-pQyvUyL2
2023-06-29T08:18:26.038Z [INFO]: Installing dependencies from Pipfile.lock (0b4f62)...
2023-06-29T08:18:26.181Z [WARNING]: usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
                                    or: setup.py --help [cmd1 cmd2 ...]
                                    or: setup.py --help-commands
                                    or: setup.py cmd --help
                                    error: invalid command 'egg_info'
```

</details>

### Additional information

I suspect it could actually something to do with an update in the amazon linux 2 image, as my amplify-cli version was pinned to 12.0.3 because of https://github.com/aws-amplify/amplify-cli/issues/12793, so should not be tied to a cli update.

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.
