### ISSUE TITLE
Existing schema attributes cannot be modified or deleted.

### ISSUE THREAD

**Issue by tscole** [aws-amplify/amplify-cli#13095]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.16.0

### Amplify CLI Version

12.2.3

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Custom attributes added in yml for cognition user pool:

```yaml
      Schema:
        - Name: email
          Required: true
          Mutable: true
        - Name: stripe_id
          Mutable: 'true'
          AttributeDataType: String
          StringAttributeConstraints:
            MaxLength: '256'
            MinLength: '1'
        - Name: stripe_sub_id
          Mutable: 'true'
          AttributeDataType: String
          StringAttributeConstraints:
            MaxLength: '256'
            MinLength: '1'
        - Name: stripe_plan_name
          Mutable: 'true'
          AttributeDataType: String
        - Name: company
          Mutable: 'true'
          AttributeDataType: String
        - Name: vat_number
          Mutable: 'true'
          AttributeDataType: String
        - Name: address_1
          Mutable: 'true'
          AttributeDataType: String
        - Name: address_2
          Mutable: 'true'
          AttributeDataType: String
        - Name: city
          Mutable: 'true'
          AttributeDataType: String
        - Name: postcode
          Mutable: 'true'
          AttributeDataType: String
        - Name: state
          Mutable: 'true'
          AttributeDataType: String
        - Name: country
          Mutable: 'true'
          AttributeDataType: String
```

### Describe the bug

This is an old project that hasn't had any work for a while.
After upgrading to amplify cli v12.2.3 the .yml file is deleted and override.ts is required for custom attributes.

I have the following override.ts in place:

```ts
import { AmplifyAuthCognitoStackTemplate } from "@aws-amplify/cli-extensibility-helper";

export function override(resources: AmplifyAuthCognitoStackTemplate) {
  resources.userPool.schema = [
    ...(resources.userPool.schema as any[]), // Carry over existing attributes (example: email)
    {
      attributeDataType: "String",
      mutable: true,
      name: "email",
      required: true,
    },
    {
      attributeDataType: "String",
      mutable: true,
      name: "stripe_id",
      stringAttributeConstraints: {
        maxLength: "256",
        minLength: "1",
      },
    },
    {
      attributeDataType: "String",
      mutable: true,
      name: "stripe_sub_id",

      stringAttributeConstraints: {
        maxLength: "256",
        minLength: "1",
      },
    },
    {
      attributeDataType: "String",
      mutable: true,
      name: "stripe_plan_name",
    },
    {
      attributeDataType: "String",
      mutable: true,
      name: "company",
    },
    {
      attributeDataType: "String",
      mutable: true,
      name: "address_1",
    },
    {
      attributeDataType: "String",
      mutable: true,
      name: "address_2",
    },
    {
      attributeDataType: "String",
      mutable: true,
      name: "city",
    },
    {
      attributeDataType: "String",
      mutable: true,
      name: "state",
    },
    {
      attributeDataType: "String",
      mutable: true,
      name: "postcode",
    },
    {
      attributeDataType: "String",
      mutable: true,
      name: "country",
    },
    {
      attributeDataType: "String",
      mutable: true,
      name: "vat_number",
    },
  ];
}
```

However attempting amplify push results in the error  **Existing schema attributes cannot be modified or deleted.**

I am therefore unable to do any further work to the back end of this project as all pushes fail.

### Expected behavior

Pushing should work because override.ts should mean that cognito attributes aren't being changed.

### Reproduction steps

You will need to start with an earlier version of the amplify cli and use the supplied yaml file to create the custom attributes. Upgrade to the latest CLI and then attempt a push using the supplied override.ts. 

### Project Identifier

dbbb418abb38539d3a09d33eacc39132

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.
