### ISSUE TITLE
first class support for CI   

### ISSUE THREAD

**Issue by lielran** [aws-amplify/amplify-cli#1322]
**Is your feature request related to a problem? Please describe.**
It seems to me that aws-amplify did a great job in creating, manage and sharing cloud environments but when it comes to CI/CD process, it can be better. 
the documentation has only a small area that mentions the headless scripts, which I found complex and also require external tooling for mocking the user manual steps in the setup process.  

**Describe the solution you'd like**
Support for CI. as we store all the needed files in SCM we can add another file for CI with all the configs. most of the cli tools that I know that aim for CI knows how to fetch data from env vars or config files.

**Describe alternatives you've considered**
using the headless files. here again not sure what to use and in what order. 
for example, I've aws creds as env vars, should I run aws_init.sh?

**Comment by ambientlight** [comment]
Agree with this. 
Related issue: https://github.com/aws-amplify/amplify-cli/issues/1236

**Comment by lielran** [comment]
Thanks @ambientlight ,   this what works for me:
```
# .circleci/config.yml
executors:
  node-executor:
     docker:
      - image: circleci/node:latest
deploy:
    executor: node-executor
    steps:
```

**Comment by UnleashedMind** [comment]
@lielran 
Could you provide more details on the kind of the CI/CD solution you'd like to have? 
Do you want to integrate with existing CI/CD tools or you want the Aamplify CLI itself to be able to provide CI/CD capabilities?

**Comment by swaminator** [comment]
Also, have you checked out the Amplify Console? console.amplify.aws?

**Comment by oharaandrew314** [comment]
> Also, have you checked out the Amplify Console? https://console.amplify.aws

The Amplify Console is fine if you want to fragment your CI across several providers.  But if you want all of your builds to be in one place, then I'm afraid it's not helpful.

**Comment by lielran** [comment]
@UnleashedMind  So after trying Amplify console, I've decided to switch my CI/CD tool to CircleCi. 
in "external"(not an aws service)CI/CD tool you have to install amplify by yourself and the configuration and setup is not easy. 
the documentation point to the headless scripts which I found very not easy to integrate, slow and error prune (stdin/out to console that may change). I would try to avoid using the headless scripts. 

I would like to see the amplify cli will support/have: 
1) (also) support aws credentials as env vars (e.g. AWS_ACCESS_KEYS) 
2) CI is doing git clone, therefore is missing some files for amplify to work. it should be easy to switch to the right amplify env and create them. 
3) have documentation of ci/cd in multi aws accounts

**Comment by ambientlight** [comment]
@UnleashedMind: at very least amplify should be able to `configure projects` without requiring files that are .gitignored in default generated amplify project. (./amplify/.config/local-env-info.json and ./amplify/backend/amplify-meta.json)

**Comment by amcdnl** [comment]
OK - I'm trying to get this working and not having any luck... Maybe one of you have an idea:

Here is my Circle Config:
```
version: 2

# Docker image to use for setup
var_1: &docker_image circleci/node:11.14.0

# Job step for checking out the source code from GitHub. This also ensures that the source code
# is rebased on top of master.
var_2: &checkout_code
  checkout:
    # After checkout, rebase on top of master. By default, PRs are not rebased on top of master,
    # See https://discuss.circleci.com/t/1662
    post: git pull --ff-only origin "refs/pull/${CI_PULL_REQUEST//*pull\//}/merge"

# Cache key
var_3: &cache_key v1-{{ checksum "package-lock.json" }}

# Restores the cache that could be available for the current package.json
var_4: &restore_cache
  restore_cache:
    key: *cache_key

# Save cahce
var_5: &save_cache
  save_cache:
    key: *cache_key
    paths:
      - "node_modules"

# Attach to existing workspace
var_6: &attach_workspace
  attach_workspace:
    at: .

defaults: &job_defaults
  docker:
    - image: *docker_image

jobs:
  prepare:
    <<: *job_defaults
    steps:
      - *checkout_code
      - *restore_cache
      - run: npm install
      - *save_cache
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    <<: *job_defaults
    steps:
      - *checkout_code
      - *attach_workspace
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build
  test:
    <<: *job_defaults
    steps:
      - *checkout_code
      - *attach_workspace
      - run: npm run test
      - store_test_results:
          path: ./coverage
      - store_artifacts:
          path: ./coverage

  lint:
    <<: *job_defaults
    steps:
      - *checkout_code
      - *attach_workspace
      - run: npm run lint

  deploy-dev:
    <<: *job_defaults
    steps:
      - *checkout_code
      - *restore_cache
      - *attach_workspace
      - run: chmod 777 .circleci/write_aws_creds_file.sh && .circleci/write_aws_creds_file.sh
      - run: chmod 777 .circleci/amplify_init.sh && .circleci/amplify_init.sh
      - run: ./node_modules/.bin/amplify env checkout dev
      - run: ./node_modules/.bin/amplify publish -y --invalidateCloudFront

  deploy-prod:
    <<: *job_defaults
    steps:
      - *checkout_code
      - *restore_cache
      - *attach_workspace
      - run: chmod 777 .circleci/write_aws_creds_file.sh && .circleci/write_aws_creds_file.sh
      - run: chmod 777 .circleci/amplify_init.sh && .circleci/amplify_init.sh
      - run: ./node_modules/.bin/amplify env checkout prod
      - run: ./node_modules/.bin/amplify publish -y --invalidateCloudFront

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - prepare:
          filters:
            branches:
              ignore:
                - gh-pages
      - lint:
          requires:
            - prepare
      - build:
          requires:
            - lint
      - test:
          requires:
            - build
      - deploy-dev:
          requires:
            - test
      - deploy-prod:
          type: approval
          requires:
            - test
```

here is the scripts I'm using:

```
#!/bin/bash
set -e
IFS='|'

REACTCONFIG="{\
\"SourceDir\":\"src\",\
\"DistributionDir\":\"build\",\
\"BuildCommand\":\"npm run-script build\",\
\"StartCommand\":\"npm run-script start\"\
}"
AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":true,\
\"profileName\":\"asdf\",\
\"accessKeyId\":\"asdf\",\
\"secretAccessKey\":\"asdf\",\
\"region\":\"us-east-1\"\
}"
AMPLIFY="{\
\"projectName\":\"asdfi\",\
\"defaultEditor\":\"code\"\
}"
FRONTEND="{\
\"frontend\":\"javascript\",\
\"framework\":\"react\",\
\"config\":$REACTCONFIG\
}"
PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"

./node_modules/.bin/amplify configure project \
--amplify $AMPLIFY \
--frontend $FRONTEND \
--providers $PROVIDERS \
```

and

```
#!/bin/bash

 mkdir -p ~/.aws/

 cat <<EOF > ~/.aws/credentials
[amplify]
aws_access_key_id=asdf
aws_secret_access_key=asdf
EOF

 cat <<EOF > ~/.aws/config
[profile amplify]
region=us-east-1
EOF
```

and my versions are:

```
    "react-scripts": "^3.0.1",
    "@aws-amplify/cli": "^1.7.1",
    "aws-amplify": "^1.1.28",
```

**Comment by swaminator** [comment]
The Amplify Console has a script that simplifies the CI process using the Amplify CLI. Check this out: https://gist.github.com/swaminator/7408de774e24ecf031d0d9928f1fbae5

**Comment by amcdnl** [comment]
@swaminator - Can you share how that might look in the circle setup?

**Comment by DanNeish** [comment]
I'm using the following with CircleCI and it seems to be working well so far.

```
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

executors:
  node:
    docker:
      - image: circleci/node:12.4.0

jobs:
  build_and_test:
    executor: node
    steps:
      - run:
          name: 'Show node and NPM versions'
          command: |
            node -v
            npm -v
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: 'Run tests'
          command: |
            echo TESTS NOT IMPLEMENTED YET

  deploy:
    parameters:
      deploy_env:
        type: string
      chat_app_id:
        type: string
    executor: node
    steps:
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export REACT_APP_CHAT_APP_ID="<< parameters.chat_app_id >>"' >> $BASH_ENV
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - aws-cli/install
      - aws-cli/configure
      - run:
          name: 'Install aws-amplify CLI'
          command: |
            sudo npm install -g @aws-amplify/cli
      - run:
          name: 'Show AWS CLI and Amplify Versions'
          command: |
            aws --version
            amplify --version
      - run:
          name: 'Checkout Amplify << parameters.deploy_env >> Environment'
          command: |
            amplify env list
            amplify init --amplify "{\"envName\":\"<< parameters.deploy_env >>\"}" --providers "{\"awscloudformation\":{\"useProfile\":true,\"profileName\":\"default\"}}" --yes
      - run:
          name: 'Deploy to << parameters.deploy_env >>'
          command: |
            amplify publish --invalidateCloudFront --codegen "{\"generateCode\":false}" -- yes

workflows:
  Deploy:
    jobs:
      - build_and_test
      - deploy:
          name: DeployStaging
          deploy_env: staging
          chat_app_id: ${CHAT_APP_ID_STAGING}
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - master
      - request_production_deploy:
          type: approval
          requires:
            - DeployStaging
          filters:
            branches:
              only:
                - master
      - deploy:
          name: DeployProduction
          deploy_env: production
          chat_app_id: ${CHAT_APP_ID_PRODUCTION}
          requires:
            - request_production_deploy
          filters:
            branches:
              only:
                - master
```

**Comment by amcdnl** [comment]
I ended up punting on Amplify and just using S3 directly using Circle S3 Orbs.

```
version: 2.1

# Docker image to use for setup
var_1: &docker_image circleci/python:2.7-node

# Job step for checking out the source code from GitHub. This also ensures that the source code
# is rebased on top of master.
var_2: &checkout_code
  checkout:
    # After checkout, rebase on top of master. By default, PRs are not rebased on top of master,
    # See https://discuss.circleci.com/t/1662
    post: git pull --ff-only origin "refs/pull/${CI_PULL_REQUEST//*pull\//}/merge"

# Cache key
var_3: &cache_key v2-{{ checksum "package-lock.json" }}

# Restores the cache that could be available for the current package.json
var_4: &restore_cache
  restore_cache:
    key: *cache_key

# Save cahce
var_5: &save_cache
  save_cache:
    key: *cache_key
    paths:
      - "node_modules"

# Attach to existing workspace
var_6: &attach_workspace
  attach_workspace:
    at: .

defaults: &job_defaults
  docker:
    - image: *docker_image

orbs:
  aws-s3: circleci/aws-s3@1.0.11

jobs:
  prepare:
    <<: *job_defaults
    steps:
      - *checkout_code
      - *restore_cache
      - run: npm install
      - *save_cache
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  lint:
    <<: *job_defaults
    steps:
      - *checkout_code
      - *attach_workspace
      - run: npm run lint

  build:
    <<: *job_defaults
    steps:
      - *checkout_code
      - *attach_workspace
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy-dev:
    <<: *job_defaults
    steps:
      - *checkout_code
      - *attach_workspace
      - aws-s3/sync:
          from: build
          to: 's3://mybucket/'
          overwrite: true
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
          arguments: |
            --cache-control "max-age=86400"
```
