### ISSUE TITLE
missing field with generated code.

### ISSUE THREAD

**Issue by NuruddinBadawi** [aws-amplify/amplify-cli#1359]
** Which Category is your question related to? **
generated code

** What AWS Services are you utilizing? **
amplify

** Provide additional details e.g. code snippets **
I have this schema 

```
type Product @model {
  id: ID!
  name: String!
  description: String!
  image: S3Object!
  category: Category
  price: Float!
}
```

the generated query code
```
export const listProducts = `query ListProducts(
  $filter: ModelProductFilterInput
  $limit: Int
  $nextToken: String
) {
  listProducts(filter: $filter, limit: $limit, nextToken: $nextToken) {
    items {
      id
      name
      description
      category
      price
    }
    nextToken
  }
}
```

**There is no image field **

**Comment by yuth** [comment]
@NuruddinBadawi Could you answer the following questions
1.  Whats the version of Amplify CLI. You could get the version by running `amplify -v`
2. Can you share the contents of `<project-root>/.graphqlconfig.yml`  look like. Please make sure to obfuscate *API Key* and *endpoints*.

**Comment by NuruddinBadawi** [comment]
yeh sure

```
❯ amplify -v
1.6.5
```

.graphqlconfig.yml
```
projects:
  albaitotiapp:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: ___
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: eu-central-1
        maxDepth: 2
      endpoints:
        prod: >-
          https://___.appsync-api.eu-central-1.amazonaws.com/graphql

```
