### ISSUE TITLE
Can't get backend deployment work native amplify cli

### ISSUE THREAD

**Issue by OperationalFallacy** [aws-amplify/amplify-cli#13631]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

Deployments

### Is your feature request related to a problem? Please describe:

```
version: 1
applications:
  - appRoot: xxx-website
    backend:
      phases:
        install:
          commands:
            - pwd
            - cd ../xxx-api
            - node --version
            - nvm use 18.17.0 || true
            - node --version
            - yarn global add tsc-alias typescript tsc
        build:
          commands:
            - yum install jq -y
            - pwd
            - cd ../xxx-api
            - which envCache
            - envCache --get stackInfo
            - export STACKINFO="$(envCache --get stackInfo)"
            - echo $STACKINFO
            - env
            - if [ "${USER_BRANCH}" = "dev" ]; then envCache --set stackInfo "$(amplify env get --json --name dev)"; fi
            - if [ "${USER_BRANCH}" = "prod" ]; then envCache --set stackInfo "$(amplify env get --json --name prod)"; fi
            - yarn install --production
            - export aid=$(envCache --get stackInfo | jq '.AmplifyAppId')
            - amplify --version
            - amplify status -v
            - amplify pull --appId ${aid} --envName ${USER_BRANCH}
            - amplify env list
            # - cat $(which amplifyPush) || true
            - amplify function build -y
            - amplify status
            - amplify push
            # - amplify push -y
            # - amplifyPush --simple
            - echo 'Build and push completed...'
```

### Describe how you'd like this feature to work

I can't use amplifyPush --simple because it's not building and updating functions, probably because I've used some custom scripting. It works though in local dev environment.

And I can't get deployments with "amplify push" work in the cicd because it keeps failing with "Amplify backend project files detected within this folder" at amplify pull command... 

```
2024-02-28T21:48:58.930Z [INFO]: 🛑 No Amplify backend project files detected within this folder.
2024-02-28T21:48:58.930Z [INFO]: Resolution:
                                 Either initialize a new Amplify project or pull an existing project.
                                 - "amplify init" to initialize a new Amplify project
                                 - "amplify pull <app-id>" to pull your existing Amplify project. Find the <app-id> in the AWS Console or Amplify Studio.
                                 Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
```

I need help figuring out what's going on. given that amplify status works  - even though it says creating everything from scratch - why checking out env is such a pain?
