### ISSUE TITLE
Error: Can't resolve 'amplifyconfiguration.json' in build stage

### ISSUE THREAD

**Issue by marcusoyang** [aws-amplify/amplify-cli#13668]
### Amplify CLI Version

12.10.1

### Question

Hello,

I recently migrated my nextjs app from Amplify v5 to v6. Locally it builds fine but when building through Amplify, the json file isn't being generated.

`Type error: Cannot find module '../components/amplifyconfiguration.json' or its corresponding type declarations.`

```
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - yarn global add @aws-amplify/cli
        - amplifyPush --simple
``` 

![image](https://github.com/aws-amplify/amplify-cli/assets/87522892/1c638da3-0957-46d0-afe5-7218465ebd6c)
