### ISSUE TITLE
amplify pull (headless)  fail to pull configuration when used with github actions on ubuntu

### ISSUE THREAD

**Issue by dkliss** [aws-amplify/amplify-cli#13661]
### How did you install the Amplify CLI?

npm

### Amplify CLI Version

12.10.1

### What operating system are you using?

ubuntu

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Hi,

I have a github action wokrflow as shown below. When I run this in github actions, the AWS credentials are processed correctly and I can see that by checking of aws s3 ls shows me all s3 files. However, after that when i like to pull my aws amplify configuration via "aws amplify pull" but the github action workflow is stuck at "Opening link: https://us-east-1.admin.amplifyapp.com/admin/[redacted]/dev/verify/?loginVersion=1". When I open the link, it ask me to copy a key back. 
I expected all this to work programatically without my intervention. Is there anything missing here from my side? I am using github Provider (token.actions.githubusercontent.com), which is setup along with required IAM role and aws integration is working.

Also I see no logs for amplify pull. I expected the amplify pull to retrieve my configured envoirnment.

```
jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Flutter        
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter --version      
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Install Amplify CLI
        run: |
          npm install -g @aws-amplify/cli
      - run: amplify --version
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: ${{ env.AWS_AUDIENCE }}
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActionsSession
      - name: Check if AWS can access s3 buckets
        run: aws s3 ls
      - name: Pull latest changes from Amplify backend
        run: amplify pull --appId ${{ env.AWS_APPID }} --envName ${{ env.AWS_ENV }}  --verbose --yes
```

### Describe the bug

amplify pull does not work in github action. It is stuck at opening link as example below 

```
19m 7s
Run amplify pull --appId [redacted]-envName dev  --verbose --yes
  amplify pull --appId [redacted] --envName dev  --verbose --yes
  shell: /usr/bin/bash -e {0}
  
Opening link: https://github.com[redacted]/actions/runs/[redacted]/job/[redacted]#step:10:7/dev/verify/?loginVersion=1
```

### Expected behavior

amplify pull shall retrieve latest configuration from aws amplify.

### Reproduction steps

1. Setup AWS amplify from local PC with authentication etc.
2. Push the changes to aws server.
3. Setup github action as Identity provider in AWS. 
4. Now setup a github action workflow as per workflow i provided above.
5. Pull the aws amplify configuration via github actions which was pushed from local PC.
6. ISSUE: Pull is stuck for long time at "opening link". 

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.
