### ISSUE TITLE
Install Amplify CLI on Windows Github Actions Fails: The term 'install.cmd' is not recognized as a name of a cmdlet

### ISSUE THREAD

**Issue by dkliss** [aws-amplify/amplify-cli#13664]
### How did you install the Amplify CLI?

curl -sL https://aws-amplify.github.io/amplify-cli/install-win -o install.cmd && install.cmd

### Amplify CLI Version

12.10.1

### What operating system are you using?

runs-on: windows-latest

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

"No manual changes made"

### Describe the bug

I run below workflow but the curl command fails with error. Is there something else to be done aport from running curl for windows?

`"The term 'install.cmd' is not recognized as a name of a cmdlet, function, script file, or executable program.     | Check the 
 spelling of the name, or if a path was included, verify that the path is correct and try again."
`
  ```
build_windows:
    name: Build Flutter (windows)
    needs: [flutter_test]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Install AWS CLI
        run: |
          curl -sL https://aws-amplify.github.io/amplify-cli/install-win -o install.cmd && install.cmd
      - name: Install Amplify CLI
        run: |
          npm install -g @aws-amplify/cli --unsafe-perm=true
      - run: amplify --version
```

### Expected behavior

I expect below to work for Windows host in GitHib Actions.

`curl -sL https://aws-amplify.github.io/amplify-cli/install-win -o install.cmd && install.cmd`

### Reproduction steps

Run above workflow with curl.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.
