### ISSUE TITLE
Duplicated files generated every time running amplify pull/push

### ISSUE THREAD

**Issue by Dickensli** [aws-amplify/amplify-cli#13843]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v22.4.0

### Amplify CLI Version

12.12.4

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

Every time I run `amplify pull` or `amplify push`, duplicate files are generated under the `#current-cloud-backend` directory. For example, my backend folder structure looks like this:

backend
|── api
|── awscloudformation/build
│   └── root-cloudformation-stack.json
|──auth
│   └── build
|── function
|── amplify-meta.json
|── backend-config.json
|── tags.json

However, the #current-cloud-backend directory ends up with:

#current-cloud-backend
|── api
|── api 2
|──awscloudformation/build
|   └── root-cloudformation-stack.json
|   └── root-cloudformation-stack 2.json
|── auth
│   └── build
│   └── build 2
|── auth 4
|── function
|── amplify-meta.json
|── amplify-meta 2.json
|── backend-config.json
|── backend-config 2.json
|── tags.json
└── tags 2.json

These number-appended folders are usually empty or outdated and vary with each run, e.g. I updated my api's `defaultauthentication` from `API_KEY` to `AMAZON_COGNITO_USER_POOLS` using `amplify update api` in local; then I ran `amplify push`, and two `amplify-meta.json`s were generated. `amplify-meta.json` catch the change but `amplify-meta 2.json` does not.

Sometimes, it gets worse, and the `api/` folder disappears. When I check Amplify Backend Studio, I see errors like "can't retrieve data since schema is missing." While I can fix this by running `amplify push --force`, the issue of duplicated files still persists.

One possible cause is:
I have turned on CI/CD linked to github repo, usually when I have some backend change, I run `amplify push`, waiting for push to succeed, and then run `git add`, `git commit`, `git push` which triggers CI/CD runs. Could this introduce any conflict between manual amplify push vs. CI/CD push?

my `amplify.yml`
```
version: 1
appRoot: ./career-copilot-app/
backend:
  phases:
    build:
      Commands:
        - sudo pip3 install pipenv
        - sudo pip3 install venv
        - amplifyPush --simple
  artifacts:
    baseDirectory: amplify/backend
    files:
      - '**/*'
  cache:
    paths:
      - 'amplify/**/node_modules/**/*'
      - 'amplify/.serverless/**/*'
      - 'amplify/backend/**/build/**/*'
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
        - npm audit fix
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist/career-copilot-app/browser
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Expected behavior

no duplicated files/folders should be generated

### Reproduction steps

1. make some local changes in api schema or lambda function src
2. amplify push (duplicated files appear)
3. manually delete all duplicated files under #current-cloud-backend
4. waiting for push to succeed
5. git add
6. git commit
7. git push
8. waiting for CI/CD to finish
9. amplify pull
10. another a few duplicated files appear

### Project Identifier

083a411c049aa404823988034e0b09f6

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.
