### ISSUE TITLE
How can I publish from CI

### ISSUE THREAD

**Issue by bokuweb** [aws-amplify/amplify-cli#1430]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **

amplify-cli

** What AWS Services are you utilizing? **

amplify/appSync/dynamodb/S3/cognito

** Provide additional details e.g. code snippets **

I try to `publish` my amplify project with circle CI.
However It does not succeed with following command

- command
```
              amplify env list    
              amplify init --amplify "{\"envName\":\"staging\"}" --yes
              amplify publish --invalidateCloudFront -- yes
```

- output
```
| Environments |
| ------------ |
| dev      |
| staging      |

Note: It is recommended to run this command from the root of your app directory
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

- Initializing your environment: staging
✔ Initialized provider successfully.
Could not read cloudformation template at path: /root/app/amplify/backend/api/app/build/cloudformation-template.json
✖ An error occurred when pushing the resources to the cloud
✖ There was an error initializing your environment.
init failed
{ Error: ENOENT: no such file or directory, open '/root/app/amplify/backend/api/app/build/parameters.json'
    at Object.openSync (fs.js:439:3)
    at Object.writeFileSync (fs.js:1190:35)
    at writeUpdatedParametersJson (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/upload-appsync-files.js:85:8)
    at uploadAppSyncFiles (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/upload-appsync-files.js:126:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path:
   '/root/app/amplify/backend/api/app/build/parameters.json' }
Exited with code 1
```

But it succeed in my local machine with following command.

```
git clone my-app
cd my-app
amplify env list    
amplify init --amplify "{\"envName\":\"staging\"}" --yes
amplify publish --invalidateCloudFront -- yes
```

## Added

However sometimes it succeed with above script in CI 🤔 It's weird...
Do not wait for the file to be generated?

**Comment by UnleashedMind** [comment]
Hi @bokuweb 
What's the version of the Amplify CLI you are using? this looks very similar to this issue: 
https://github.com/aws-amplify/amplify-cli/issues/1342
Which was fixed and merged by this PR: 
https://github.com/aws-amplify/amplify-cli/pull/1383
and published.

**Comment by bokuweb** [comment]
@UnleashedMind Oops, I use v1.6.8

**Comment by kaustavghosh06** [comment]
@bokuweb We identified the issue and we will submit a fix for it.

**Comment by bokuweb** [comment]
Thanks for your work :)

**Comment by ronaldwidha** [comment]
Thanks @mikeparisstuff. I am hitting the same problem too. What's the best way to go about getting aws-amplify/cli build that has latest fixes?

**Comment by bokuweb** [comment]
This issue is resolved with v1.6.9 🎉

**Comment by scherroman** [comment]
After much trial and error, I was finally able to get amplify init and publish to work in Github Actions. The method that worked for me as described in [#2072](https://github.com/aws-amplify/amplify-cli/issues/2072) was running the aws cli configure commands to configure the default profile and then using the default profile during amplify init:

```
name: Continuous Deployment
on: 
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      
      - name: Install dependencies
        run: |
          npm install @aws-amplify/cli -g
          npm ci
      
      - name: Verify packages
        run: npm run verify-packages
      
      - name: Run linter
        run: npm run lint
      
      - name: Run tests
        run: npm run test
      
      - name: Build project
        run: npm run build-prod
        
      - name: Configure amplify
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
          aws configure set default.region us-east-1
          amplify init --amplify "{\"envName\":\"prod\"}" --providers "{\"awscloudformation\": {\"useProfile\":true, \"profileName\":\"default\"}}" --yes
          amplify status

      - name: Deploy to production
        run: amplify publish --invalidateCloudFront --yes
        

```

Note that the ubuntu-latest image comes pre-installed with AWS CLI. I also build my project beforehand separately, with my amplify build command set to `echo 🚀 Publishing...`
