### ISSUE TITLE
Simplify Default Configurations

### ISSUE THREAD

**Issue by amcdnl** [aws-amplify/amplify-cli#1730]
## Problem Statement
Oftentimes teams have default configurations for regions, buckets, etc. Currently if you want to initialize these you have to write a script and then have your team run that.

## Proposal
Provide a configuration file similar to the `amplify.yml` file that allows users to set defaults that you might otherwise configure via the script suggestions.

This could also help facilitate easier CI setups mentioned in https://github.com/aws-amplify/amplify-cli/issues/1322

**Comment by attilah** [comment]
@amcdnl to help the team to discuss it in more depth, could you please elaborate on the details of this request and provide more information on:
- what options would you require to be supported as default config?
- where that config would be stored? source control is fine or it contains secrets which would make it unsuitable to be stored there?
- what is missing from the existing headless support, that would help your scenario?

Provide a sample config what you'd find satisfying your needs.

**Comment by amcdnl** [comment]
Sure!

In the Amplify docs section under Environments and Teams (https://aws-amplify.github.io/docs/cli/multienv?sdk=js) there is a section about CI and it says:

> ideally a CI tool should be used to automate this process - amplify CLI now provides headless support for its init/push commands  Check out https://github.com/aws-amplify/amplify-cli/tree/multienv/packages/amplify-cli/sample-headless-scripts for examples)

When you follow that link and start digging in you find scripts that define all these different configuration options. If we look at the `headeless_init_env.sh` script there is a block of code that defines 'project' based settings like:

```
AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":true,\
\"profileName\":\"default\"\
}"
```

and even more specific things like:

```
NOTIFICATIONSCONFIG="{\
\"Pinpoint\":{
\"SMS\":{
\"Enabled\":true\
},\
```

That are the same across all devs working on the project. I would expect the tooling to provide me a convenient way to define these in a JSON/YML file rather than scripting this out w/ bash scripts. 

I don't see this config any different than what you would find in a CI config file like circle where defaults are provided but users can provide environment variable overrides.

If we were to model it after something like CircleCI, it might look something like:

```yml
version: 0.1

config:
    configLevel: project
    useProfile: true
    # could override based on .env local files/etc
    profileName: default

providers:
  awscloudformation:
    # could make configurable based on ENV variables from CI/etc
    region: us-east-1 
    deploymentBucketName: foo.baz

categories:
  notifications:
    pinpoint:
      sms:
        enabled: true
    email:
      enabled: true
      fromAddress: zzz@amazon.com
  auth:
    facebookAppId: f13bbd
```

Try not to focus on the exact details I put in that example but just wanted to give you an idea. Basically I'd like anything that I'd want to script out in those scripts or type in manually that isn't something like 'what code editor' could be setup in a config file like that and then override based on .env or environment variables from CI.
