### ISSUE TITLE
generatedFileName API.service.ts too large

### ISSUE THREAD

**Issue by malcomm** [aws-amplify/amplify-cli#1735]
**Is your feature request related to a problem? Please describe.**

Generated API Service file is too large. This causes two major problems:

1. compiles can fail with:
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```
Sure there are workarounds for this but ...

2. Large file has trouble loading in an IDE/editor, either very slow or could possibly cause an IDE crash 

**Describe the solution you'd like**

Split the file up into clear parts/sections that get imported into the single file.

**Describe alternatives you've considered**

```
NODE_OPTIONS=--max-old-space-size=4096
```

Other than that ... not sure ... at the moment, I'm just working around this and dealing with it.

**Additional context**

Generated file:
- **name:** src/app/API.service.ts
- **size:** 13MB
- **lines:** 416,656

Pretty sure the main reason my generated API.service.ts is so large, is the my `maxDepth: 7`, but I suspect this is a fairly common config setting for folks. 

- **file:** .graphqlconfig.yml

```
projects:
  avdrapi:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/API.service.ts
        docsFilePath: src/graphql
        maxDepth: 7
```
