### ISSUE TITLE
'amplify status' shows "Update" for Auth Category even though it has been pushed

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#199]
**Describe the bug**
I already pushed all my local backend changes and things seem to be in sync. Shouldn't then "Operation" be "No Change" under Auth?

**Context**
I have been modifying the yaml cloudformation for the auth category manually to add things that the amplify interactive questionnaire does not support. So maybe that is the reason amplify's "operation" status seems out of sync now. 

**Expected behavior**
"No Change" should appear under Auth after a successful 'amplify push'

**Console Log**

```
$ amplify push
| Category | Resource name         | Operation | Provider plugin   |
| -------- | --------------------- | --------- | ----------------- |
| Auth     | dryeyefrontendcognito | Update    | awscloudformation |
| Hosting  | S3AndCloudFront       | No Change | awscloudformation |
? Are you sure you want to continue? true
⠦ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE_CLEANUP_IN_PROGRESS dryeyefrontend-20180923114013 AWS::CloudFormation::Stack Sun Sep 23 2018 21:13:29 GMT-0600 (Mountain Daylight Time)               
UPDATE_IN_PROGRESS                  dryeyefrontend-20180923114013 AWS::CloudFormation::Stack Sun Sep 23 2018 21:13:21 GMT-0600 (Mountain Daylight Time) User Initiated
UPDATE_IN_PROGRESS                  authdryeyefrontendcognito     AWS::CloudFormation::Stack Sun Sep 23 2018 21:13:25 GMT-0600 (Mountain Daylight Time)               
UPDATE_IN_PROGRESS                  hostingS3AndCloudFront        AWS::CloudFormation::Stack Sun Sep 23 2018 21:13:25 GMT-0600 (Mountain Daylight Time)               
UPDATE_COMPLETE                     hostingS3AndCloudFront        AWS::CloudFormation::Stack Sun Sep 23 2018 21:13:26 GMT-0600 (Mountain Daylight Time)               
UPDATE_COMPLETE                     authdryeyefrontendcognito     AWS::CloudFormation::Stack Sun Sep 23 2018 21:13:26 GMT-0600 (Mountain Daylight Time)               
UPDATE_IN_PROGRESS                  authdryeyefrontendcognito     AWS::CloudFormation::Stack Sun Sep 23 2018 21:13:30 GMT-0600 (Mountain Daylight Time)               
UPDATE_IN_PROGRESS                  hostingS3AndCloudFront        AWS::CloudFormation::Stack Sun Sep 23 2018 21:13:30 GMT-0600 (Mountain Daylight Time)               
UPDATE_COMPLETE                     authdryeyefrontendcognito     AWS::CloudFormation::Stack Sun Sep 23 2018 21:13:31 GMT-0600 (Mountain Daylight Time)               
UPDATE_COMPLETE                     hostingS3AndCloudFront        AWS::CloudFormation::Stack Sun Sep 23 2018 21:13:31 GMT-0600 (Mountain Daylight Time)               
UPDATE_COMPLETE                     dryeyefrontend-20180923114013 AWS::CloudFormation::Stack Sun Sep 23 2018 21:13:31 GMT-0600 (Mountain Daylight Time)               
✔ All resources are updated in the cloud


hisham@mb2:~/src/dry-eye-frontend$ amplify --version
0.1.23
hisham@mb2:~/src/dry-eye-frontend$ amplify status
| Category | Resource name         | Operation | Provider plugin   |
| -------- | --------------------- | --------- | ----------------- |
| Auth     | dryeyefrontendcognito | Update    | awscloudformation |
| Hosting  | S3AndCloudFront       | No Change | awscloudformation |

Hosting endpoint: <removed>
```

**Desktop (please complete the following information):**
 - OS: OSX

**Comment by UnleashedMind** [comment]
What have you manually edited on the Cloudformation template? Just so we can reproduce the issue.

**Comment by hisham** [comment]
I added the following I believe: 

1. 3 custom attributes to the UserPool schema like this:


```
      Schema:

        -
          Name: email
          Required: true
          Mutable: true
        - Name: practitioner_id
          AttributeDataType: String
          Mutable: true
          StringAttributeConstraints:
              MinLength: 1
              MaxLength: 1024
        - Name: signup_secret
          AttributeDataType: String
          Mutable: false
          StringAttributeConstraints:
              MinLength: 1
              MaxLength: 128
        - Name: origin
          AttributeDataType: String
          Mutable: true
          StringAttributeConstraints:
              MinLength: 1
              MaxLength: 1024
```

2. Added UsernameAtrributes of email to UserPool I believe so user can sign-in via email address rather than username: 

```
UsernameAttributes:
        - 'email'
```

3. Option to remember device for cognito: 

```
     DeviceConfiguration:
          DeviceOnlyRememberedOnUserPrompt: true
```

4. Lambda triggers for cognito UserPool: 

```
     LambdaConfig:
          PreSignUp: 'arn:aws:lambda:us-east-1:541223640481:function:<removed>'
          CustomMessage: 'arn:aws:lambda:us-east-1:541223640481:function:<removed>'
          DefineAuthChallenge: 'arn:aws:lambda:us-east-1:541223640481:function:<removed>'
          CreateAuthChallenge: 'arn:aws:lambda:us-east-1:541223640481:function:<removed>'
          VerifyAuthChallengeResponse: 'arn:aws:lambda:us-east-1:541223640481:function:<removed>'
```
5. Five Lamdba::Permissions so that Cognito can call the lambda triggers, like this: 

```
  CognitoPreSignupLambdaInvocationPermission:
      Type: AWS::Lambda::Permission
      Properties:
          Action: lambda:InvokeFunction
          FunctionName: 'arn:aws:lambda:us-east-1:541223640481:function:<removed>'
          Principal: cognito-idp.amazonaws.com
          SourceArn: !GetAtt UserPool.Arn
      DependsOn: UserPool
```
