### ISSUE TITLE
Ability to generate different filename.swift files from directories of .graphql files

### ISSUE THREAD

**Issue by jasonbobier** [aws-amplify/amplify-cli#2123]
**Is your feature request related to a problem? Please describe.**

Yes, https://github.com/aws-amplify/amplify-cli/issues/2122

**Describe the solution you'd like**
amplify codegen --max-depth --input=MySubAPIDirectory --output=MySubAPIDirectory.swift

would produce an api using just the .graphql files in MySubAPIDirectory and save it as MySubAPIDirectory.swift

Basically, I don't want to create the massive namespace polluting API.swift that has everything in it. I want nice clean sub apis with just the queries, mutations, and subscriptions that I use in my app.

**Describe alternatives you've considered**
See the bug report for how I'm doing it now. It produces an error and is a hack.

**Comment by kaustavghosh06** [comment]
@jasonbobier You can store these input and output parameters (also specifiy a pattern) in the `.graphqlConfig.yml` generated at the root of your project.

Out here, are you just requesting for a headless option for the same?

**Comment by jasonbobier** [comment]
Is there some documentation on this somewhere? I see:

generatedFileName: API.swift

but that produces one swift file from all of the graphql files.

**Comment by rodrigoelp** [comment]
Hi @jasonbobier, this answer might be a tad late as I notice you asked more than a two months ago.

I have played with the `.graphconfig.yml` file and I can confirm `codegen` will pick up whatever name you provide it and use it flawlessly. In my case I have all the amplify stuff located in a specific folder of my project as:

```
./src/ ~> all ios source code.
./aws/
./aws/.graphconfig.yml
./aws/schema.json
./aws/graphql
```
My yaml file looks like this:
```yml
projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: ../src/SampleApp/SampleApp/Aws.Api.swift
        docsFilePath: graphql
        region: us-east-1
        apiId: null
        frontend: ios
        maxDepth: 5
extensions:
  amplify:
    version: 3
```

Calling `amplify codegen` creates correctly my source code and locates it in a place that is way less messy than the actual documentation gives you.
