### ISSUE TITLE
Cannot change the depth of the returned queries data

### ISSUE THREAD

**Issue by CaptainChemist** [aws-amplify/amplify-cli#2234]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

This could definitely be a user error but I can't get the gql generation to go more than 2 levels even when I change the max depth.

**To Reproduce**

1. Run `amplify codegen configure` and specify the max statement depth as 3. (typescript language, default everything else)
2. Confirm in the .graphqlconfig.yml that the `extensions` section looks like this with the new `maxDepth` parameter.
````
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        maxDepth: 3
````

3. Run `amplify api gql-compile` and `amplify codgen` 
4. I would expect now that my queries and mutations typescript files would first of all be changed from what they were before, in particular having a deeper statement depth, but the files remain unchanged. Even if I delete the files and run the generation again, I don't see that they are any different.

**Expected behavior**
I expect that after changing the max statement depth that the autogenerated queries and mutations will have a deeper nesting. I am working with this relationship:

enrolledUserCourses -> courses -> lectures

When I query the enrolledUserCourses, I don't even see the lecture field even though when I do a courses query instead it shows up just fine.
