### ISSUE TITLE
CLI no longer appears to generate API.ts after schema change

### ISSUE THREAD

**Issue by mwarger** [aws-amplify/amplify-cli#2259]
**Describe the bug**
The amplify cli no longer appears to generate an updated API.ts after a schema change. I first noticed this while running `mock` and not seeing my expected types reflected.  This appears to be independent of `mock` though, since just running `amplify codegen` or `amplify codegen types` does not resolve it.

**To Reproduce**
1. I used the generated three model example with blog, post, comment
2. Run `codegen` using typescript and default configuration
3. Queries, mutations, and everything else generates, but API.ts does not update
4. Deleting API.ts and running again, does not generate a file (unless you count https://github.com/aws-amplify/amplify-cli/issues/2002 - which is blank)

**Expected behavior**
API.ts should be there - this appears to be a regression in the tool 

Please prioritize this, if possible - this really hinders progress.  Thank you.  

amplify -v
3.2.0

**Comment by kaustavghosh06** [comment]
We released a new version of the CLI - v3.8.0 with a fix for this.

**Comment by nagey** [comment]
seeing something similar in v4.13.4.

Here's my `.graphqlconfig.yml` for reference:
```
projects:
  myproject:
    schemaPath: products/web/src/graphql/schema.json
    includes:
      - products/web/src/graphql/**/*.js
    excludes:
      - amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: products/web/src/API.ts
        docsFilePath: products/web/src/graphql
        graphQLApiId: rzktsf3bznh5xpe362x7xoxbeu
extensions:
  amplify:
    version: 3
```
