### ISSUE TITLE
Codegen fails for older codegen yaml files

### ISSUE THREAD

**Issue by attilah** [aws-amplify/amplify-cli#2262]
**Describe the bug**

Older versions of CLI si creating a yaml files where ```includes``` and ```excludes``` can be non-arrays, which is not handled by the latest code.

```yaml
projects:
  xyz:
    schemaPath: src/graphql/schema.json
    includes: src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
```

**To Reproduce**
Project created with 1.7.5, then pushed with latest would reproduce it.
