### ISSUE TITLE
Cannot give postConfirmation trigger access to auth

### ISSUE THREAD

**Issue by Jkap7788** [aws-amplify/amplify-cli#2303]
**Describe the bug**
I have created a post confirmation trigger using `amplify update auth`.

I would like to give the postConfirmation trigger access to the user pool in order to get user information and perform other operations that affect the user pool.

I then used `amplify update function` in order to give the post confirmation function access to the user pool.

However, an error occurs saying: "Error: Cannot add [functionName] due to a cyclic dependency" where [functionName] is the name of my function.

The postConfirmation cloudformation template file is updated with the appropriate permissions but the user pool id is not passed down as a parameter from nested-cloudformation-stack.yml

**Desktop (please complete the following information):**
 - OS: windows 10

**Additional context**
Invoking `amplify update auth` and then adding add-to-group functionality works fine but invoking `amplify update function` and then giving permissions to auth throws the error stated above.

I have tried this with @aws-amplify/cli 3.0.0 and 3.2.0, both result in the same error.

Thanks a lot!

**Comment by attilah** [comment]
@Jkap7788 it is a cyclic dependency as the CLI says. I'm not sure that we've a CLI supported way for this scenario, because the possibility that comes to my mind is adding a custom policy resource which depend on both resources, your user pool and the function, but the CustomResources are getting deployed within the GraphQL API scope.

**Comment by thedgbrt** [comment]
it seems related to #1874 and #2076 

@attilah , do you have any idea how it can be setup manually, by editing the CloudFormation template files for example?

**Comment by Jkap7788** [comment]
@attilah Thanks for the reply!

I'm currently using a manual workaround for this.

Using `amplify update function` to add auth permissions to cognito triggers will result in a cyclic dependency error message.
However, the correct IAM policy is added to the function's cloud formation template.
The cognito user pool id is NOT passed down as a parameter so to fix this, I manually modify the IAM policy to include the user pool id in the iam resource arn

@thedgbrt  A quick and easy fix is just to manually add the user pool id into the iam policy. Not ideal but gets you unstuck quickly.

@attilah Out of curiosity, how come adding add-to-group functionality to a post confirmation trigger does not register as a cyclic dependency where as adding auth permissions via `amplify update function` does cause a cyclic dependency?

**Comment by davekiss** [comment]
@attilah I'm also running into a similar issue and would benefit from seeing an example of the setup for a custom policy you're referencing

**Comment by davidsteed** [comment]
Same problem - permission appear to be fine bu the environment variable is not set properly.  What do I edit to set the environment variable to the correct userpool

**Comment by WhiteAbeLincoln** [comment]
I had the same issue. I ended up editing the auth's cloudformation template, rather than the function's.

Look for the comment `# Updating lambda role with permissions to Cognito`. There will be a policy document section with permissions granted for group creation and adding users to groups. Add the additional policies that you want to the list.

```yaml
  myAuthPostConfirmationAddToGroupCognito:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: myAuthPostConfirmationAddToGroupCognito
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
            
              - cognito-idp:AdminAddUserToGroup
            
              - cognito-idp:GetGroup
            
              - cognito-idp:CreateGroup

             # Add your other permissions here
            
            
            
            Resource: !GetAtt
            
              - UserPool
            
              - Arn
            
            
            

      Roles:
        - !Join ['',["myAuthPostConfirmation", '-', !Ref env]]
  
```

Ideally the cli would allow us to select which permissions to grant when setting up a trigger instead of assuming these defaults
