### ISSUE TITLE
Autogenerated graphql files are not importable in typescript

### ISSUE THREAD

**Issue by meketadev** [aws-amplify/amplify-cli#2496]
**Describe the bug**
The generated graphql mutations, queries, and subscriptions are not importable.  

**To Reproduce**
1. Create project `ng init` todo.
2. cd into project and add amplify `amplify init` using the angular options
3. Add the api, and use any schema, the "todo" default schema is fine.
4. amplify push the changes so the graphql files are generated
5. In a component try to import a query, mutation or schema from the graphql folder, not the API.service.ts file.

**Expected behavior**
I would expect to be able to use the generated files to import the query statements.  This would be useful for the appsync client query option.

**Screenshots**
![image](https://user-images.githubusercontent.com/41303621/66171207-311cc880-e5fc-11e9-9e09-84836967b4ae.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10

**Smartphone (please complete the following information):**
amplify version 3.10.0
typescript 3.5.3
angular/cli 8.3.8

**Additional context**

**Comment by SwaySway** [comment]
@meketadev Could you share your `.graphqlconfig.yml`? It is located in the root of your project.
Based on your screenshot it looks like your graphql operations are in a graphql format.

**Comment by meketadev** [comment]
Here is the .graphqlconfig.yml file:
```
projects:
  pacingplan:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/API.service.ts
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
```
