### ISSUE TITLE
What's the proper workflow for adding lambda trigger to Auth?

### ISSUE THREAD

**Issue by jaxondu** [aws-amplify/amplify-cli#258]
I need to add a post confirmation lambda trigger to Cognito User Pool. "amplify auth add" does not support adding one. So whats the recommended workflow to add one?  Manually edit the CloudFormation script generated by  "amplify auth add". Then "amplify push". But then my changes will be removed when I next run  "amplify auth update". Or add in the lambda trigger at Cognito User Pool console. Will my changes on the console be erased when I next run "amplify auth update" and "amplify push"?

**Comment by haverchuck** [comment]
@jaxondu Amplify CLI does not currently support trigger configuration, so yes - at this time you would run the risk of overwriting configured triggers upon an `auth update`.  I am marking this issue as a feature request, so that we can take a look at adding trigger support.

**Comment by jaxondu** [comment]
@haverchuck there is another issue at #102 cli auth not able to cater to flow of using email or phone login. This is a stopper as we need this in order to adopt amplify cli, as there is no way to make auth setting changes outside cli.

**Comment by ju-Skinner** [comment]
@jaxondu you can add the settings below into the cloudformation template, under the UserPool section. I did this which allows a user to signup via `username` or `verified email address`. If you want both `email` and `phone` along with `username` you can just add another value `phone_number`. Here is a link to reference [AliasAttributes](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UserPoolType.html)

```
AliasAttributes: 
  - "email"
```

**Comment by troygoode** [comment]
For future reference, if you want to set up your Pool to only use email _instead_ of usernames, modify your CloudFormation template (`amplify/backend/auth/?/?-cloudformation-template.yml`) to include `UsernameAttributes: - "email"`. Example:

```yaml
# BEGIN USER POOL RESOURCES
UserPool:
# Created upon user selection
# Depends on SNS Role for Arn if MFA is enabled
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: !If [ShouldNotCreateEnvResources, !Ref userPoolName, !Join ['',[!Ref userPoolName, '-', !Ref env]]]
    UsernameAttributes:
      - "email"
```

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html
