### ISSUE TITLE
Nested Stack TemplateURL S3 Endpoint - Invalid S3 Addresses

### ISSUE THREAD

**Issue by rrrix** [aws-amplify/amplify-cli#2732]
**Describe the bug**
Amplify CloudFormation Provider generates nested CloudFormation template resources with an invalid "TemplateURL" S3 Address value for S3 Buckets in non-US Standard (non us-east-1) regions. 

**Amplify CLI Version**
3.17.0

**To Reproduce**
Note: Reproducing this within the Amplify CLI  is sometimes inconsistent for some reason. A Sample CloudFormation stack demonstrating the problem is attached at the bottom. For some reason CloudFormation behaves differently on Root Stack Creation versus Root Stack Updates with new Nested Stacks. 

1. Create an Amplify project in a region other than `us-east-1`
1. Add any given resource (e.g. `amplify add api`)
1. Run `amplify push` 
1. Modify the resource created in step #2, e.g. add a new GraphQL Type with `@model`
1. Run `amplify push` again
1. Error received: 
> S3 error: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

**Expected behavior**
Updates that include New Resources with New Nested Stacks are created successfully.

The `TemplateURL` value should contain valid S3 Addresses appropriate for the region that the deployment bucket resides in, according to [AWS Service Endpoints - Amazon Simple Storage Service (Amazon S3)](https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region)

For buckets located in us-east-1, the current TemplateURL value generated is acceptable:
`https://s3.amazonaws.com/<S3DeploymentBucket>/<S3DeploymentRootKey>/stacks/<stack-name>.json`

For buckets located in other regions, the TemplateURL value must reflect the appropriate endpoint, for example us-west-2:

Preferred, virtualhost style addressing: 

`https://<S3DeploymentBucket>.s3.amazonaws.com/<S3DeploymentRootKey>/stacks/<stack-name>.json`

--OR--

Path-Style with Regional Endpoint: 

`https://s3.us-west-2.amazonaws.com/<S3DeploymentBucket>/<S3DeploymentRootKey>/stacks/<stack-name>.json`

**Screenshots**
<img width="1302" alt="Screen Shot 2019-11-13 at 3 26 10 PM" src="https://user-images.githubusercontent.com/3194704/68813219-06c22000-062a-11ea-9ac0-1ca8761eed5e.png">

**Desktop (please complete the following information):**
 - OS: `MacOS`
 - Node Version. `v12.13.0`

**Additional context**
Additional information is available in the [S3 Developer Guide, Virtual Hosting of Buckets](https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html)

Also the "Important Note" in this blog post: [Amazon S3 Path Deprecation Plan – The Rest of the Story](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/)

Unfortunately the behavior varies depending on:
* The region being used (us-east-1 or not)
* The date the bucket is created 
* The S3 API being used (REST API version 2 / version 4 vs S3API. CloudFormation uses REST v4. 
* The "addressing style" being used - "path style" vs. "virtualhost-style".

So far I've found two places where the **TemplateURL** field is generated in the Amplify CLI:

https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-transformer-core/src/util/splitStack.ts#L308
https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-transformer-core/src/util/amplifyUtils.ts#L271

For testing and demonstration, Here's an example Root CloudFormation Stack, with a Nested Stack, in a bucket in us-west-2 with the invalid addressing style:
https://amplify-s3-templateurl-example-us-west-2.s3-us-west-2.amazonaws.com/root-example-error.yaml

```
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  nestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/amplify-s3-templateurl-example-us-west-2/S3_Bucket.yaml
```

And a Root Stack with the valid (virtualhost) addressing style:
https://amplify-s3-templateurl-example-us-west-2.s3-us-west-2.amazonaws.com/root-example-valid.yaml

```
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  nestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://amplify-s3-templateurl-example-us-west-2.s3.amazonaws.com/S3_Bucket.yaml
```

Both reference the same nested stack, which simply attempts to create a basic empty S3 Bucket:
https://amplify-s3-templateurl-example-us-west-2.s3-us-west-2.amazonaws.com/S3_Bucket.yaml

```
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  NestedS3Bucket:
    Type: AWS::S3::Bucket
```
