### ISSUE TITLE
Graphql Connection Not Creating Connections

### ISSUE THREAD

**Issue by tfendt** [aws-amplify/amplify-cli#2734]
**Which Category is your question related to?**
Graphql

**Amplify CLI Version** 
3.17.0

**What AWS Services are you utilizing?**
DynamoDB, Cognito

**Provide additional details e.g. code snippets**
I have the following schema:
```
type Tenant @model @auth(rules: [{allow: owner}, { allow: groups, groups: ["Admin"]}]) {
  id: ID!
  name: String!
  email: String!
  stores: [Store!]! @connection(name: "TenantStores")
  users: [User]! @connection(name: "TenantUsers")
}

type User @model @auth(rules: [{allow: owner}]) {
  id: ID!
  name: String!
  email: String!
  tenant: Tenant! @connection(name: "TenantUsers")
}

type Store @model @auth(rules: [{allow: owner}]){
  id: ID!
  tenant: Tenant! @connection(name: "TenantStores")
  name: String!
}
```
When I create a Store or User and then query Tenant it doesn't return any stores or users. I have read through all the docs and examples of @connection so I believe it should be working.

Here is what I use to create a store:
```
const store = { name : nameValue, storeTenantId: tenant};
await API.graphql(graphqlOperation(createStore, { input: store }));
```
Here is what I use to create a Tenant:
```
const tenant = { name : nameValue, email : emailValue};
await API.graphql(graphqlOperation(createTenant, { input: tenant }));
```

When I run the following query:
```
tenant = await API.graphql(graphqlOperation(getTenant, {id: "24b2345e-c4c8-43d9-93d7-20d767be08ec"}));
console.log(tenant);
```
I get the tenant object but the stores (and users) are null.
```
getTenant:
email: "test@test.com"
id: "24b2345e-c4c8-43d9-93d7-20d767be08ec"
name: "Test Tenant"
owner: "test-tenant"
stores: {items: Array(0), nextToken: null}
users: {items: Array(0), nextToken: null}
```
When I execute the getStore query it returns the Tenant as expected:
```
getStore:
id: "aba0aec7-52d6-4bdf-9342-6fde92b2a0a3"
name: "Test Store"
owner: "test-tenant"
tenant:
  email: "test@test.com"
  id: "24b2345e-c4c8-43d9-93d7-20d767be08ec"
  name: "Test Tenant"
  owner: "test-tenant"
stores: {nextToken: null}
users: {nextToken: null}
```
Where am I going wrong? Do I have to execute the updateTenant mutation after creating a new Store or User?
