### ISSUE TITLE
Deploy Failure: Throttling: Rate exceeded

### ISSUE THREAD

**Issue by fblanton** [aws-amplify/amplify-cli#3113]
**Describe the bug**
I have a project hooked up to AWS Amplify Console that auto deploys three branches from a private GitLab project.

It successfully deploys the beta branch to a `beta.` subdomain
It successfully deploys the master branch to an `app.` subdomain
**It fails to deploy the dev branch to a `dev.` subdomain**

It fails on the Build > Backend step of the auto deploy.

The error states:
```
[INFO]: init failed
[INFO]: Error: Project stack doesn't exist
```
Merging my work from my dev branch to my beta branch successfully triggers the beta deploy which then deploys successfully in AWS Amplify Console.

Deploying the `dev` env from the amplify-cli successfully updates the stack and allows me to at least test the backend with my local dev site.

Attempting  `envCache --set stackInfo ""` in the `amplify.yml` does not resolve the issue. It successfully clears the stack name, but then the stack name gathered from the deploy gives the same error. Again, the stack name does exist on CloudFormation

**To Reproduce**
1. Go to All Apps
2. Click on my only deployed app
3. Click on dev branch
4. Click Redeploy this version
5. Wait for the Build > Backend step to fail

**Expected behavior**
I would expect that if the amplify-cli is able to deploy the stack, that so would amplify console when referencing the same files

**Additional context**
**local machine details:**
macOS: @10.14.6
amplify-cli: @3.17.0

**AWS Amplify Console Details:**
Build image: Using default image
Build timeout: 30m

Live package updates
Amplify CLI: latest
Yarn: latest

`amplify.yml`
```yml
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - '#envCache --set stackInfo ""'
        - amplifyPush --environment $USER_BRANCH --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

The following stack does in fact exist when looking in CloudFormation:
`webapp-oneclickcode-20190509112706`

I can provide the full error if the `STACKINFO` object does not contain sensitive issue. To me it looks like it would be OK to share. The `STACKINFO` object is the only item with account specific items listed. None of which should provide a security leak as far as I understand.
