### ISSUE TITLE
How do I update src/graphql/schema.json

### ISSUE THREAD

**Issue by berenddeboer** [aws-amplify/amplify-cli#3134]
**Which Category is your question related to?**

Updating `src/graphql/schema.json`.

None of the commands I've seen such as `amplify push` do that, and older commands like `amplify code generate --download` no longer work.

**Amplify CLI Version** 

4.11.0.

**What AWS Services are you utilizing?**

AppSync + Aurora.

My `.graphconfig` (regenerated with latest):

```
projects:
  TestAPI:
    schemaPath: amplify/backend/api/TestAPI/build/schema.graphql
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: eu-west-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
```
