### ISSUE TITLE
Stucks on the push process - MFALambdaInputs

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-cli#3168]
I tried to set my Develop ENV to Production yesterday. 
Under Develop I could push everything. 
Because the NodeJS version also has the update in it, there is a lot to push at Production. 

-v = 4.12.0

What is new: Social Auth. 

`
Current Environment: production

| Category  | Resource name             | Operation | Provider plugin   |
| --------- | ------------------------- | --------- | ----------------- |
| Auth      | userPoolGroups            | Create    | awscloudformation |
| Function  | createProfile             | Create    | awscloudformation |
| Function  | analytics                 | Create    | awscloudformation |
| Auth      | aivyusers                 | Update    | awscloudformation |
| Api       | aivy                      | Update    | awscloudformation |
| Function  | estest                    | Update    | awscloudformation |
| Function  | zscoreCalculationLambda   | Update    | awscloudformation |
| Function  | pullNewExternalJobs       | Update    | awscloudformation |
| Function  | initBackend               | Update    | awscloudformation |
| Function  | getMatchingCareers        | Update    | awscloudformation |
| Function  | getNearbyJobOffer         | Update    | awscloudformation |
| Function  | aivyusersPostConfirmation | Delete    | awscloudformation |
| Analytics | aivyapp                   | Delete    | awscloudformation |
| Function  | addglobalcta              | No Change | awscloudformation |
| Function  | googleTalentSolution      | No Change | awscloudformation |
| Function  | addPartnerCompanies       | No Change | awscloudformation |
| Function  | addStepstoneJobs          | No Change | awscloudformation |
| Function  | addAldiJobs               | No Change | awscloudformation |
| Storage   | aivyUserContent           | No Change | awscloudformation |
? Are you sure you want to continue? Yes

The following types do not have '@auth' enabled. Consider using @auth with @model
	 - Bug
	 - ExamConfig
	 - Career
	 - Event
	 - EventOrganizer
	 - Article
Learn more about @auth here: https://aws-amplify.github.io/docs/cli-toolchain/graphql#auth

GraphQL schema compiled successfully.

_UPDATE_COMPLETE    storageaivyUserContent                AWS::CloudFormation::Stack Sat Jan 11 2020 13:52:44 GMT+0100 (GMT+01:00)
UPDATE_IN_PROGRESS authaivyusers                         AWS::CloudFormation::Stack Sat Jan 11 2020 13:52:44 GMT+0100 (GMT+01:00)
UPDATE_IN_PROGRESS storageaivyUserContent                AWS::CloudFormation::Stack Sat Jan 11 2020 13:52:44 GMT+0100 (GMT+01:00)
UPDATE_IN_PROGRESS aivy-rn-app-production-20190802143852 AWS::CloudFormation::Stack Sat Jan 11 2020 13:52:40 GMT+0100 (GMT+01:00) User Initiated
⠼ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS aivy-rn-app-production-20190802143852-authaivyusers-NG1VIYNC0PC7 AWS::CloudFormation::Stack Sat Jan 11 2020 13:52:45 GMT+0100 (GMT+01:00) User Initiated
⠇ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS SNSRole   AWS::IAM::Role        Sat Jan 11 2020 13:52:54 GMT+0100 (GMT+01:00) Requested update requires the creation of a new physical resource; hence creating one.
UPDATE_COMPLETE    MFALambda AWS::Lambda::Function Sat Jan 11 2020 13:52:52 GMT+0100 (GMT+01:00)
UPDATE_IN_PROGRESS MFALambda AWS::Lambda::Function Sat Jan 11 2020 13:52:52 GMT+0100 (GMT+01:00)
⠙ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS SNSRole AWS::IAM::Role Sat Jan 11 2020 13:52:55 GMT+0100 (GMT+01:00) Resource creation Initiated
⠧ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE SNSRole AWS::IAM::Role Sat Jan 11 2020 13:53:11 GMT+0100 (GMT+01:00)
⠇ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE    UserPool AWS::Cognito::UserPool Sat Jan 11 2020 13:53:17 GMT+0100 (GMT+01:00)
UPDATE_IN_PROGRESS UserPool AWS::Cognito::UserPool Sat Jan 11 2020 13:53:15 GMT+0100 (GMT+01:00)
⠴ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS UserPoolClientRole AWS::IAM::Role        Sat Jan 11 2020 13:53:26 GMT+0100 (GMT+01:00) Requested update requires the creation of a new physical resource; hence creating one.
UPDATE_IN_PROGRESS MFALambdaInputs    Custom::LambdaCallout Sat Jan 11 2020 13:53:24 GMT+0100 (GMT+01:00)
⠇ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS UserPoolClientRole AWS::IAM::Role Sat Jan 11 2020 13:53:27 GMT+0100 (GMT+01:00) Resource creation Initiated
⠋ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE UserPoolClientRole AWS::IAM::Role Sat Jan 11 2020 13:53:41 GMT+0100 (GMT+01:00)
⠹ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE    HostedUIProvidersCustomResource AWS::Lambda::Function Sat Jan 11 2020 13:53:46 GMT+0100 (GMT+01:00)
CREATE_COMPLETE    HostedUICustomResource          AWS::Lambda::Function Sat Jan 11 2020 13:53:46 GMT+0100 (GMT+01:00)
CREATE_IN_PROGRESS HostedUIProvidersCustomResource AWS::Lambda::Function Sat Jan 11 2020 13:53:46 GMT+0100 (GMT+01:00) Resource creation Initiated
UPDATE_COMPLETE    UserPoolClientLambda            AWS::Lambda::Function Sat Jan 11 2020 13:53:46 GMT+0100 (GMT+01:00)
CREATE_IN_PROGRESS HostedUICustomResource          AWS::Lambda::Function Sat Jan 11 2020 13:53:46 GMT+0100 (GMT+01:00) Resource creation Initiated
CREATE_IN_PROGRESS HostedUIProvidersCustomResource AWS::Lambda::Function Sat Jan 11 2020 13:53:46 GMT+0100 (GMT+01:00)
UPDATE_IN_PROGRESS UserPoolClientLambda            AWS::Lambda::Function Sat Jan 11 2020 13:53:46 GMT+0100 (GMT+01:00)
CREATE_IN_PROGRESS HostedUICustomResource          AWS::Lambda::Function Sat Jan 11 2020 13:53:45 GMT+0100 (GMT+01:00)
⠼ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS HostedUIProvidersCustomResourcePolicy AWS::IAM::Policy Sat Jan 11 2020 13:53:51 GMT+0100 (GMT+01:00) Resource creation Initiated
CREATE_IN_PROGRESS HostedUICustomResourcePolicy          AWS::IAM::Policy Sat Jan 11 2020 13:53:51 GMT+0100 (GMT+01:00) Resource creation Initiated
CREATE_IN_PROGRESS HostedUIProvidersCustomResourcePolicy AWS::IAM::Policy Sat Jan 11 2020 13:53:50 GMT+0100 (GMT+01:00)
UPDATE_IN_PROGRESS UserPoolClientLambdaPolicy            AWS::IAM::Policy Sat Jan 11 2020 13:53:49 GMT+0100 (GMT+01:00)
CREATE_IN_PROGRESS HostedUICustomResourcePolicy          AWS::IAM::Policy Sat Jan 11 2020 13:53:49 GMT+0100 (GMT+01:00)
⠹ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS HostedUICustomResourceLogPolicy       AWS::IAM::Policy Sat Jan 11 2020 13:54:08 GMT+0100 (GMT+01:00)
CREATE_COMPLETE    HostedUIProvidersCustomResourcePolicy AWS::IAM::Policy Sat Jan 11 2020 13:54:05 GMT+0100 (GMT+01:00)
CREATE_COMPLETE    HostedUICustomResourcePolicy          AWS::IAM::Policy Sat Jan 11 2020 13:54:05 GMT+0100 (GMT+01:00)
UPDATE_COMPLETE    UserPoolClientLambdaPolicy            AWS::IAM::Policy Sat Jan 11 2020 13:54:05 GMT+0100 (GMT+01:00)
⠸ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS HostedUICustomResourceLogPolicy          AWS::IAM::Policy Sat Jan 11 2020 13:54:09 GMT+0100 (GMT+01:00) Resource creation Initiated
CREATE_IN_PROGRESS HostedUIProvidersCustomResourceLogPolicy AWS::IAM::Policy Sat Jan 11 2020 13:54:08 GMT+0100 (GMT+01:00)
UPDATE_IN_PROGRESS UserPoolClientLogPolicy                  AWS::IAM::Policy Sat Jan 11 2020 13:54:08 GMT+0100 (GMT+01:00)
⠋ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS HostedUIProvidersCustomResourceLogPolicy AWS::IAM::Policy Sat Jan 11 2020 13:54:09 GMT+0100 (GMT+01:00) Resource creation Initiated
⠦ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS HostedUIProvidersCustomResourceInputs    Custom::LambdaCallout Sat Jan 11 2020 13:54:27 GMT+0100 (GMT+01:00)
CREATE_IN_PROGRESS HostedUICustomResourceInputs             Custom::LambdaCallout Sat Jan 11 2020 13:54:26 GMT+0100 (GMT+01:00)
UPDATE_COMPLETE    UserPoolClientLogPolicy                  AWS::IAM::Policy      Sat Jan 11 2020 13:54:23 GMT+0100 (GMT+01:00)
CREATE_COMPLETE    HostedUIProvidersCustomResourceLogPolicy AWS::IAM::Policy      Sat Jan 11 2020 13:54:23 GMT+0100 (GMT+01:00)
CREATE_COMPLETE    HostedUICustomResourceLogPolicy          AWS::IAM::Policy      Sat Jan 11 2020 13:54:23 GMT+0100 (GMT+01:00)
⠏ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE    HostedUICustomResourceInputs          Custom::LambdaCallout      Sat Jan 11 2020 13:54:31 GMT+0100 (GMT+01:00)
CREATE_IN_PROGRESS HostedUICustomResourceInputs          Custom::LambdaCallout      Sat Jan 11 2020 13:54:31 GMT+0100 (GMT+01:00) Resource creation Initiated
UPDATE_IN_PROGRESS IdentityPool                          AWS::Cognito::IdentityPool Sat Jan 11 2020 13:54:31 GMT+0100 (GMT+01:00)
CREATE_COMPLETE    HostedUIProvidersCustomResourceInputs Custom::LambdaCallout      Sat Jan 11 2020 13:54:30 GMT+0100 (GMT+01:00)
CREATE_IN_PROGRESS HostedUIProvidersCustomResourceInputs Custom::LambdaCallout      Sat Jan 11 2020 13:54:30 GMT+0100 (GMT+01:00) Resource creation Initiated
⠋ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE IdentityPool AWS::Cognito::IdentityPool Sat Jan 11 2020 13:54:32 GMT+0100 (GMT+01:00)
⠦ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE    OAuthCustomResource AWS::Lambda::Function Sat Jan 11 2020 13:54:34 GMT+0100 (GMT+01:00)
CREATE_IN_PROGRESS OAuthCustomResource AWS::Lambda::Function Sat Jan 11 2020 13:54:34 GMT+0100 (GMT+01:00) Resource creation Initiated
CREATE_IN_PROGRESS OAuthCustomResource AWS::Lambda::Function Sat Jan 11 2020 13:54:33 GMT+0100 (GMT+01:00)
⠦ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS OAuthCustomResourcePolicy AWS::IAM::Policy Sat Jan 11 2020 13:54:39 GMT+0100 (GMT+01:00) Resource creation Initiated
CREATE_IN_PROGRESS OAuthCustomResourcePolicy AWS::IAM::Policy Sat Jan 11 2020 13:54:38 GMT+0100 (GMT+01:00)
⠼ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE OAuthCustomResourcePolicy AWS::IAM::Policy Sat Jan 11 2020 13:54:53 GMT+0100 (GMT+01:00)
⠋ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS OAuthCustomResourceLogPolicy AWS::IAM::Policy Sat Jan 11 2020 13:54:56 GMT+0100 (GMT+01:00)
⠦ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS OAuthCustomResourceLogPolicy AWS::IAM::Policy Sat Jan 11 2020 13:54:58 GMT+0100 (GMT+01:00) Resource creation Initiated
⠴ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE OAuthCustomResourceLogPolicy AWS::IAM::Policy Sat Jan 11 2020 13:55:12 GMT+0100 (GMT+01:00)
⠏ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS OAuthCustomResourceInputs Custom::LambdaCallout Sat Jan 11 2020 13:55:15 GMT+0100 (GMT+01:00)
⠧ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS OAuthCustomResourceInputs Custom::LambdaCallout Sat Jan 11 2020 13:55:18 GMT+0100 (GMT+01:00) Resource creation Initiated
⠋ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE OAuthCustomResourceInputs Custom::LambdaCallout Sat Jan 11 2020 13:55:18 GMT+0100 (GMT+01:00)
⠸ Updating resources in the cloud. This may take a few minutes..._
`

From this moment nothing more happens. I got the message yesterday about the NodeJS version. I have adjusted it manually. 

I'm not sure what it could be. 
I checked the console on Cloudfront. 
It's not breaking up there either. 
Unfortunately, I don't see what they're going to try to do next.

**If i add a new ENV - all is fine and the push is working.**

**Comment by davidbiller** [comment]
Is there any option for me to check why it is stucking? A log?

**Comment by davidbiller** [comment]
i tried now 
amplify update auth
with the default settings without social auth. 
It stucks too...

**Comment by davidbiller** [comment]
<img width="1304" alt="Bildschirmfoto 2020-01-12 um 18 03 26" src="https://user-images.githubusercontent.com/7137361/72222533-11cff880-3566-11ea-9f0c-e7f7a377b262.png">

I just tried to update the NodeJS for the production without a merge of develop.

I get the error message (see picture) 

The tables given here are only available in Develop. Production should not even know them. I also used amplify env production -restore

**Comment by davidbiller** [comment]
it stucks on nestedStack:

MFALambdaInputs

**Comment by davidbiller** [comment]
@kaustavghosh06 
I guess you are my person for this right?

**Comment by davidbiller** [comment]
<img width="1471" alt="Bildschirmfoto 2020-01-12 um 21 09 14" src="https://user-images.githubusercontent.com/7137361/72224918-d04c4700-357f-11ea-8045-203d2920ac3b.png">
Lambda: MFALambdaInputs

**Comment by kaustavghosh06** [comment]
@davidbiller Which region are you trying to deploy to? 
One workaround is changing the require('cfn-response') to require('./cfn-response') in your auth Cloudformation template for the resource/lambda function you're getting an error for.

**Comment by davidbiller** [comment]
@kaustavghosh06 eu-central-1
at the moment the cloudFormation is stucking on update process since 1 hour...

**Comment by kaustavghosh06** [comment]
@davidbiller Yes, the update process should complete in sometime and then you can try out the suggested workaround. 
I wasn't able to reproduce the issue in `eu-central-1` for a newly added auth resource. Can you check your Cloudformation template located in `amplify/backend/auth/<cloudformation-template>`
directory and see if you have following block correctly:
```
MFALambda:
  # Lambda which sets MFA config values
  # Depends on MFALambdaRole for role ARN
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        ZipFile: !Join 
          - |+
          - - 'const response = require(''cfn-response'');'
            - 'const aws = require(''aws-sdk'');'
            - 'const identity = new aws.CognitoIdentityServiceProvider();'
            - 'exports.handler = (event, context, callback) => {'
            - ' if (event.RequestType == ''Delete'') { '
            - '   response.send(event, context, response.SUCCESS, {})'
            - ' }'
            - ' if (event.RequestType == ''Update'' || event.RequestType == ''Create'') {'
            - '   let totpParams = {};'
            - '   try {'
            - '     totpParams = {'
            - '       UserPoolId: event.ResourceProperties.userPoolId,'
            - '       MfaConfiguration: event.ResourceProperties.mfaConfiguration,'
            - '       SmsMfaConfiguration: {'
            - '         SmsAuthenticationMessage: event.ResourceProperties.smsAuthenticationMessage,'
            - '         SmsConfiguration: {'
            - '           SnsCallerArn: event.ResourceProperties.smsConfigCaller,'
            - '           ExternalId: event.ResourceProperties.smsConfigExternalId'
            - '         }'
            - '       },'
            - '       SoftwareTokenMfaConfiguration: {Enabled: event.ResourceProperties.totpEnabled.toLowerCase() === ''true'' ? true : false}'
            - '     };'
            - '   } catch(e) {'
            - '     response.send(event, context, response.FAILED, {e});'
            - '   };'
            - '   identity.setUserPoolMfaConfig(totpParams).promise()'
            - '     .then((res) => {'
            - '       response.send(event, context, response.SUCCESS, {res});'   
            - '     })'
            - '     .catch((err) => {'
            - '       response.send(event, context, response.FAILED, {err});'
            - '     });'
            - ' }'
            - '};'
      Handler: index.handler
      Runtime: nodejs10.x  // Check for this
      Timeout: '300'
      Role: !GetAtt 
        - MFALambdaRole
        - Arn
    DependsOn: MFALambdaRole

```
