### ISSUE TITLE
Amplify API - schema changes - no changes detected

### ISSUE THREAD

**Issue by LpmRaven** [aws-amplify/amplify-cli#3191]
**Describe the bug**
When I make a change to my API schema, changes are not detected.

**Amplify CLI Version**
4.12.0

**To Reproduce**

1. Change API schema
2. Run `amplify api update`
3. Run `amplify push`
4. `No changes detected`

**Expected behavior**
The ability to make changes to the API without having to tear down the entire stack.

My current way around this is to: 

1. Run `amplify delete`
2. Run `amplify init`
3. Run `amplify add api`
4. Run `amplify push`

Obviously, this is not feasible in the long-term as all my database data is deleted every time I need to make minor changes to the schema. 

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v12.14.1

**Comment by nikhname** [comment]
@LpmRaven After making changes to your schema what do you see when you run amplify status?

**Comment by nikhname** [comment]
What changes are you making when you run amplify api update? This is not necessary if you only updated the schema.

**Comment by LpmRaven** [comment]
@nikhname Running `amplify status` I get:
```
Current Environment: dev

| Category | Resource name  | Operation | Provider plugin   |
| -------- | -------------- | --------- | ----------------- |
| Api      | myApi          | No Change | awscloudformation |
```
If I run `amplify push`, my cloud resource does not change.

development/schema.graphql:
```
type Product @model
  @key (fields: ["globalIdColor", "region", "productType", "categorySlug", "subCategorySlug", "size", "supplier"])
  # Indexes for pages
...
  {
  globalIdColor: String!
...
  color: String!
  allColors: [String!]    <---- This is a new field
  primaryImage: String!
  rrp: Int!
  rating1: Int!
  rating2: Int!
  rating3: Int!
}
```
This is the change to my schema (above), I have added one new field and I need my cloud resources to change, (including the generated resolvers and the dynamodb), what do I do?

I've gone to `amplify/backend/api/myapi/schema.graphql` and it does not contain my new field.
I store my schema in a development folder as all of the `amplify` folder is generated. The first time I run `amplify add api` I reference my schema in the development folder when it asks if I have a schema for the project. I have a feeling it may no longer be referencing the schema I told it to use. In the graphqlconfig.yml (as you can see below) it does not reference the schema I told it to use (I have not changed this file). Is this an error in the generation of the api? Or should it no longer use the schema I told it to once it generates the schema at `amplify/backend/api/myapi/schema.graphql`?

```yml
projects:
  myapi:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
```
