### ISSUE TITLE
Lack of depth after codegen --max-depth 6

### ISSUE THREAD

**Issue by michaelcuneo** [aws-amplify/amplify-cli#3308]
I've just changed my GraphQL schema a little, and I've ended up with no depth now. It only goes so far then stops, and gives me little to no data.

Was there a change in the latest versions of Amplify-cli that would have caused this? I have just recently updated my amplify-cli and my first push after the update of the client asked me to update the api. So I said yes... and now my project is all messed up.

**Comment by michaelcuneo** [comment]
In my schema, I have Galleries and Images.

I add the gallery first, which gives me a Gallery ID... Then I generate images, and provide the gallery ID to them during creation.

This is all within a Project Model... i.e. Project -> Gallery -> Images.

```
type Project @model {
  id: ID!
  date: AWSDateTime
  title: String!
  abstract: String!
  details: String!
  funding: String!
  videoURL: String
  categoryId: ID!
  category: Category! @connection(name: "CategoryLink")
  gallery: Gallery @connection(name: "ProjectGallery")
  collaborators: [ProjectStaff]! @connection(name: "ProjectCollaborators")

type Image @model {
  id: ID!
  key: String!
  mime: String!
  gallery: Gallery @connection(name: "ImageList")
}

type Gallery @model {
  id: ID!
  name: String!
  project: Project @connection(name: "ProjectGallery")
  images: [Image] @connection(name: "ImageList")
}

```

Project and Gallery and Images are all created, but if I list a project ... this is my result.

The project has a gallery, but the gallery doesn't contain it's images. Only the ID and Name of the gallery. The project that it belongs to obviously exists because it's connected to this project... but the images do not connect.

Similarly I have a Staff member, with connected Roles... my Staff members are created successfully but won't list their roles.

```
id: "9fd588bb-2d5d-4ccd-8223-41637b215af4"
date: null
title: "Test Stuff"
abstract: "Test Stuff"
details: "Test Stuff"
funding: "TEST"
videoURL: null
categoryId: "8a4bd170-43c2-11ea-b77f-2e728ce88125"
category: {id: "8a4bd170-43c2-11ea-b77f-2e728ce88125", label: "Future Work", value: "8a4bd170-43c2-11ea-b77f-2e728ce88125", description: "Future Work focusses on the future of work across the creative industries."}
gallery: {id: "c435aab4-61e7-42b0-9e49-a4572050eac1", name: "Test Stuff"}
collaborators: {nextToken: null}
```

**Comment by michaelcuneo** [comment]
This has now carried over to a production environment, and I have had to push the entire web app into maintenance mode because everything has fallen over.

Every amplify serve I perform now makes an 'Update' to the 'api' but I never make any changes to the graphql.schema.

Not sure how to move forward now to fix this up, people around here are waiting for me to perform work on our sites.

**Comment by kaustavghosh06** [comment]
@michaelcuneo What's your maxDepth setting in the `<project-root>/.graphqlconfig.yml` file?
It should look something like this

```yml
projects:
  mytestproject:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        maxDepth: 8
extensions:
  amplify:
    version: 3


```
