### ISSUE TITLE
How to implement Custom GraphQL Transformer

### ISSUE THREAD

**Issue by lennybr** [aws-amplify/amplify-cli#348]
** Which Category is your question related to? **
AppSync GraphQL

** Provide additional details e.g. code snippets **
The docs at https://github.com/aws-amplify/amplify-cli/blob/master/how-to-write-a-transformer.md outline how to write custom transformers. But I was wondering how to actually integrate these into the amplify api gql-compile workflow?

**Comment by mikeparisstuff** [comment]
We were actually discussing something like this today. There is no way to do it right now other than by building your own lightweight CLI that calls the transformer library under the hood. You can then load whatever transformers you want as well as write and include your own custom transformers. This is what is outlined in the doc and now on the amplify docs here https://aws-amplify.github.io/docs/js/graphql

Looking to the future, we want to develop some sort of system that would allow you to include your own transformers via a flag and/or a setting in .amplifyrc or other config file. I would think something like this could work:

```
amplify api gql-compile --transformers model auth custom
```

with an associated config somewhere:

```yml
# mapping of easy name from cli to name of npm package that must be installed on the machine.
transformers:
  model: graphql-model-transformer
  auth: graphql-auth-transformer
  custom: my-custom-transformer-package
```
