### ISSUE TITLE
graphqconfig should reflect removed api

### ISSUE THREAD

**Issue by kjetilge** [aws-amplify/amplify-cli#3546]
When I remove an API end then later create a new one with a different name, the schemaPath still has the former name.

If I have an initial config that looks like this:
```
projects:
  fftest9:
    schemaPath: amplify/backend/api/fftest9/build/schema.graphql
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
```

- And then delete the API, then add a new API named ```fftest11``` and then try to run ```amplify codegen``` the results in this:

```
ENOENT: no such file or directory, open '/Users/kjetilge/Documents/GitHub/FAGFILM_AMPLIFY_APPS/fagfilm-backend/amplify/backend/api/fftest9/build/schema.graphql'
```
**The solution I'd like**
The schemaPath should be updated when I remove or add a new API.

For now I can change the schemaPath manually. It works fine, but it took some time to figure out what was happening.

I'm using the mock backend when writing this, but I believe I have encountered the same problem when running proper backend.
