### ISSUE TITLE
Use a manually created user pool with an existing API when using amplify cli with Angular. 

### ISSUE THREAD

**Issue by vchaddha** [aws-amplify/amplify-cli#3565]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
amplify cli, api , auth, manual configuration

**Amplify CLI Version** 
4.13.4
You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**
AppSync, Cognito user pool.

**Provide additional details e.g. code snippets**
Anyone faced the use case wherein amplify project has api and auth, and we need to change the user pool being used.
What I tried doing already:

* https://aws-amplify.github.io/docs/js/api#manual-configuration

* https://aws-amplify.github.io/docs/js/authentication#manual-configuration

used the 

```
Amplify.configure(
Auth:{}
API:{}
)
```

and made sure that the Auth segment shows the new user pool details and related oauth specifications.
Though, what I noticed, is that after doing this, the authentication is being handled by the new user pool, but appsync still expects an authenticated user from the old user pool. Below is my analysis till yet.

**/amplify/backend/api/notetaker/parameters.json** contains this:

```
{
    "AppSyncApiName": "notetaker",
    "DynamoDBBillingMode": "PAY_PER_REQUEST",
    "DynamoDBEnableServerSideEncryption": "false",
    "AuthCognitoUserPoolId": {
        "Fn::GetAtt": [
            "authnotetaker0612adbe",
            "Outputs.UserPoolId"
        ]
    }
}  
```

which goes into the build.

Now, checking:
**Amplify/backend/auth/notetaker0612abde/notetaker0612adbe-cloudformation-template.yml **

```
UserPoolId:
    Value: !Ref 'UserPool'
    Description:  Id for the user pool
  UserPoolName:
    Value: !Ref userPoolName 
```

And when I check this stack, the outputs show up as the old user pool
and not as the new user pool.
Due to this:

```
UserPool:
    Type: AWS::Cognito::UserPool
    UpdateReplacePolicy: Retain
    Properties:
      UserPoolName: !If [ShouldNotCreateEnvResources, !Ref userPoolName, !Join ['',[!Ref userPoolName, '-', !Ref env]]]
```

Which makes me realize that the exports file just overwrites the user pool being used for authentication, but, essentially the older user pool is still being referenced according to the environment settings, which we need to change.

I see that the amplify-meta.json provides the outputs as well, upon build (after we do amplify push). 

```
"output": {
                "UserPoolId": "<old user pool id>",
                "AppClientIDWeb": "<old web client id>",
                "AppClientID": "<old client id>",
                "IdentityPoolId": "<old identity pool id>",
                "IdentityPoolName": "<old identity pool name>",
                "UserPoolName": "<old user pool name>",
                "AppClientSecret": "<old client secret>"
            },
```

the entries are all reverted to the old entries, so trying to find the source from which amplify understands which user pool to use, so as to provide this output, even after manually configuring amplify Auth with the new user pool details.
