### ISSUE TITLE
Cross account CI/CD for ampify-cli project

### ISSUE THREAD

**Issue by vchaddha** [aws-amplify/amplify-cli#3623]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
amplifyPush script to be used cross account, using CodeBuild.

**Amplify CLI Version** 
amplify --version
4.14.1
You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**
amplify-cli, codepipeline, codebuild. Cross account CI/CD.

**Provide additional details e.g. code snippets**
* **Problem statement:**
I am trying to setup cross account CI/CD pipeline using Codepipeline with 2 stages for Codebuild and there are two issues that I am trying to resolve, which I need help with.
* **Issue 1**
I am using something similar that amplify console does, wherein I use the helper script amplifyPush.sh
https://github.com/aws-amplify/amplify-console/blob/master/scripts/amplifyPush.sh

I use a docker image for my build environment in CodeBuild, which is defined as follows:
```
# Use the standard Amazon Linux base, provided by ECR/KaOS
# It points to the standard shared Amazon Linux image, with a versioned tag.
FROM amazonlinux:2
MAINTAINER Amazon AWS

# Framework Versions
ENV VERSION_NODE=10.16.3

# UTF-8 Environment
ENV LANGUAGE en_US:en
ENV LANG=en_US.UTF-8
ENV LC_ALL en_US.UTF-8

## Install OS packages
RUN touch ~/.bashrc
RUN yum -y install \
      jq \
      tar \
      zip \
      gzip \
      python3 \
      python3-devel \
    yum clean all && \
    rm -rf /var/cache/yum


## Install Node 10
#RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
RUN /bin/bash -c ". ~/.nvm/nvm.sh && \
	nvm install $VERSION_NODE && nvm use $VERSION_NODE && \
	nvm alias default node && nvm cache clear"

ENV PATH /root/.nvm/versions/node/v${VERSION_NODE}/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

## Install AWS Amplify CLI for VERSION_NODE
RUN /bin/bash -c ". ~/.nvm/nvm.sh && nvm use ${VERSION_NODE} && \
    npm install -g @aws-amplify/cli"

RUN /bin/bash -c ". ~/.nvm/nvm.sh && nvm use ${VERSION_NODE} && \
    npm install -g typescript && \
    npm install -g @angular/cli && \
    npm install -g @angular-devkit/build-angular" 

## Environment Setup
RUN echo "nvm use ${VERSION_NODE} 1> /dev/null" >> ~/.bashrc

## Install awscli
RUN /bin/bash -c "pip3 install awscli && rm -rf /var/cache/apk/*"

COPY envCache /usr/local/bin
RUN chmod +x /usr/local/bin/envCache
COPY amplifyPush /usr/local/bin
RUN chmod +x /usr/local/bin/amplifyPush

RUN source ~/.bashrc

ENTRYPOINT [ "bash", "-c" ]
```

When I use the below build file:
```
version: 0.2

phases:
  build:
    commands:
      - assumes_role=`aws sts assume-role --role-arn <cross account role arn> --role-session-name int`
      - AWS_ACCESS_KEY_ID=`echo $assumes_role | jq -r .Credentials.AccessKeyId`
      - AWS_SECRET_ACCESS_KEY=`echo $assumes_role | jq -r .Credentials.SecretAccessKey`
      - AWS_SESSION_TOKEN=`echo $assumes_role | jq -r .Credentials.SessionToken`
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set aws_session_token $AWS_SESSION_TOKEN
      - aws configure set default.region us-east-1
      - chmod u+x ./amplifyPush.sh
      - ./amplifyPush.sh
      - amplify publish
    finally:
      - echo Build completed

artifacts:
  files:
    - '**/*'
```
It just gives the message: 
```
usage: amplify-push <--environment|-e <name>> <--simple|-s>
--environment  The name of the Amplify environment to use
--simple  Optional simple flag auto-includes stack info from env cache
```
which makes me think that it does not auto initiate an environment.

When I use 
```
- chmod u+x ./amplifyPush.sh
- ./amplifyPush.sh -s -e dev
```

It does initiate the environment and creates resources in the other account, though, this is only for the first time. When I trigger this build using a change in codecommit repository, it fails saying that the s3 bucket already exists, which makes me understand that the script does not get the existing environment in the re-spun container for codebuild, and thus tries to initiate the environment again which includes creating the hosting s3 bucket again, on which it fails. Please let me know if you need complete logs.

I read a couple of other resources and issues, on which it was mentioned that amplify pull env can be used to pull the environment into the current-backend files, and then the push can be done. Though this did not help.

**My question** is, how can I make sure that on each CodeBuild build, the same environment can be used, or is there any other better way to setup cross account CI/CD pipeline. I am stuck at this point for a long time now.

* **Issue 2**
when building the project, the output Directory (outDir) is set to ./dist/<application name> in which <build files> are created. 
I have added hosting by using `amplify add hosting`
and when I use `amplify publish`, it does not copy any dist file to S3 bucket with the default project configuration.

```
{
    "projectName": "Angular-app",
    "version": "3.0",
    "frontend": "javascript",
    "javascript": {
        "framework": "angular",
        "config": {
            "SourceDir": "src",
            "DistributionDir": "dist",
            "BuildCommand": "npm run-script build",
            "StartCommand": "npm start"
        }
    },
    "providers": [
        "awscloudformation"
    ]
}
```

though when I change this to the following:
```
{
    "projectName": "Angular-app",
    "version": "3.0",
    "frontend": "javascript",
    "javascript": {
        "framework": "angular",
        "config": {
            "SourceDir": "src",
            "DistributionDir": "dist/Angular-app",
            "BuildCommand": "npm run-script build",
            "StartCommand": "npm start"
        }
    },
    "providers": [
        "awscloudformation"
    ]
}
```
it works fine locally. 

This is what I am trying to replicate in the cross account build.
In the amplifyPush file(https://github.com/aws-amplify/amplify-console/blob/master/scripts/amplifyPush.sh), below is what I have tried, but to no use:
```
AWSCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":true,\ 
\"profileName\":\"default\",\
\"SourceDir\": \"src\",\
\"DistributionDir\": \"dist/Angular-app\",\
\"BuildCommand\": \"npm run-script build\",\
\"StartCommand\": \"npm start\"\
}"
```
I also tried this:
```
AMPLIFY="{\
\"projectName\":\"dxcapp\",\
\"envName\":\"${ENV}\",\
\"javascript\": {\
\"framework\": \"angular\",\
\"config\": {\
\"SourceDir\": \"src\",\
\"DistributionDir\": \"dist/Angular-app\",\
\"BuildCommand\": \"npm run-script build\",\
\"StartCommand\": \"npm start\"\
}\
}\
}"
```

When using amplify publish, it still does not use these configuration items. Rather just uses ng build with dist as the distribution directory, and so, when I check the S3 bucket, it is empty, even after successful completion of the build stage.

**My question** is, how can I make sure that the project settings in the amplify/.config/project-config.json can be replicated by the amplifyPush script on the codebuild container?

Please let me know if you have any questions on what I am trying to do.
