### ISSUE TITLE
When adding analytics, the CLI attempts to edit attributes for existing UserPool, push fails with "Updating alias attributes is not allowed"

### ISSUE THREAD

**Issue by chrisl777** [aws-amplify/amplify-cli#382]
**Describe the bug**
I'm attempting to add the analytics category to an Amplify project. It's a React web app project that already contains Auth, Hosting and Api categories that are already published and functioning. When I add the analytics category and push, the push fails as it's apparently trying to modify the Cognito user pool in an invalid way. 

**To Reproduce**
-Set up Amplify project, add auth. (I believe we modified the Cognito setup manually later to have Username sign in but also allow Email as an alias - see screenshot below.)
-Set up the identity pool to allow unauthenticated access so that website guest analytics can be captured (see screenshot below).
-`$ amplify add analytics`
> Using service: Pinpoint, provided by: awscloudformation
> ? Provide your pinpoint resource name: MyAnalytics
> Adding analytics would add the Auth category to the project if not already added.
> ? Apps need authorization to send analytics events. Do you want to allow guests and unauthenticated users to send analytics events? (we recommend you allow this when getting started) true
> Successfully added auth resource locally.
> Successfully added resource MyAnalytics locally

-`$ amplify push`
-The push fails: 
`UPDATE_FAILED               UserPool                                            AWS::Cognito::UserPool     Wed Oct 31 2018 23:41:55 GMT-0700 (Pacific Daylight Time) Updating alias attributes is not allowed.`            
`UPDATE_ROLLBACK_IN_PROGRESS [xxxxx] AWS::CloudFormation::Stack Wed Oct 31 2018 23:41:56 GMT-0700 (Pacific Daylight Time) The following resource(s) failed to update: [UserPool].`

**Expected behavior**
It is expected that the Amplify CLI will not try to modify the attributes for the Cognito user pool in this case.

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
- Node: v10.13.0

**Additional context**
I found the probable cause of this failure. It appears that, after running the `amplify add analytics` command, the`AliasAttributes: ["email"]` line gets removed from the Cloud Formation template for auth. When I add this line back in, the push succeeds. However, it is not obvious why the push error is happening and it took some trial an error to figure out why. 

```
UserPool:
  # Created upon user selection
  # Depends on SNS Role for Arn if MFA is enabled
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref userPoolName
      Schema: 
        
        -
          Name: email
          Required: true
          Mutable: true
        
      AliasAttributes: ["email"] <---- This line gets removed by the Amplify CLI, adding back in solved the issue. 
      AutoVerifiedAttributes: !Ref autoVerifiedAttributes
```

**Screenshots**
The user pool setup:
<img width="1079" alt="screen shot 2018-10-31 at 11 33 39 pm" src="https://user-images.githubusercontent.com/230479/47837225-72f81b80-dd68-11e8-80b2-d53af1adc249.png">

The identity pool setup: 
<img width="1162" alt="screen shot 2018-10-31 at 11 34 09 pm" src="https://user-images.githubusercontent.com/230479/47837227-768ba280-dd68-11e8-9b95-4ce17458d62f.png">
