### ISSUE TITLE
amplify push --yes leaves generatedFileName empty

### ISSUE THREAD

**Issue by jmcgeheeiv** [aws-amplify/amplify-cli#4242]
**Describe the bug**
`amplify push --yes` does not create the default API `src/app/API.service.ts`. It renders `.graphqlconfig.yml` with no generated file name:
```yaml
projects:
  myproject:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
```

When I run `amplify push` and **interactively** accept all the defaults, `src/app/API.service.ts` is generated and `.graphqlconfig.yml` correctly contains the default generated file name:
```yaml
projects:
  mediatekaiotcom:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/API.service.ts
        docsFilePath: src/graphql
```
I tried the `amplify push --codegen` option, but this did not work, either. This command also generates no `src/app/API.service.ts`, and `.graphqlconfig.yml` with an empty `generatedFileName`:
```shell
amplify push --yes --codegen {\"generatedFileName\":\"src/app/API.service.ts\"}
```

**Amplify CLI Version**
Amplify 4.18.1

**To Reproduce**

Add a GraphQL API:
```shell
amplify add api
```      
Select the answers shown below in **bold**:

> Please select from one of the below mentioned services: **GraphQL**
> Provide API name: **mediatekaiotcom**
> Choose the default authorization type for the API **Amazon Cognito User Pool**
> Do you want to configure advanced settings for the GraphQL API **Yes, I want to make some additional changes.**
> Configure additional auth types? **No**
> Configure conflict detection? **No**
> Do you have an annotated GraphQL schema? **No**
> Do you want a guided schema creation? **Yes**
> What best describes your project: **Single object with fields (e.g., “Todo” with ID, name, description)**
> Do you want to edit the schema now? **Yes**
> Choose your default editor: **Your choice**

File `schema.graphql` will appear in the text editor that you chose. Replace the entire file contents with:
```graphql
type User @model {
  id: ID!
  username: String!
  firstName: String
  lastName: String
  bio: String
  image: String
}
```
Save the file. Press <Return> if necessary.

Push the API, specifying `--yes`:
```shell
amplify push --yes
```
Observe that in `.graphqlconfig.yml`, `generatedFileName` is empty, and no `src/app/API.service.ts` is generated.

**Expected behavior**
File `.graphqlconfig.yml` should contain,
```yaml
generatedFileName: src/app/API.service.ts
```
and `src/app/API.service.ts` should be generated. 

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Node Version 12.16.2

**Additional context**
None
