### ISSUE TITLE
amplify codegen types not creating anything

### ISSUE THREAD

**Issue by RandomEngy** [aws-amplify/amplify-cli#4309]
No code is generated for `amplify codegen types` on an API created in AWS console. Let me know if I'm doing something wrong...

**Amplify CLI Version**
4.19.0

**To Reproduce**
1) `amplify add codegen --apiId myId`
2) `amplify codegen types`

**Expected behavior**
Creates some types in my project. The docs seem to indicate it should produce some Java classes.

**Actual behavior**
There is no console output and no extra files are created in my project.

**Desktop:**
 - OS: Windows 10
 - Node Version: 12.16.3

**Additional context**
.graphqlconfig.yml:
```
projects:
  FocalistTest1:
    schemaPath: app/src/main/graphql/schema.json
    includes:
      - app/src/main/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app/src/main/graphql/com/amazonaws/amplify/generated/graphql
        region: us-east-2
        apiId: [snipped]
        maxDepth: 2
extensions:
  amplify:
    version: 3
```

app/src/main/graphql/schema.json exists and looks correct.
