### ISSUE TITLE
Unable to create custom templates from the Amplify CLI.

### ISSUE THREAD

**Issue by Jay2113** [aws-amplify/amplify-cli#4453]
**Describe the bug**
I am trying to create custom templates within my Amplify application. However, while trying to push the sample template from the CLI I am observing the following error “An error occurred during the push operation: No such resource AWS::MediaConvert::Queue”.

**Amplify CLI Version**
4.18.0

**To Reproduce**
Please kindly refer to this sample template: 
[sample-cloudformation-template.zip](https://github.com/aws-amplify/amplify-cli/files/4725625/sample-cloudformation-template.zip)

These are the steps that I used: https://docs.amplify.aws/cli/usage/customcf

I tried to create a CloudFormation stack from the CloudFormation console using the sample template and I was able to create the stack from the console. 

I was also able to create a CloudFormation stack from the AWS CLI using the sample template by running the following command:

aws2 cloudformation create-stack --stack-name myteststack --template-body file://sample-cloudformation-template.yml --parameters ParameterKey=env,ParameterValue=dev

**Expected behavior**
Create and successfully push the sample template from the CLI.

**Screenshots**
![CF-error](https://user-images.githubusercontent.com/38470430/83678676-1bf1a280-a5ac-11ea-9a91-190316cafd96.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: 13.11.0

**Comment by venkatesh-kadiyala** [comment]
We are looking to create AWS Media Convert Queue through amplify CLI, it creates the resource but when we try to get the ARN using Fn::GetAtt, we get the error saying "No such resource". The same behavior happens when we get the ARN for AWS::WAFv2::WebACL.

**Comment by ammarkarachi** [comment]
Is it the format logicalusername.format or similar?

**Comment by venkatesh-kadiyala** [comment]
Yes. Below is the sample snippet where we want to get the ARN. "QUEUE" is the logical ID.

Outputs:
  QueueArn:
    Description: "ARN of the Queue"
    Value: !GetAtt QUEUE.Arn

**Comment by ammarkarachi** [comment]
Can you also provide the snippet on how you import that particular ARN?

**Comment by venkatesh-kadiyala** [comment]
Below is the template we try to run using amplify CLI by having custom cloud formation template. If we remove outputs section, it creates fine but getting error if we want to get the ARN of the resource.

```
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  env:
    Type: String
    
Resources:
  # BEGIN QUEUE RESOURCE
  QUEUE:
    Type: AWS::MediaConvert::Queue
    Properties: 
      Description: "Queue for processing transcoding jobs"
      Name: !Sub
      - CLIPS-VOD-${env}
      - { env: !Ref env }
      PricingPlan: "ON_DEMAND"
      Status: "ACTIVE"
    
    

Outputs:
  QueueArn:
    Description: "ARN of the Queue"
    Value: !GetAtt QUEUE.Arn

```
