### ISSUE TITLE
API.service.ts not changed after local graphql schema change

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#4564]
**Describe the bug**
I add a new method in my ```type Query``` in schema.graphql. amplify mock does not generate an updated API.service.ts, quries.graphql, etc.. according to this newly added method. 

**Amplify CLI Version**
4.21.3

**To Reproduce**
Here's my .graphqlconfig.yml file: 

```
projects:
  MyGraphQLAPI:
    schemaPath: amplify/backend/api/MyGraphQLAPI/build/schema.graphql
    includes:
      - frontend/projects/shared/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: frontend/projects/shared/graphql/API.service.ts
        docsFilePath: frontend/projects/shared/graphql
        region: us-east-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
```

**Desktop (please complete the following information):**
OSX. node 13.2.0

**Additional context**
Is it because my schemaPath points to the build version of schema.graphql rather than original? How do I regenerate this? amplify api codegen and amplify api gql-compile don't change it.
