### ISSUE TITLE
Cache invalidation with gatsby apps

### ISSUE THREAD

**Issue by ohlr** [aws-amplify/amplify-cli#4598]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Cache invalidation with gatsby

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.13.2

**What AWS Services are you utilizing?**

https://aws.amazon.com/blogs/mobile/aws-amplify-console-supports-instant-cache-invalidation-and-delta-deployments/

I have a gatsby-amplify app. If I remove pages, aka paths from my gatsby app and access them afterwards they are not accessible on my local builds but on AWS the CDN serves the old version of the app when accessing these routes. As soon I access a valid route, it switches to the new version of the app.

My build settings:
```
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn build
  artifacts:
    baseDirectory: public
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

where yarn build references "gatsby build",
