### ISSUE TITLE
on the CI/CD, amplifyPush should check when there's no changes

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-cli#4842]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

`amplifyPush` pushes backend even when there are no changes.

**Amplify CLI Version**
4.24.1

**To Reproduce**

just use `amplifyPush` on the CI/CD

**Expected behavior**

`amplifyPush` should not push the backend when there are no changes.

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: N/A
 - Node Version: N/A

**Additional context**

N/A

**Comment by UnleashedMind** [comment]
@aprilmintacpineda 
are you getting this on Amplify Console?

**Comment by aprilmintacpineda** [comment]
@UnleashedMind yes it's on the Continuous Deployment on the amplify console. I have the following `amplify.yml`

```yml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
