### ISSUE TITLE
[bug] `amplify configure codegen` doesn't generate typescript code when switching from javascript

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/amplify-cli#4858]
**Describe the bug**

using `amplify configure codegen` to configure typescript code doesnt generate code.

**Amplify CLI Version**
4.24

**To Reproduce**

- have a very simple amplify init setup with a single graphql api in javascript (git repo here https://github.com/sw-yx/testamplify12121)
- then run `amplify configure codegen` and try to switch the generated code to javascript
- nothing happens

**Expected behavior**

- typescript code should be generated

**Screenshots**
![image](https://user-images.githubusercontent.com/6764957/87696311-3467f600-c7c3-11ea-81cc-92fd7758c6c2.png)

**Desktop (please complete the following information):**
 - OS: mac
 - Node Version. 12.8

**Comment by sw-yx** [comment]
i have tried generating the .ts from scratch in a new project and that works fine. so it is really about the *switching* from JS to TS here where `codegen` fails.

**Comment by UnleashedMind** [comment]
you need to run `amplify codegen` again after you update it using `amplify codegen configure`

**Comment by sw-yx** [comment]
thanks. hmm. since that is a VERY likely next step after running configure, should we not offer to run amplify codegen for them or at least prompt?

**Comment by UnleashedMind** [comment]
I will mark this as an enhancement request then, the team will evaluate it.

**Comment by mogarick** [comment]
Hi @sw-yx @UnleashedMind. I'm having similar problems but with a slight difference. I don't know how but the coden gen generates .graphql files and I want TS ones. But trying to change that by issuing `amplify codegen configure` I get an error

``` 
? Choose the code generation language target typescript
? Enter the file name pattern of graphql queries, mutations and subscriptions src/graphql/**/*.ts
? Enter the file name for the generated code src/API.ts
? Enter maximum statement depth [increase from default if your schema is deeply nested] 2
Cannot read property 'replace' of null
```

When I say I don't know how is it generating .graphql files for queries, mutations, etc. is because my `.graphqlconfig.yml` is not configured to generate `.graphql` files. Here is my file

```
projects:
  anivettyapi:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
  excludes:
    - ./amplify/**
    - ./src/graphql/GraphQLAPIClientAwsAmplify.ts
    - ./src/graphql/GraphQLServiceSyncManager.ts
  extensions:
    amplify:
      codeGenTarget: typescript
      generatedFileName: src/API.ts
      docsFilePath: src/graphql
extensions:
  amplify:
    version: 3

```
Could this be related or should I open a new issue? 

Thank you in advance for your attention.
