### ISSUE TITLE
Getting error message `Cannot read property 'replace' of null` while executing `amplify codegen configure`

### ISSUE THREAD

**Issue by mogarick** [aws-amplify/amplify-cli#4924]
**Describe the bug**
For an unknown reason I'm getting `.graphql` files generated for queries, mutations and subscriptions even though I configured TypeScript as codegen output. (You can see my current file in the additional context section of this report)

I tried to execute `amplify codegen configure` to re state that I want the graphql operations to be generated as Typescript but I'm getting the next error:

```
Cannot read property 'replace' of null
```

Unfotunately that's all about the error. No stacktrace was output. Only the above message.

**Amplify CLI Version**
My amplify cli version is `4.13.14`.

**To Reproduce**
```
> amplify codegen configure
? Choose the code generation language target typescript
? Enter the file name pattern of graphql queries, mutations and subscriptions src/graphql/**/*.ts
? Enter the file name for the generated code src/API.ts
? Enter maximum statement depth [increase from default if your schema is deeply nested] 2
Cannot read property 'replace' of null
```

**Expected behavior**
I was expecting the command to execute successfully and Typescript files get generated.

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.6
 - Node Version. v12.16.3

**Additional context**
Heres my `.graphqlconfig.yml`:

```
projects:
  myamplifyapi:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
  excludes:
    - ./amplify/**
    - ./src/graphql/GraphQLAPIClientAwsAmplify.ts
    - ./src/graphql/GraphQLServiceSyncManager.ts
  extensions:
    amplify:
      codeGenTarget: typescript
      generatedFileName: src/API.ts
      docsFilePath: src/graphql
extensions:
  amplify:
    version: 3

```

I was advised by @sw-yx to file this as new issue. I originally reported the behavior in the issue #4858 because I though it could be related.

**Comment by mogarick** [comment]
May be the key is how did amplify got configured to generate mutations and queries as .graphql files. I created a new amplify project and tested with option typescript and it worked. it generates ts files. I then tried with another project to generate js files and it also worked. I both cases I also executed `amplify codegen configure` and there were no errors.

So I don't know how in heaven I ended up with a codegen config to generate .graphql files in the first term. And the problem is I can't run `amplify codegen configure` to change to typescript because I get the error mentioned in this issue.

**Comment by mogarick** [comment]
Hello @nikhname 
This is weird. 
After deleting the .yaml file and then running again `amplify codegen configure` it started the process from scratch and after that it correctly generated the ts files. It didn't generate the .graphql files anymore. 
This was the otuput
```
? Choose the code generation language target typescript
? Enter the file name pattern of graphql queries, mutations and subscriptions src/gr
aphql/**/*.ts
? Do you want to generate/update all possible GraphQL operations - queries, mutation
s and subscriptions Yes
? Enter maximum statement depth [increase from default if your schema is deeply nest
ed] 3
? Enter the file name for the generated code src/API.ts
? Do you want to generate code for your newly created GraphQL API Yes
✔ Generated GraphQL operations successfully and saved at src/graphql
✖ Could not parse graphql operations in src/graphql/GraphQLAPIClientAwsAmplify.ts
  Failed on : executeOperation
```
The last error was due to a couple of ts files included in the destination directory. I then added them to the exclude section.

This is the new yaml file generated:

```
projects:
  myamplifyapi:
    schemaPath: amplify/backend/api/myamplifyapi/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-west-2
        apiId: null
        maxDepth: 3
```

A curios note is that if I run `amplify codegen` after the initial configuration, the yaml is slightly changed to add a few extra lines:
```
projects:
  myamplifyapi:
    schemaPath: amplify/backend/api/myamplifyapi/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-west-2
        apiId: null
        maxDepth: 3
extensions:
  amplify:
    version: 3
```

Another thing to note is that the yaml now points to the `.graphql` schema file in the build directory and not to the `.json` one in the src directory as it was in the yaml file I deleted.

I think it is still necessary to trace both the reason why the operations files were generated as .graphql files and check about the lack of a full stack trace when the error occurred trying to execute `amplify codegen configure` when the .graphql files were being generated.

Thank you for the attention.
