### ISSUE TITLE
AWS Amplify npm install error

### ISSUE THREAD

**Issue by ardian-c** [aws-amplify/amplify-cli#5022]
Hi, 

After I created a new deployment for a `dev` branch, both the `dev` and `master` branch failed to build. The build settings are:

```
version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

The failure message is something like this: 
'@some-library' is not in the npm registry

AWS Amplify node/npm versions: 
node v10.16.0
npm  v6.9.0
