### ISSUE TITLE
`API.ts` always generated with no content

### ISSUE THREAD

**Issue by wmadden** [aws-amplify/amplify-cli#5226]
**Describe the bug**
`amplify codegen` generates an `API.ts` containing only comments. The full file content of `API.ts` is:

```ts
/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.
```

The following files are created and non-empty:

* `graphql/mutations.ts`
* `graphql/queries.ts`
* `graphql/subscriptions.ts`
* `aws-export.js`

**Amplify CLI Version**
4.28.1

**To Reproduce**
`.graphqlconfig.yml`:

```
projects:
  plantfriends:
    schemaPath: amplify/backend/api/project/build/schema.graphql
    includes:
      - web-client/src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: web-client/src/gen/API.ts
        docsFilePath: web-client/src/gen/graphql
        maxDepth: 2
extensions:
  amplify:
    version: 3
```

**Expected behavior**
I assume there should be some content in `API.ts`, based on tutorials and articles I've seen elsewhere. Also the TypeScript compiler refuses to compile it (with `--isolatedModules` enabled):

```
web-client/src/gen/API.ts
TypeScript error in ./web-client/src/gen/API.ts(1,1):
All files must be modules when the '--isolatedModules' flag is provided.  TS1208
```

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v14.5.0

**Additional context**

I'm running this command inside a Yarn monorepo. I had to install `@aws-amplify/cli` globally to get it to function at all.
