### ISSUE TITLE
Run amplify mock api on Amplify CI/CD

### ISSUE THREAD

**Issue by nathanqueija** [aws-amplify/amplify-cli#5314]
Hello there,

I'm using the command `amplify mock api` locally for my E2E tests and it works really well, but I'm wondering if it would be possible to add it to my CI/CD pipeline on Amplify.
I know that this command requires java and the build on Amplify runs on a predefined Docker image that doesn't include Java.
Would it be possible to include Java in the image or is there any workaround that can be done to achieve this result?

Thanks

**Comment by nathanqueija** [comment]
I managed to make it work by adding this line to amplify.yml:

`- amazon-linux-extras install java-openjdk11`

**Comment by nathanqueija** [comment]
It would be nice if Java could be added in the instance though since this is a command from the CLI and is quite useful for testing.

**Comment by alissaVrk** [comment]
can you please post the .yml file to mock api in the aws console?

**Comment by cwinters8** [comment]
I'm curious about this as well. I figured out installing the Java dependency (I used `yum install -y java-11-amazon-corretto-headless`) but I'm having trouble getting the mocking process to be sent to the background. I've tried `amplify mock api & npx wait-on http://localhost:20002` and `(amplify mock api &) && npx wait-on http://localhost:20002` but the session just hangs after the GraphQL schema compiles. I'd love to know how you were able to move past this issue @nathanqueija. Thanks in advance.

**Comment by cwinters8** [comment]
I was able to get this working successfully using a tool called [pm2](https://pm2.keymetrics.io/), which you just need to install globally from npm. @alissaVrk here's my amplify.yml which runs a successful build, test, and deploy.

```yaml
version: 1
backend:
  phases:
    preBuild:
      commands:
        - npm install -g @aws-amplify/cli
    build:
      commands:
        - amplifyPush --simple
test:
  phases:
    preTest:
      commands:
        - yum install -y java-11-amazon-corretto-headless
        - npm ci
        - npm install wait-on -g
        - npm install pm2 -g
        - npm install mocha mochawesome mochawesome-merge mochawesome-report-generator
        - pm2 start startMockApi.sh
        - wait-on http://localhost:20002
        - pm2 start npm -- start
        - wait-on http://localhost:3000
    test:
      commands:
        - 'CYPRESS_loginPassword=$CYPRESS_USER_PASS npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
        - npm test -- --watchAll=false
    postTest:
      commands:
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by alissaVrk** [comment]
thank you very much, will try 👍

**Comment by nathanqueija** [comment]
Hello @alissaVrk and @cwinters8 , so this is my build file:

```yml
version: 0.1
frontend:
  customHeaders:
    - pattern: "**/*"
      headers:
        - key: Strict-Transport-Security
          value: max-age=31536000; includeSubDomains
        - key: X-Frame-Options
          value: SAMEORIGIN
        - key: X-XSS-Protection
          value: 1; mode=block
        - key: X-Content-Type-Options
          value: nosniff
  phases:
    preBuild:
      commands:
        - nvm install 10.18.1
        - yarn prebuild
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: /dist
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
test:
  artifacts:
    baseDirectory: cypress
    configFilePath: "**/mochawesome.json"
    files:
      - "**/*.png"
      - "**/*.mp4"
  phases:
    preTest:
      commands:
        - nvm install 10.18.1
        - amazon-linux-extras install java-openjdk11
        - java -version
        - echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p
        - wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
        - yum install -y ./google-chrome-stable_current_*.rpm
        - yarn add mocha@5.2.0 mochawesome mochawesome-merge mochawesome-report-generator
    test:
      commands:
        - yarn run test:e2e
    postTest:
      commands:
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json

backend:
  phases:
    build:
      commands:
        - "# Execute Amplify CLI with the helper script"
        - amplifyPush --simple
```

After everything is set up I run this command from my `package.json` file: 

`"test:e2e": "/bin/bash ./scripts/e2e.sh"` and this is the content from the shell file:

```bash
npm install -g @aws-amplify/cli
yarn kill-amplify-mock-api
yarn kill-port 8080
(yarn start:server:e2e &)
(amplify mock api &)
yarn wait-on http-get://localhost:20002
yarn wait-on http-get://localhost:8080
cypress run --record --headless --browser chrome --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"
```

Here are some of the npm scripts that I also run during this process:

```bash
     "mock:api": "yarn kill-amplify-mock-api && amplify mock api",
    "kill-amplify-mock-api": "kill-port 20002 && kill-port 20003",
    "test:e2e": "/bin/bash ./scripts/e2e.sh",
    "start:server:e2e": "yarn build && yarn serve",
    "serve": "yarn kill-port 8080 && serve e2e_dist -p 8080 -s"```

Basically, the process is:
- Kill any instances of the mock server
- Start the mock server
- Build the application and wait until it's available
- Run the E2E tests

Let me know if I can help with anything else. Happy to have a chat and share further how the whole process looks like.
