### ISSUE TITLE
How to pass parameters to the typescript generated subscription?

### ISSUE THREAD

**Issue by pauldendulk** [aws-amplify/amplify-cli#5355]
**Which Category is your question related to?**
amplify codegene for appsync typescript/angular

**Amplify CLI Version** 
4.27.3

**What AWS Services are you utilizing?**
AppSync with DynamoDB datasource

**Details and code snippets**
- Created a DynameDB table called HeroTournament with and 'Id' primary partition key and no further configuration.
- Created an appsync schema from that table.
- Used ```amplify codegen``` to generate typescipt code.

The queries and mutations are easily usable. It is however not clear to me how to pass parameters to the subscription. Without parameters the subscription does not work, as expected. I can remove the '($Id: String)' from the generated code and it works, but for all possible changes. I can write my own method that does pass the input parameter but I assume that the default generated method should be usable as well. How?

The generated subscription:
```typescript
  OnCreateHeroTournamentListener: Observable<
    OnCreateHeroTournamentSubscription
  > = API.graphql(
    graphqlOperation(
      `subscription OnCreateHeroTournament($Id: String) {
        onCreateHeroTournament(Id: $Id) {
          __typename
          Id
        }
      }`
    )
  ) as Observable<OnCreateHeroTournamentSubscription>;
```

**Comment by UnleashedMind** [comment]
Subscriptions are used to receive mutation events, they are "attached" to certain mutations, whenever those mutations are executed, the subscribers receives the notifications. In the Amplify CLI compiled schema, they generally do not take parameters, you can add your filter logic on the client side.
You can see the Subscription type definition in the compiled schema `amplify/backend/api/<api-resource-name>/build/schema.graphql`
The directive @auth can be used to restrict who can receive certain subscriptions. (see the [document](https://docs.amplify.aws/cli/graphql-transformer/directives#authorizing-subscriptions) here)
For example, if the @auth(rules: [{allow: owner}]) is added on a type, you will see the compiled schema has the (owner: String!) parameter in the subscriptions.

**Comment by UnleashedMind** [comment]
closing the issue for now.
Feel free to open new issues if needed.

**Comment by pauldendulk** [comment]
> Subscriptions are used to receive mutation events, they are "attached" to certain mutations, whenever those mutations are executed, the subscribers receive the notifications. In the Amplify CLI compiled schema, they generally do not take parameters, you can add your filter logic on the client side.

It is not possible to receive notifications with the generated subscription method because the statement expects a parameter: 
> subscription OnCreateHeroTournament **($Id: String)**

The subscription fails because that parameter is not passed in. I have to remove the '($Id: String)' manually to receive any notifications at all.

Also, I have no 'schema.graphql' file at this location amplify/backend/api/<api-resource-name>/build/schema.graphql. There is no api folder in amplify/backend. Is there something wrong with the way I generate my code? Perhaps some of my configuration is wrong or outdated?

This is my graphqlconfig.yml:

```yaml
projects:
  Heros:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/API.service.ts
        docsFilePath: src/graphql
        region: eu-central-1
        apiId: adfadfadfasdfasdfasdfasdfasdfasd
        maxDepth: 4
extensions:
  amplify:
    version: 3
```
