### ISSUE TITLE
add option to set name of the template literal tag to `amplify codegen`

### ISSUE THREAD

**Issue by ygkn** [aws-amplify/amplify-cli#5442]
**Is your feature request related to a problem? Please describe.**

I wrote the GraphQL code because the generated queries, mutations, and subscriptions have the limitation that the depth cannot be changed one by one.

To generate the variables and response types for that code, I added `src/**/*.ts` and` src/**/*.tsx` to the `includes` in `.graphqlconfig.yml`.

```yml
...
    schemaPath: amplify/backend/api/<API_NAME>/build/schema.graphql
    includes:
      - src/**/*.ts
      - src/**/*.tsx
    excludes:
      - ./amplify/**
    extensions:
...
```

And I run `graphql codegen`, I get the following error:
```
$ amplify codegen                 
✔ Generated GraphQL operations successfully and saved at src/graphql
✖ Could not parse graphql operations in src/components/ButtonLink.tsx
  Failed on : appearance-none inline-block px-10 py-3 rounded-full text-center whitespace-no-wrap
```

This is because template string literals that are not GraphQL code are recognized as GraphQL code.

**Describe the solution you'd like**
To avoid this, I need the `tagName` option to set a tag or magic comment to distinguish between template string literals in GraphQL code and others.

[This option exists as a `tagName` argument in the` generate` function of graphql-types-generator](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-graphql-types-generator/src/generate.ts#L27), but [has been forced to `''` by amplify-codegen](https://github.com/aws-amplify/amplify-cli/blob/00c6ad8ebb9c12d77eb59b0564bc0b1b682358a7/packages/amplify-codegen/src/commands/types.js#L64).

I need this option in a config file such as `.graphqlconfig.yml`.

Please let me know if there is any other way I can type variables and responses in my GraphQL code.
