### ISSUE TITLE
Get the introspection schema with amplify pull (without pulling the backend ressources)

### ISSUE THREAD

**Issue by alexboulay** [aws-amplify/amplify-cli#5445]
**Is your feature request related to a problem? Please describe.**
When a front-end engineer wants to use a GraphQL API, he will pull the Amplify project to access it. He does not have the intention of modifying the APIs or Functions within that Amplify project. However, he wants to use `amplify codegen` which would require to download the introspective schema from the AppSync console. Not a very nice workflow since he want's to regenerate his code as soon as there is new stuff added to the API. 

**Describe the solution you'd like**
It would be nice to be able to do `amplify codegen`, without having to download the introspective schema manually. The current solution is to pull the backend by saying "yes" when prompted by the CLI to this question "Do you plan on modifying this backend?". Maybe, another question would be, would you like to pull the introspective schema?

**Comment by nikhname** [comment]
Hi @alexboulay, we support the use case of automatically downloading the introspection schema for codegen by using ```amplify codegen --apiId XXXXX```, where --apiID is the unique AppSync identifier for your API (https://docs.amplify.aws/lib/graphqlapi/query-data/q/platform/js#using-aws-appsync-sdk).
If you are using codegen in an uninitialized project you will still need to manually download the introspection schema.

**Comment by alexboulay** [comment]
When you say "uninitialized project", do you mean a project that's been pulled without the backend? Because my goal is to simply run `amplify pull` then `amplify codegen`. If I pull the amplify project, logically, the CLI should know what API i am referring to

**Comment by nikhname** [comment]
By uninitialized project we mean a project where ```init``` or ```pull``` has not been executed. It would make sense for codegen to automatically determine the apiId and download the introspection schema after a question so I am marking this as an enhancement.

**Comment by alexboulay** [comment]
Sweet. In the meantime, I tried your suggestion. It seems that within my project where I have pulled an existing project(without pulling back end ressources), I run `amplify codegen --appId XXXX`. I get the following output: `Please download the schema.graphql or schema.json` From what you said, I don't think this is normal behaviour.

**Comment by themse** [comment]
Any updates? How can we download the introspection schema. @nikhname, unfortunately your explanation doesn't work. And codegen isn't perfect (especially models and types). Don't you think about cooperation with [graphql-codegen team](https://www.graphql-code-generator.com/)? Their codegen is perfect. They generate hooks and it helps to avoid code duplication all the time and keep strict typing.

**Comment by themse** [comment]
@alexboulay I've found the way how to workaround this issue.  It's not the best solution, but better than nothing
```
aws appsync get-introspection-schema --api-id=XXX --format=JSON schema.json --profile=XXX
amplify codegen --apiId=XXX
```
and `.graphqlconfig.yml`
```
projects:
  yourProjectName:
    schemaPath: schema.json
    includes:
      - src/services/amplify/generated/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/services/amplify/generated/base-types.ts
        docsFilePath: /src/services/amplify/generated
        region: us-west-2
        apiId: XXX
        maxDepth: 5
extensions:
  amplify:
    version: 3
```
