### ISSUE TITLE
Bug in Angular codegen for GraphQL API subscriptions 

### ISSUE THREAD

**Issue by danyuep** [aws-amplify/amplify-cli#5749]
**Describe the bug**
I'm just getting started with AWS and am currently setting up an angular project that makes use of the 'APIService', which is code-generated by the Amplify cli from my local schema.graphql file.
Im an trying to use the APIService to subscribe to the creation of a new database obj (i.e. 'Country').

Generated code:
```
  OnCreateCountryListener: Observable<
    OnCreateCountrySubscription
  > = API.graphql(
    graphqlOperation(
      `subscription OnCreateCountry {
        onCreateCountry {
          __typename
          id
          name {
            __typename
            value
            languageCode
          }
          createdAt
          updatedAt
        }
      }`
    )
  ) as Observable<OnCreateCountrySubscription>;

...

export type OnCreateCountrySubscription = {
  __typename: "Country";
  id: string;
  name: Array<{
    __typename: "MultiLangInfo";
    value: string;
    languageCode: LanguageCode;
  } | null> | null;
  createdAt: string;
  updatedAt: string;
};
```

My issue is, that when I subscribe to the generated subsription method, incoming events are expected to be of type 'OnCreateCountrySubscription'. However, when I try to access for example the property 'name', it results as undefined.
By logging the incoming event I noticed that the object is structured as follows:

Google Chrome console output:
```
{provider: AWSAppSyncRealTimeProvider, value: {…}}
  provider: AWSAppSyncRealTimeProvider {_config: {…}, socketStatus: 1, keepAliveTimeout: 300000, subscriptionObserverMap: 
  Map(2), promiseArray: Array(0), …}
    value:
      data:
        onCreateCountry:
          createdAt: "2020-10-31T12:48:10.879Z"
          id: "00a86220-4d62-4746-b6c0-7f24d64c85d5"
          name: [{…}]
          updatedAt: "2020-10-31T12:48:10.879Z"
__typename: "Country"
__proto__: Object
__proto__: Object
__proto__: Object
__proto__: Object
```

When I access the object as follows: 
```
APIService.OnCreateCountryListener(c: OnCreateCountrySubscription  => {
  const createdCountry = c .value.data.onCreateCountry;
  // those properties do not exist on the type  'OnCreateCountrySubscription' 
  // -> results in TSError
}
```
... I get the object in a structure as it would be expected from the type 'OnCreateCountrySubscription' itself. But obviously the typescript compiler sees this as an error.

For me it seems like the type conversion for incoming events is not set up properly in the code generator.

**Amplify CLI Version**
4.32.0

**To Reproduce**
GraphQL schema that is used by the angular code generator:
```
enum LanguageCode {
  DE
  EN
}

type Country @model {
  id: ID!
  name: [MultiLangInfo]
}

type MultiLangInfo {
  value: String!
  languageCode: LanguageCode!
}
```

**Expected behavior**
Incoming events are epxtected to actually be of type 'OnCreateCountrySubscription'.

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version v12.19.0

**Additional context**
