### ISSUE TITLE
Changing Auth 'parameters.json' and 'template.yml' fails

### ISSUE THREAD

**Issue by xitanggg** [aws-amplify/amplify-cli#5761]
**Which Category is your question related to?**
Auth

**Amplify CLI Version** 
4.32.0

**What AWS Services are you utilizing?**
AWS Cognito

**Provide additional details e.g. code snippets**
Hi, I am adding Auth with `amplify auth add`. The default Auth created by Amplify uses case sensitive username. For example, if email is used as username alias, hi@gmail.com and HI@gmail.com would be treated as two different usernames, which is not what most people wanted (This has been brought up before #4185 and remains unresolved). 

With the old version of Amplify CLI, we can modify the Auth Cloudformation Template directly by adding [UsernameConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-usernameconfiguration.html) to enable case insensitivity. (As mentioned in #3494)
```yml
  UsernameConfiguration:
    CaseSensitive: false
```

However, with the new CLI that creates two files `parameters.json` and `xxx-cloudformation-template.yml`, I am confused as to where to add this.

In `parameters.json`, I had tried `"usernameConfiguration": {"CaseSensitive": false}` or `"usernameConfiguration": "{\n  \"CaseSensitive\": false \n}"`. 

In `xxx-cloudformation-template.yml`, I added
```yml
Parameters:
  (...skip)
  usernameConfiguration:
    Type: String

Resources:
  (...skip)
  UserPool:
    (...skip)
    Properties:
      UsernameConfiguration: !Ref usernameConfiguration
```
but I received the error `Property validation failure: [Value UsernameConfiguration} does not match type {Object}]` when I do `amplify push`. I would appreciate any helps to resolve this. Thanks.

**Comment by xitanggg** [comment]
Sorry, I had a brain fart. 

Basically, simply add it to `xxx-cloudformation-template.yml` solves it. No need to touch `parameters.json`
```yml
Parameters:
  (...skip)
  usernameConfiguration:
    Type: String

Resources:
  (...skip)
  UserPool:
    (...skip)
    Properties:
      UsernameConfiguration:
        CaseSensitive: false
```
