### ISSUE TITLE
amplifyPush results in Fn::GetAtt references undefined resource

### ISSUE THREAD

**Issue by adamMo** [aws-amplify/amplify-cli#5791]
**Which Category is your question related to?**
question

**Amplify CLI Version** 
4.32.0

**What AWS Services are you utilizing?**
Amplify, Cognito

Hello, 
I recently tried to create an Amplify app. I configured Cognito a moment before and connected to it using `amplify auth import` - tested locally and works fine. I wanted to use CICD on Amplify and deploy the project but when I call `amplifyPush -e dev` I keep getting ` 'Template error: instance of Fn::GetAtt references undefined resource authmyappb0dd2e14'`

My amplify.yml looks like: 
```
version: 1
frontend:
  phases:
    build:
      commands:
        - '# Get Amplify CLI Cloud-Formation stack info from environment cache'
        - export STACKINFO="$(envCache --get stackInfo)"
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush -e dev
        - '# Store Amplify CLI Cloud-Formation stack info in environment cache'
        - envCache --set stackInfo "$(amplify env get --json --name dev)"
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
In my project there is generated `amplify/backend/backend-config.json` that contains:
```
{
  "auth": {
    "myappb0dd2e14": {
      "service": "Cognito",
      "serviceType": "imported",
      "providerPlugin": "awscloudformation",
      "dependsOn": [],
      "customAuth": false
    }
  }
}
```
