### ISSUE TITLE
JSONValidationError: File project: data should NOT have additional properties: 'graphqltransformer'

### ISSUE THREAD

**Issue by vikrantRajan** [aws-amplify/amplify-cli#6117]
**Which Category is your question related to?**
Amplify, Cognito

**Amplify CLI Version** 
Amplify CLI is 4.38.0.

**What AWS Services are you utilizing?**
Amplify, Cognito

**Provide additional details e.g. code snippets**
I get the following error in the amplify console during the CI/CD build

I am not sure how to get the version for the backend build CI/CD. 
I ran these commands
```
npm install -g @aws-amplify/cli@latest
amplify configure
amplify init
npm i @aws-amplify/ui-vue
```

added the following the main.js file (I am using Vue.js for frontend)
```
import Amplify, { Auth } from 'aws-amplify';
import awsconfig from './aws-exports';
Amplify.configure(awsconfig);
```

added the following UI components from the auth
```
<template>
  <amplify-authenticator>
    <div>
      My App
      <amplify-sign-out></amplify-sign-out>
    </div>
  </amplify-authenticator>
</template>
```

checked out to my dev env
removed my previous auth in dev 
then added a fresh auth with default settings for dev
pushed 
```
amplify env checkout dev [--restore]
amplify remove auth
amplify add auth
amplify push
```

I have a prod env as well and did the same steps for that, but for now, I am testing just the dev branch.
I pushed my code to bitbucket and amplify starts provisioning the backend but the build fails. 

There are the settings I found in the amplify/.config/project-config.json

```
{
  "projectName": "MemberPlatform3",
  "version": "3.0",
  "frontend": "javascript",
  "javascript": {
    "framework": "vue",
    "config": {
      "SourceDir": "src",
      "DistributionDir": "dist",
      "BuildCommand": "npm run build",
      "StartCommand": "npm run serve"
    }
  },
  "providers": [
    "awscloudformation"
  ]
}
```

These are the settings I found in amplify/team-provider-info.json (the auth data comes from the .yml files located in amplify/backend/auth/memberplatform3376d2675.yml)
```
{
  "dev": {
    "awscloudformation": {
      "AuthRoleName": "xxxxxxxxxxxxxxxxx",
      "UnauthRoleArn": "xxxxxxxxxxxxxxxxx",
      "AuthRoleArn": "xxxxxxxxxxxxxxxxx",
      "Region": "us-west-2",
      "DeploymentBucketName": "xxxxxxxxxxxxxxxxx",
      "UnauthRoleName": "xxxxxxxxxxxxxxxxx",
      "StackName": "xxxxxxxxxxxxxxxxx",
      "StackId": "xxxxxxxxxxxxxxxxx",      
      "AmplifyAppId": "xxxxxxxxxxxxxxxxx"
    },
    "categories": {
      "auth": {
        "memberplatform3376d2675": {}
       }
     }
   },
"prod": {
    // same as above with unique values
    },
    "categories": {
      "auth": {
        "memberplatform36eeced50": {}
       }
     }
   },
}
```

This is in the amplify/cli.json
```
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": false,
      "enableiterativegsiupdates": false
    }
  }
}
```

Here are my build settings
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush -e $AWS_BRANCH --simple

```

But as you can see in this image from the AWS Amplify Console, any command associated with amplify is failing. I am not sure if I am missing some kind of configuration. 

Please help, as I have been trying to figure this out for almost a week now.

<img width="1040" alt="Screen Shot 2020-12-08 at 4 13 10 PM" src="https://user-images.githubusercontent.com/48606890/101556694-46b01f80-3970-11eb-9a01-8469cdc571cc.png">
