### ISSUE TITLE
The CLI can not grant access to the preSignUp trigger to use the user pool

### ISSUE THREAD

**Issue by ignaciolarranaga** [aws-amplify/amplify-cli#6171]
**Describe the bug**
If you want to access the Cognito user pool inside the preSignUp trigger you must be able to grant permissions, but this is not possible due a cyclic dependency. Specifically:
```
ignacio@MacBook % amplify update function
? Select which capability you want to update: Lambda function (serverless function)
? Select the Lambda function you want to update samplePreSignup
General information
| Name: samplePreSignup
| Runtime: nodejs

Resource access permission
- Not configured

Scheduled recurring invocation
| Not configured

Lambda layers
- Not configured

? Which setting do you want to update? Resource access permissions
? Select the category auth
Auth category has a resource called sample
? Select the operations you want to permit for sample read

You can access the following resource attributes as environment variables from your Lambda function
        AUTH_SAMPLE_USERPOOLID
Error: Cannot add samplePreSignup due to a cyclic dependency
    at checkForCyclicDependencies (/Users/ignacio/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/update-amplify-meta.js:199:15)
    at AmplifyToolkit.updateamplifyMetaAfterResourceUpdate [as _updateamplifyMetaAfterResourceUpdate] (/Users/ignacio/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/update-amplify-meta.js:116:9)
    at updateFunctionResource (/Users/ignacio/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/index.js:144:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.executeAmplifyCommand (/Users/ignacio/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/index.js:195:5)
    at async executePluginModuleCommand (/Users/ignacio/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:166:5)
    at async Object.executeCommand (/Users/ignacio/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/Users/ignacio/.nvm/versions/node/v12.16.1/lib/node_modules/@aws-amplify/cli/lib/index.js:91:9)
There was an error adding the function resource
```

Indeed it is a common kind of check (for example in my case I'm trying to verify that the phone numbers do not repeat).

**Amplify CLI Version**
4.39.0

**To Reproduce**
1. Add authentication
2. Add a preSignUp trigger
3. `amplify update function` trying to grant access to the user pool

**Expected behavior**
The permission should be possible to be added (or directly created when adding the trigger).

**Additional context**
In [here](https://dev.to/andthensumm/enforcing-attribute-uniqueness-in-cognito-with-aws-amplify-and-react-263f) you can see an example of doing almost the same manually

**Comment by ignaciolarranaga** [comment]
I did manage to resolve the issue with this work-around in the auth cloud-formation template:
```
  UserPoolPreSignupLambdaPolicy:
  # Sets the PreSignup Lambda permissions to read the pool
  # Depends on UserPool for Arn
    Type: 'AWS::IAM::Policy'
    DependsOn: UserPool
    Properties:
      PolicyName: sample89867100_userpoolclient_preSignUplambda_policy
      Roles: 
        - !Ref functionsamplePreSignupName 
        #- !Ref functionsamplePreSignupLambdaExecutionRole 
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'cognito-idp:ListUsers'
            Resource: !GetAtt UserPool.Arn
```

Despite all my attempts though, I wasn't able to inject the execution role (i.e.: `functionsamplePreSignupLambdaExecutionRole`).
I added the parameter:
```
  functionsamplePreSignupLambdaExecutionRole:
    Type: String
    Default: functionsamplePreSignupLambdaExecutionRole
```
And changed the parameters.json of the auth:
```
"dependsOn": [
        {
            "category": "function",
            "resourceName": "samplePreSignup",
            "triggerProvider": "Cognito",
            "attributes": [
                "Arn",
                "Name",
                "LambdaExecutionRole"
            ]
        }
    ],
```

But the parameter does not reach the template and it fails on deploy.
