### ISSUE TITLE
Prettier deleting "repeatable" word on custom directive

### ISSUE THREAD

**Issue by half2me** [aws-amplify/amplify-cli#6177]
**Describe the bug**
I'm really not sure if I need to report this to prettier or here, but since amplify-cli also uses prettier, I figured its worth a shot.
Its a very strange behaviour. I have the following code:
```js
import { gql } from 'graphql-transformer-core'

let a = gql`
  directive @foo repeatable on FIELD_DEFINITION
`
```

When I run prettier, it removes `repeatable`, to leave this:
```js
import { gql } from 'graphql-transformer-core'

let a = gql`
  directive @foo on FIELD_DEFINITION
`
```

I've worked around it by adding `// prettier-ignore`, but its the strangest thing, and I can't figure out why its happening.

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. v12.20.0
- Visual Studio Code with prettier plugin, auto format on save.

**Additional context**
My `.prettierrc.yaml`:
```yaml
trailingComma: all
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
quoteProps: as-needed
bracketSpacing: true
printWidth: 120
```
