### ISSUE TITLE
Parameter 'X' must be one of AllowedValues

### ISSUE THREAD

**Issue by stleon** [aws-amplify/amplify-cli#6224]
**Describe the bug**

Seems like paremeters from paremeters.json are not passed to the cloudformation template.

**Amplify CLI Version**
4.40.0

**To Reproduce**
I want to use [Custom CloudFormation stacks](https://docs.amplify.aws/cli/usage/customcf).

parameters.json:

```
{
    "X": "Yes"
}
```

category-cloudformation-template.yaml:

```
Parameters:
  env:
    Description:  the env parameter will be passed in to your cloudformation templates dynamically by the CLI
    Type: String

  X:
    Description: some description
    Type: String
    Default: No
    AllowedValues:
      - Yes
      - No
...
```

Then I run:

```
$ amplify env checkout dev
$ amplify push -y
```

And I have error:

```
CREATE_FAILED      xxxx          AWS::CloudFormation::Stack Sun Dec 20 2020 15:24:00 GMT+0300  Parameter 'X' must be one of AllowedValues
```

**Expected behavior**
Successful adding of custom CloudFormation stack.

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v15.3.0
