### ISSUE TITLE
[codegen] graphql config - multiple extension outputs from a project

### ISSUE THREAD

**Issue by uncodable** [aws-amplify/amplify-cli#6291]
**Is your feature request related to a problem? Please describe.**
I want to output typescript types to lambda functions as well as my frontend application also.

**Describe the solution you'd like**
The ability to have many extensions with the same key as `amplify` within the same project:
```yml
projects:
  Workspaces:
    schemaPath: src/graphql/Workspaces/schema.json
    includes:
      - src/graphql/Workspaces/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/utils/API.ts
        docsFilePath: src/graphql/Workspaces
        maxDepth: 2
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/backend/foobar/API.ts
        docsFilePath: amplify/backend/foobar
        maxDepth: 2
extensions:
  amplify:
    version: 3
```

**Describe alternatives you've considered**
Having a folder in the root directory to allow types to be read from there, however it's not easy and requires extra permissions and npm won't let you read outside the main dir it's being ran from. So this will be an issue for lambda functions.

**Comment by uncodable** [comment]
**Alternative solution**
This would work a better way instead of executing the extension many times;
```yml
projects:
  Workspaces:
    schemaPath: src/graphql/Workspaces/schema.json
    includes:
      - src/graphql/Workspaces/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFiles: 
          - src/utils/API.ts
          - amplify/backend/API.ts
        docsFilePaths:
          - src/graphql/Workspaces
          - amplify/backend/Workspaces
        maxDepth: 2
extensions:
  amplify:
    version: 3
```
