### ISSUE TITLE
Better defaults for .graphqlconfig.yml

### ISSUE THREAD

**Issue by dopry** [aws-amplify/amplify-cli#6366]
**Is your feature request related to a problem? Please describe.**
Amplify codegen dumps it's graphql all over the place like an itinerant toddler. 

**Describe the solution you'd like**
Dump all the generated code for an api in a folder named for the API

```
projects:
  {ApiName}:
    schemaPath: src/{ApiName}/schema.json
    includes:
      - src/{ApiName}/**/*.ts
    excludes:
      - ./amplify/**
      - src/{ApiName}/types.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/{ApiName}/types.ts
        docsFilePath: src/{ApiName}
extensions:
  amplify:
    version: 3
```
