### ISSUE TITLE
Cannot read property 'region' of undefined when running amplify env pull --yes

### ISSUE THREAD

**Issue by mansdahlstrom1** [aws-amplify/amplify-cli#6424]
> **Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the
> [Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Error `Cannot read property 'region' of undefined` when running `amplify env pull --yes`. 

Output from GitHub Actions

``` 
Initializing new Amplify CLI version...
Done initializing new version.
Scanning for plugins...
Plugin scan successful
- Fetching updates to backend environment: stage from the cloud.
✔ Successfully pulled backend environment stage from the cloud.
✖ There was an error initializing your environment.
Cannot read property 'region' of undefined
TypeError: Cannot read property 'region' of undefined
    at Object.getConfiguredPinpointClient (/Users/runner/hostedtoolcache/node/12.20.1/x64/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-pinpoint.js:45:35)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.pullAllChannels (/Users/runner/hostedtoolcache/node/12.20.1/x64/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-notifications/lib/notifications-manager.js:86:36)
    at constructPinpointNotificationsMeta (/Users/runner/hostedtoolcache/node/12.20.1/x64/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-notifications/lib/multi-env-manager.js:78:7)
    at Object.initEnv (/Users/runner/hostedtoolcache/node/12.20.1/x64/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-notifications/lib/multi-env-manager.js:8:37)
    at initEnv (/Users/runner/hostedtoolcache/node/12.20.1/x64/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-notifications/index.js:16:3)

```

**Amplify CLI Version**
@aws-amplify/cli@4.41.2

**To Reproduce**

1. take working amplify repo (note this repo in question has the amplify project folder in a subdirectory called `mobile`)
2. Deploy a new env and make sure it works (Analytics and notifications needs to be setup)
3. Add following workflow to GitHub Actions ( change the env name in the workflow to match your env name)
4. Make sure all the secret are in place (or just replace with hardcoded AWS Keys)

```
name: CI
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:        
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 12
   
      - run: npm install -g @aws-amplify/cli

      - name: configure amplify
        working-directory: ./mobile
        run: |
          echo '{"projectPath": "'"$(pwd)"'","defaultEditor":"code","envName":"stage"}' > ./amplify/.config/local-env-info.json
          amplify env pull --yes  
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          AWS_REGION: 'eu-west-1'
          
      - name: install
        run: |
          cd mobile
          npm install
```

2. Run the CI vai Github action or via a push to master branch.

**Expected behavior**
Amplify env should be succefully setup

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Mac/Windows/Ubuntu]
**GitHub CI**
- Node Version. You can use `node -v` to check the node version on your system
**Node 12**

**Log output**
Include any relevant log output under `~/.amplify/logs/amplify-cli-<issue-date>.log`

**Additional context**
Had another problem with the same flow before that i solved and commented on here: https://github.com/aws-amplify/amplify-cli/issues/4005#issuecomment-762849484
