### ISSUE TITLE
No such resource AWS::Events::EventBus

### ISSUE THREAD

**Issue by absynthe** [aws-amplify/amplify-cli#6440]
> **Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the
> [Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Added a custom cloud formation to my project with an EventBus, for which I want to expose the ARN as output. If I upload the same template to CloudFormation it just works. 

**Amplify CLI Version**
`4.41.2` 

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

1. Init a new project with Amplify CLI
2. Add the following to your `backend-config.json`:

```
  "orchestration": {
    "testHarnessEventBus": {
      "providerPlugin": "awscloudformation",
      "service": "EventBridge"
    }
```
3. Under backend folder create an orchestration/testHarnessEventBus folder and add the following in `template.yml`:
```
AWSTemplateFormatVersion: "2010-09-09"
Description: Creates an event bus for the application
Parameters:
  env:
    Type: String
Resources:
  TestHarnessEventBus:
    Type: AWS::Events::EventBus
    Properties: 
      Name: !Join ['-',['TestHarnessEventBus',!Ref env]]
Outputs:
  EventBusArn:
    Value: !GetAtt TestHarnessEventBus.Arn
    Description: ARN of the Event Bus
```
4. Under the same folder create `parameters.json` with content `{}`

**Expected behavior**
Amplify CLI should not throw an error for a valid get attribute call.

**Screenshots**
Here is console dump:
```
amplify push
✔ Successfully pulled backend environment dev from the cloud.

Current Environment: dev

| Category      | Resource name             | Operation | Provider plugin   |
| ------------- | ------------------------- | --------- | ----------------- |
| Function      | validationTestListener    | Update    | awscloudformation |
| Orchestration | testHarnessEventBus       | Update    | awscloudformation |
| Auth          | kendratestharness61c8e6e2 | No Change | awscloudformation |
| Api           | KendraTestHarness         | No Change | awscloudformation |
| Function      | getKendraIndices          | No Change | awscloudformation |
? Are you sure you want to continue? Yes
Invalid CloudFormation template: /.../amplify/backend/orchestration/testHarnessEventBus/template.yml
No such resource AWS::Events::EventBus
```

**Desktop (please complete the following information):**

- OS: Mac
- Node Version. v13.11.0
