### ISSUE TITLE
Command 'amplify add codegen' don't follow configuration

### ISSUE THREAD

**Issue by pippo111** [aws-amplify/amplify-cli#6468]
**Describe the bug**
When setting up `codegen` described here: https://docs.amplify.aws/cli/graphql-transformer/codegen#workflows generated code is placed under different directory than pointed.

**Amplify CLI Version**
4.41.2

**To Reproduce**
1. Create and configure AppSync graphql schema
2. Export `schema.json` to your project directory
3. Run `amplify add codegen`
4. Enter this configuration:
```
amplify add codegen
? Choose the type of app that you're building javascript
? What javascript framework are you using react
? Choose the code generation language target typescript
? Enter the file name pattern of graphql queries, mutations and subscriptions aws/graphql/**/*.ts
? Do you want to generate/update all possible GraphQL operations - queries, mutations and subscriptions Yes
? Enter maximum statement depth [increase from default if your schema is deeply nested] 2
? Enter the file name for the generated code aws/API.ts
? Do you want to generate code for your newly created GraphQL API Yes
✔ Generated GraphQL operations successfully and saved at src/graphql
✔ Code generated successfully and saved in file aws/API.ts
```

**Expected behavior**
Generated GraphQL operations should be saved into `aws/graphql`

**Actual behavior**
Generated GraphQL operations should be saved into `src/graphql`

**Desktop (please complete the following information):**

- OS: Linux Manjaro
- Node Version. v12.20.1

**Log output**
```
2021-01-24T09:47:40.071Z|info : amplify version core  {"version":true,"yes":false}
2021-01-24T09:48:10.804Z|info : amplify add codegen
```

**Comment by AaronZyLee** [comment]
Thanks for reporting the bug. I am able to reproduce this issue. This is due to a bug in the codegen question walk-through. I will submit a PR soon to fix it. Before the fixing, there is also a temporary solution for your case. In the directory where you run  `amplify codegen add`, you will find a file called `.graphqlconfig.yml`. This is the config file right after you first run `amplify codegen add`. The only thing need to be changed is the `extensions.amplify.docsFilePath` field. I attach my code snippet below FYI. 
```Yaml
projects:
  test:
    schemaPath: amplify/backend/api/test/build/schema.graphql
    includes:
      - aws/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: aws/API.ts
        docsFilePath: aws/graphql  #The field is not configured correctly and needs to be changed
        region: us-west-2
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
```
