### ISSUE TITLE
Not authorized to access 'nextToken' or 'items' fields on a @connection field type when running the Create() mutation

### ISSUE THREAD

**Issue by dorontal** [aws-amplify/amplify-cli#6501]
**Describe the bug**

Using a schema where one (parent) model's field has a `@connection` to another model (child model), the Create mutation returns errors, specifically: it can create the parent model, but it complains about not being able to access either the
`nextToken` field or the `items` field of the connection type of its child `@connection` model field.

**Amplify CLI Version**

4.41.2

**To Reproduce**

1. Create a schema with a "has many" ("one-to-many") connection like this one:
  ```graphql
  type Track
    @model(subscriptions: null)
    @auth(
      rules: [
        { allow: owner, operations: [create, update, delete] },
        { allow: public, provider: iam, operations: [read] }
      ]
    )
    @key(
      name: "byFolderIdCreatedAt",
      fields: ["folderId", "createdAt"],
      queryField: "tracksByFolderId"
    ) {
    id: ID!
    name: String!
    folderId: ID
  }

  type Folder
    @model(subscriptions: null)
    @auth(
      rules: [
        { allow: owner, operations: [create, update, delete] },
        { allow: public, provider: iam, operations: [read] }
      ]
    ) {
    id: ID!
    name: String!
    tracks: [Track] @connection(keyName: "byFolderIdCreatedAt", fields: ["id"])
  }
  ```
2. Auto-generate Javascript code for queries and mutations via an Amplify cli push.
3. Try to use the auto-generated function (which just calls the GraphQL mutation) `CreateFolder()` as in this example that created the error from my code (the first call to `Amplify.configure()` ensures you are using COGNITO for authentication). Before this code runs, make sure the user running it is signed in to Cognito:
   ```typescript
   Amplify.configure({
     aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS'
   });

   this.awsAPI.CreateFolder({
       name: 'test'
   }).catch((err: Error) => {
       console.log('errrrrrr', err);
   })
   ```

**Expected behavior**

Expected the above to work with no errors, as it is a fairly straightforward use case! Instead, here is the printed out value of `err` in the  `catch()` block above, seen in the browser's dev console:

[ NOTE: the above call to `CreateFolder()` is here only to demonstrate the problem and has been simplified; originally there was a `then` clause there but since we get an error in this call the `then` clause never got executed so it is not shown. If this issue reported here did not exist, you'd be relying on the `then` block instead of the `catch` block to get your created folder data. The `catch` block above is actually also the current workaround (!), because when this error is thrown, the folder still gets created and its data is returned to you in `err.data`. ]
```
{data: {…}, errors: Array(2)}
data:
  createFolder: {__typename: "Folder", id: "095ab0a2-4968-4a39-ae52-41391af8a5fa", …}
  __proto__: Object
errors: Array(2)
  0:
    data: null
    errorInfo: null
    errorType: "Unauthorized"
    locations: [{…}]
    message: "Not Authorized to access items on type ModelTrackConnection"
    path: (3) ["createFolder", "tracks", "items"]
    __proto__: Object
  1:
    data: null
    errorInfo: null
    errorType: "Unauthorized"
    locations: [{…}]
    message: "Not Authorized to access nextToken on type ModelTrackConnection"
    path: (3) ["createFolder", "tracks", "nextToken"]
    __proto__: Object
    length: 2
  __proto__: Array(0)
__proto__: Object
```
NOTE: the you can see that `err.data` 

**Desktop (please complete the following information):**

- OS: Linux 4.19
- Node Version. 12.0.0
