### ISSUE TITLE
amplify codegen does not generate schema.json

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-cli#6665]
> **Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the
> [Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

amplify codegen does not generate schema.json

**Amplify CLI Version**

4.44.0
also encountered this on amplify Ci/CD

**To Reproduce**

Run `amplify codegen`

**Expected behavior**

It should generate `scheme.json`

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS 11.2.1
- Node Version: v15.2.0

**Log output**

N/A

**Additional context**

N/A

It used to do this, but now it does not. I'm doing it on an old project that has been dormant for some time.

**Comment by SwaySway** [comment]
@aprilmintacpineda 
A few questions here
- Are you using a custom push script in your ci/cd flow?
- Did you notice this change when you moved to version 4.44?
- Can you provide your `.graphqlconfig.yml`?

**Comment by aprilmintacpineda** [comment]
@SwaySway 

`amplify.yml`

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplify codegen
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn
    build:
      commands:
        - yarn build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

```

`.graphqlconfig.yml`

```yaml
projects:
  wrgdgraphqlapi:
    schemaPath: amplify/backend/api/myapp/build/schema.graphql
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: ap-southeast-2
        apiId: null
        maxDepth: 5
extensions:
  amplify:
    version: 3
```

> Did you notice this change when you moved to version 4.44?

Yeah, this project was dormant for months, I think about 3 months or more. Previously we were committing the `src/graphql` but now we decided not to do that as it is a source of all git conflicts and it's generated by amplify anyways so we shouldn't really need to commit that.
