### ISSUE TITLE
Specifying environment when AWS Amplify builds

### ISSUE THREAD

**Issue by dcp3450** [aws-amplify/amplify-cli#6963]
I have the Amplify environments setup to

```
{
  "dev": {...},
  "production": {...}
}
```

and the amplify.yml is

```
version: 1
frontend:
    phases:
        preBuild:
            commands:
                - 'npm ci'
                - if [ "${AWS_BRANCH}" == "master" ]; then amplify env checkout production; fi
                - if [ "${AWS_BRANCH}" == "develop" ]; then amplify env checkout dev; fi
        build:
            commands:
                - if [ "${AWS_BRANCH}" == "master" ]; then npm run build:prod; fi
                - if [ "${AWS_BRANCH}" == "develop" ]; then npm run build; fi
    artifacts:
        baseDirectory: dist/wcp-ui
        files:
            - '**/*'
    cache:
        paths:
            - 'node_modules/**/*'
```
the hope being the production env is used on the master branch build and dev env used on the develop branch build. However, the files are pointed to my local location when the command runs as such the command errors.

How do I have AWS Amplify update the file location?
