### ISSUE TITLE
Share amplify back-end between multiple web apps!

### ISSUE THREAD

**Issue by mjza** [aws-amplify/amplify-cli#7533]
I have one amplify project that contains back-end plus a react.js front-end. 

I want to have the second amplify project with react.js for front-end, however, share the back-end from the other amplify app with this one.

Although I shared the back-end and my second app works in the local environment, when I push it in the main branch to deploy it in the amplify it would fail to build. 

my `amplify.yml` in the second app:

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
``` 

Since it does not have any entry for `backend` like my first app, it fails in the step for fron-end build and it says:

> 2021-06-17T08:51:48.575Z [INFO]: Creating an optimized production build...
> 2021-06-17T08:51:49.382Z [INFO]: Failed to compile.
> 2021-06-17T08:51:49.383Z [INFO]: ./src/index.js
>                                  Cannot find file './aws-exports' in './src'. 

Please guide my through sharing an amplify back-end with 2 web apps. 
Most of the discussions in the internet are about sharing it with mobile applications like these:

https://docs.amplify.aws/cli/teams/multi-frontend

https://egghead.io/lessons/javascript-sharing-an-aws-amplify-back-end-project-across-multiple-clients

**Comment by josefaidt** [comment]
Hey @mjza :wave: how are you currently deploying the second application? Since the exports file is not committed to git it will need to be generated by running `amplify pull --appId <appid> --envName <env-name>`

**Comment by mjza** [comment]
Hey @josefaidt Yes I pulled with the command that you mentioned. Please notice that the back-end does not exist on my amplify app B, it is on amplify app A. On app A it works and compiled, however on app B I only need to use it and I don't need it build the back-end.
If you have a tutorial for such case, it would be so useful. 
For example in my scenario I have one client App (A) and one dashboard App (B).
Both front-ends are react.js, and both apps must use the same DB.

**Comment by josefaidt** [comment]
@mjza when going through the steps of that command it should prompt the following:

```
> amplify pull --appId <appId> --envName dev
Opening link: https://us-east-1.admin.amplifyapp.com/admin/<appId>/dev/verify/
✔ Successfully received Amplify Admin tokens.
Amplify AppID found: <appId>. Amplify App name is: <appName>
Backend environment dev found in Amplify Console app: <appName>
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building javascript
Please tell us about your project
? What javascript framework are you using none
? Source Directory Path:  src
? Distribution Directory Path: dist
? Build Command:  npm run-script build
? Start Command: npm run-script start
? Do you plan on modifying this backend? No
```

When we choose "No" for the last question `Do you plan on modifying this backend` it should generate the exports file in the source directory path.

**Comment by mjza** [comment]
I will test it an let you know.

**Comment by mjza** [comment]
When I select to not modify the back-end I cannot run the codegen! 

> mahdijaberzadehansari@Mac-mini-von-Mahdi cimplycitydashboard % amplify pull --appId xyz --envName staging
> Opening link: https://us-east-1.admin.amplifyapp.com/admin/xyz/staging/verify/
> ✔ Successfully received Amplify Admin tokens.
> Amplify AppID found: xyz. Amplify App name is: cimplycitywebapp
> Backend environment staging found in Amplify Console app: cimplycitywebapp
> ? Choose your default editor: Visual Studio Code
> ? Choose the type of app that you're building javascript
> Please tell us about your project
> ? What javascript framework are you using react
> ? Source Directory Path:  src
> ? Distribution Directory Path: build
> ? Build Command:  npm run-script build
> ? Start Command: npm run-script start
> ? Do you plan on modifying this backend? No
> 
> Added backend environment config object to your project.
> Run 'amplify pull' to sync upstream changes.
> 
> mahdijaberzadehansari@Mac-mini-von-Mahdi cimplycitydashboard % amplify codegen 
> Please download the schema.graphql or schema.json and place in /Users/mahdijaberzadehansari/Git/cimplycitydashboard before adding codegen when not in an amplify project

**Comment by mjza** [comment]
Do I really need to copy and paste this file each time from project A to project B?

**Comment by mjza** [comment]
The above configuration only makes a `.graphqlconfig.yml` in the root of my second project. 
Then I had to:
1. Copy `schema.graphql` file inside the root folder of the second App by hand!
2. Copy the built version of  `schema.graphql` from build folder in the first app `amplify/backend/api/cimplycitywebapp/build/` to exactly same folder in the second app. 

Making the folders in the second app, and copying the both `schema.graphql` files has been done by hand. 
It means every time there would be an update on the graphql I have to do these steps again and again. 
Isn't it annoying?

**Comment by mjza** [comment]
Another problem is the type of the generated files. It generates `*.graphql` instead of `*.js`

Here is my yml: 

```yml
projects:
  cimplycitywebapp:
    schemaPath: amplify/backend/api/cimplycitywebapp/build/schema.graphql
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        apiId: null
        maxDepth: 0
extensions:
  amplify:
    version: 3
```

I see here it has been mentioned `codeGenTarget: javascript`, however, it generates `*.graphql` files.

I even tried to copy and paste the `graphql.json` in both places. But it did not make any changes!

**Comment by mjza** [comment]
Could be related to https://github.com/aws-amplify/amplify-cli/issues/247

**Comment by mjza** [comment]
I solved the second issue. I removed the yaml file and used `amplify codegen add` to configure it from beginning, it solved the issue:

> mahdijaberzadehansari@Mac-mini-von-Mahdi cimplycitydashboard % amplify codegen add
> ? Choose the type of app that you're building javascript
> ? What javascript framework are you using react
> ? Choose the code generation language target javascript
> ? Enter the file name pattern of graphql queries, mutations and subscriptions src/graphql/**/*.js
> ? Do you want to generate/update all possible GraphQL operations - queries, mutations and subscriptions Yes
> ? Enter maximum statement depth [increase from default if your schema is deeply nested] 5
> ✔ Generated GraphQL operations successfully and saved at src/graphql
> mahdijaberzadehansari@Mac-mini-von-Mahdi cimplycitydashboard % amplify codegen    
> ✔ Generated GraphQL operations successfully and saved at src/graphql

**Comment by mjza** [comment]
Anyway, even by applying the new configuration the same error can be seen still.

> 2021-06-21T09:53:28.808Z [INFO]: Creating an optimized production build...
> 2021-06-21T09:53:29.455Z [INFO]: Failed to compile.
> 2021-06-21T09:53:29.456Z [INFO]: ./src/index.js
>                                  Cannot find file './aws-exports' in './src'. 

However, in my local I have this file in src folder. 
The question is, do I need to change the build settings in the amplify?

**Comment by mjza** [comment]
I have figured it out. 
I needed to carry out the following 2 steps:
1. Update the build setting as following:
```yml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

```
2.  Update the role in the general settings to be able to perform the back-end build.
