### ISSUE TITLE
Security related to committing aws-exports.js

### ISSUE THREAD

**Issue by cmoel** [aws-amplify/amplify-cli#754]
** Which Category is your question related to? **
Auth and Amplify Console Deploy

** What AWS Services are you utilizing? **
AWS Amplify Console Deploy and AWS Cognito

** Provide additional details e.g. code snippets **
Hi folks, 

I recently generated a new Amplify project using the latest beta version (0.2.1-multienv.35) of Amplify CLI to try out Amplify Console Deploy. After setting up Cognito Auth using the Amplify CLI and connecting my GitHub repo to Amplify Console and pushing to GitHub, Amplify Console Deploy started a build. The build failed with an error because it couldn't find `./src/aws-exports.js`. I noticed `amplify init` adds `aws-exports.js` to my project's .gitignore file. How sensitive is this file? If it is sensitive, what's the best way to use AWS Amplify Console Deploy without committing it? Is that possible?

Thanks!

**Comment by kaustavghosh06** [comment]
@cmoel Are you deploying your backend via the Amplify console as well?

**Comment by swaminator** [comment]
Hi @cmoel: in the console can you goto App settings > Build settings and share your YML script?

**Comment by undefobj** [comment]
@cmoel in answer to your question around sensitivity this is fine for an SPA as the items are used for constructing HTTP requests to the appropriate endpoints in your account. See https://github.com/aws-amplify/amplify-js/issues/2495#issuecomment-453282477 for a similar question in the past.

**Comment by cmoel** [comment]
@kaustavghosh06 I don't think I have access to the beta on my account, though I would prefer to deploy the backend via the Amplify Console.

**Comment by swaminator** [comment]
@cmoel try below. You can update the `amplifyPush --environment $AWS_BRANCH` to the name of your current environment for the console to pick it up.
```
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Get Amplify CLI Cloud-Formation stack info from environment cache'
        - export STACKINFO="$(envCache --get stackInfo)"
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --environment $AWS_BRANCH
        - '# Store Amplify CLI Cloud-Formation stack info in environment cache'
        - >-
          envCache --set stackInfo "$(amplify env get --json --name
          $AWS_BRANCH)"
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
