### ISSUE TITLE
Amplify update auth override my custom in Cloudformation template

### ISSUE THREAD

**Issue by phanviet** [aws-amplify/amplify-cli#7589]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v12.21.0

### Amplify CLI Version

5.0.1

### What operating system are you using?

Mac

### Amplify Categories

auth

### Amplify Commands

update

### Describe the bug

1. `amplify add auth`: Init Cognito User Pool and custom something in `AWS::Cognito::UserPool` such as
```
UsernameConfiguration:
    CaseSensitive: false
    AliasAttributes: ['email']
    AccountRecoverySetting:
      RecoveryMechanisms:
        - Name: verified_email
          Priority: 1
```
2. `amplify update auth` to update something
3. Result: the Cloudformation content override my custom config in step 1.

### Expected behavior

`amplify update auth` shouldn't override my custom config.

### Reproduction steps

as describe section

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>
