### ISSUE TITLE
Standardize use of whitespace, tab width in generated template files

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-cli#7635]
### Describe the feature you'd like to request

Some auto-generated files include extraneous whitespace, and in some cases tab width is different across files (typically 2 and 4 spaces)

Example 1 (whitespace): CloudFormation YML Snippet

```yml
  identityPoolName:
    Type: String
  
            
  
  allowUnauthenticatedIdentities:
    Type: String
            
  resourceNameTruncated:
    Type: String
  
            
  userPoolName:
    Type: String
  
            
        
  autoVerifiedAttributes:
    Type: CommaDelimitedList
      
  mfaConfiguration:
    Type: String
  
            
        
  mfaTypes:
    Type: CommaDelimitedList
      
  smsAuthenticationMessage:
    Type: String
  
            
  smsVerificationMessage:
    Type: String
```

Example 2 (tab width = 4): Lambda CloudFormation JSON Snippet

```json
{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Description": "Lambda Function resource stack creation using Amplify CLI",
    "Parameters": {
        "CloudWatchRule": {
            "Type": "String",
            "Default" : "NONE",
            "Description" : " Schedule Expression"
        },
        "deploymentBucketName": {
            "Type": "String"
        },
        "env": {
            "Type": "String"
        },
        "s3Key": {
            "Type": "String"
        }
    
    },
    "Conditions": {
        "ShouldNotCreateEnvResources": {
            "Fn::Equals": [
                {
                    "Ref": "env"
                },
                "NONE"
            ]
        }
    },
```

### Describe the solution you'd like

Remove extraneous horizontal whitespace and consolidate/standardize tab width size to 2

### Describe alternatives you've considered

n/a

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change
