### ISSUE TITLE
amplify codegen types creates blank file

### ISSUE THREAD

**Issue by matthew-valenti** [aws-amplify/amplify-cli#7652]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.16.1

### Amplify CLI Version

5.1.0

### What operating system are you using?

Windows

### Amplify Categories

api

### Amplify Commands

codegen

### Describe the bug

With a downloaded  AppSync schema file, `amplify codegen types` creates a blank types file.

```
/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.
```

However, running `amplify codegen` successfully creates the types files (and mutations.ts and queries.ts).
My project only needs the types file.

Changing the docsFilePath to anything other than src/graphql results in a blank types file too.

There doesn't seem to be a way to generate only a types file.

```
// .graphqlconfig.yml
projects:
  Codegen Project:
    schemaPath: schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: libs/core/src/lib/models/api.models.ts
        docsFilePath: src/graphql # Bug hack workaround. Changing this path results in a blank generated types file. For now, ignore junk files created here.
        region: us-east-1
        apiId: null
        frontend: javascript
        framework: ionic
extensions:
  amplify:
    version: 3
```

### Expected behavior

Running `amplify codegen types` creates a correct types file here: libs/core/src/lib/models/api.models.ts

### Reproduction steps

1. Download an AppSync schema file to the root of a typescript project.
2. Create a  .graphqlconfig.yml file as above.
3. Run `amplify codegen types` 
4. Generated api.models.ts types file is blank

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>
