### ISSUE TITLE
amplify push failure Docker-compose An error occurred during the push operation: FnJoin requires at least one value to be provided

### ISSUE THREAD

**Issue by nathanaerocloud** [aws-amplify/amplify-cli#7751]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

sudo npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v16.5.0

### Amplify CLI Version

5.1.2

### What operating system are you using?

MacOs 11.4

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

following the the advanced amplify guide relating to containers

https://docs.amplify.aws/cli/usage/containers#serverless-containers

after bringing the application up locally (strapi and Mongo) #docker-compose up -d

example of docker-compose.yml https://strapi.io/blog/how-to-run-a-strapi-dev-stack-with-docker-compose

this occurs when i execute : amplify push

% amplify push dev
✔ Successfully pulled backend environment dev from the cloud.

Current Environment: dev

| Category | Resource name     | Operation | Provider plugin   |
| -------- | ----------------- | --------- | ----------------- |
| Api      | containerxxxxx| Create    | awscloudformation |
? Are you sure you want to continue? Yes
? Select which container is the entrypoint strapiexample
✖ An error occurred when pushing the resources to the cloud

FnJoin requires at least one value to be provided
An error occurred during the push operation: FnJoin requires at least one value to be provided

### Expected behavior

push the the containers into REST based template API frontend with Fargate

cloud-formation creates backend app hosting  

used the following cmd and selected bring your own docker file empty template

amplify configure project

### Reproduction steps

#amplify push

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line

021-07-20T08:55:24.921Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileConfig(["user-x"])
2021-07-20T08:55:24.923Z|info : amplify-provider-awscloudformation.system-config-manager.getProfiledAwsConfig.profileConfig([{"region":"eu-x-x"}])
2021-07-20T08:55:24.923Z|info : amplify-provider-awscloudformation.system-config-manager.getProfileCredentials(["user-x"])
2021-07-20T08:55:25.345Z|error : amplify-provider-awscloudformation.push-resources.run([{"resourcesToBeCreated":[{"resourceName":"[***]e920b11","dependsOn":[{"category":"","resourceName":"[***]Stack","attributes":["ClusterName","VpcId","VpcCidrBlock","SubnetIds","VpcLinkId","CloudMapNamespaceId"]}],"deploymentMechanism":"FULLY_MANAGED","imageSource":{"type":"CUSTOM"},"restrictAccess":false,"build":true,"providerPlugin":"[***]rmation","service":"ElasticContainer","skipHashing":false,"apiType":"REST","iamAccessUnavailable":true,"category":"api"}],"resourcesToBeUpdated":[],"resourcesToBeSynced":[],"resourcesToBeDeleted":[],"tagsUpdated":false,"allResources":[{"resourceName":"[***]e920b11","dependsOn":[{"category":"","resourceName":"[***]Stack","attributes":["ClusterName","VpcId","VpcCidrBlock","SubnetIds","VpcLinkId","CloudMapNamespaceId"]}],"deploymentMechanism":"FULLY_MANAGED","imageSource":{"type":"CUSTOM"},"restrictAccess":false,"build":true,"providerPlugin":"[***]rmation","service":"ElasticContainer","skipHashing":false,"apiType":"REST","iamAccessUnavailable":true,"category":"api"}]}])
Error: FnJoin requires at least one value to be provided


```

</details>

**Comment by SwaySway** [comment]
Hello @nathanaerocloud 
Could you provide more details on how to reproduce? 
I tried to repro with with the steps provided in the doc and I did not run into this error.

**Comment by nathanaerocloud** [comment]
Hi SwaySway

thank you for coming back to me I am using these settings and follow the example but use the strapi example I sent the link for ... not the example shown as its strapi I want to run in Amplify ... have you tried with this docker-compose.yml?

https://strapi.io/blog/how-to-run-a-strapi-dev-stack-with-docker-compose

**`
amplify init (accept defaults)
amplify configure project (setup profile etc and choose containers in advanced )
? Which setting do you want to configure? Advanced: Container-based deployments
Using default provider  awscloudformation
? Do you want to enable container-based deployments? Yes

amplify add api
? Please select from one of the below mentioned services: REST
? Which service would you like to use API Gateway + AWS Fargate (Container-based)
? Provide a friendly name for your resource to be used as a label for this category in the project: container47exxxx
? What image would you like to use Custom (bring your own Dockerfile or docker-compose.yml)
? When do you want to build & deploy the Fargate task On every "amplify push" (Fully managed container source)
? Do you want to restrict API access Yes
`**

then I create a docker-compose.yml and .env file in the src folder

Docker file 
`version: "3"

services:
  strapiexample:
    image: strapi/strapi
    container_name: strapiexample
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    #    links:
    #      - mongo:mongo
    networks:
      - strapi-app-network
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:1337"

  mongoexample:
    image: mongo
    container_name: mongoexample
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - strapi-app-network
    volumes:
      - strapidata:/data/db
    ports:
      - "27017:27017"

networks:
  strapi-app-network:
    driver: bridge

volumes:
  strapidata:
 `
.env

`DATABASE_CLIENT=mongo
DATABASE_NAME=strapi
DATABASE_HOST=mongoexample
DATABASE_PORT=27017
DATABASE_USERNAME=strapi
DATABASE_PASSWORD=password
MONGO_INITDB_ROOT_USERNAME=strapi
MONGO_INITDB_ROOT_PASSWORD=password`

So to run locally to test it works before pushing top Amplify

docker-compose up -d

tailing the logs

docker-compose logs --tail=all -f | grep strapiexample

`strapiexample  | Using strapi 3.6.5
strapiexample  | No project found at /srv/app. Creating a new strapi project
strapiexample  | Creating a project from the database CLI arguments.
strapiexample  | Creating a new Strapi application at /srv/app.
strapiexample  | Creating files.
strapiexample  | - Installing dependencies:
strapiexample  | Dependencies installed successfully.
strapiexample  | 
strapiexample  | Your application was created at /srv/app.
strapiexample  | 
strapiexample  | Available commands in your project:
strapiexample  | 
strapiexample  |   yarn develop
strapiexample  |   Start Strapi in watch mode.
strapiexample  | 
strapiexample  |   yarn start
strapiexample  |   Start Strapi without watch mode.
strapiexample  | 
strapiexample  |   yarn build
strapiexample  |   Build Strapi admin panel.
strapiexample  | 
strapiexample  |   yarn strapi
strapiexample  |   Display all available commands.
strapiexample  | 
strapiexample  | You can start by doing:
strapiexample  | 
strapiexample  |   cd /srv/app
strapiexample  |   yarn develop
strapiexample  | 
strapiexample  | Starting your app...
strapiexample  | Building your admin UI with development configuration ...
strapiexample  | ℹ Compiling Webpack

`
So the application comes up locally and I can setup my admin user in the local browser

The issue occurs when it ry and push this to Amplify

Amplify push

✔ Successfully pulled backend environment dev from the cloud.

Current Environment: dev

| Category | Resource name     | Operation | Provider plugin   |
| -------- | ----------------- | --------- | ----------------- |
| Auth     | cognito87f6xxxx   | Create    | awscloudformation |
| Api      | container47exxxx | Create    | awscloudformation |
? Are you sure you want to continue? Yes
? Select which container is the entrypoint strapiexample
✖ An error occurred when pushing the resources to the cloud

FnJoin requires at least one value to be provided
An error occurred during the push operation: FnJoin requires at least one value to be provided

this looks to be cloud-formation error but I am not sure why :(

**Comment by nathanaerocloud** [comment]
Small update: a fellow engineers was able to replicate this situation on his system following these steps, would appreciate any input on a workaround

**Comment by josefaidt** [comment]
Hey @nathanaerocloud :wave: thanks for raising this and apologies for the delay! I was able to successfully reproduce this error using the steps and details provided (thank you for the details, they were very helpful in reproducing 😄). Marking this as a bug

Reproduction steps:

```
amplify init (accept defaults)
amplify configure project (setup profile etc and choose containers in advanced )
? Which setting do you want to configure? Advanced: Container-based deployments
Using default provider awscloudformation
? Do you want to enable container-based deployments? Yes

amplify add api
? Please select from one of the below mentioned services: REST
? Which service would you like to use API Gateway + AWS Fargate (Container-based)
? Provide a friendly name for your resource to be used as a label for this category in the project: container47exxxx
? What image would you like to use Custom (bring your own Dockerfile or docker-compose.yml)
? When do you want to build & deploy the Fargate task On every "amplify push" (Fully managed container source)
? Do you want to restrict API access Yes
```

Below are the sample files used:

```yml
version: '3'

services:
  strapiexample:
    image: strapi/strapi
    container_name: strapiexample
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    #    links:
    #      - mongo:mongo
    networks:
      - strapi-app-network
    # volumes:
    #   - ./app:/srv/app
    ports:
      - '1337:1337'

  mongoexample:
    image: mongo
    container_name: mongoexample
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - strapi-app-network
    # volumes:
    #   - strapidata:/data/db
    ports:
      - '27017:27017'

networks:
  strapi-app-network:
    driver: bridge
# volumes:
#   strapidata:
```

```
# .env
DATABASE_CLIENT=mongo
DATABASE_NAME=strapi
DATABASE_HOST=mongoexample
DATABASE_PORT=27017
DATABASE_USERNAME=strapi
DATABASE_PASSWORD=password
MONGO_INITDB_ROOT_USERNAME=strapi
MONGO_INITDB_ROOT_PASSWORD=password
```

**Comment by nathanaerocloud** [comment]
Hi Josefaidt 

Glad you were able to get the same result, will you fix the issue or provide a workaround? what does assigning as a bug result with?

best regards

Nathan

**Comment by josefaidt** [comment]
Hey @nathanaerocloud by labelling as a bug (and not a feature request, for example) the team will work with the provided steps and details to provide a resolution. For this issue in particular I do not have a workaround for, unfortunately. However, the team can now use this added context to work towards a proper solution 🙂

**Comment by sundersc** [comment]
Hey @nathanaerocloud Can you add a key "build: true" to the entry point container and give a try.
Something like this.

```yml
services:
  strapiexample:
    image: strapi/strapi
    build: true
    container_name: strapiexample
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
```

**Comment by nathanaerocloud** [comment]
Hi Sunersc,

Did you try this locally yourself? I get

`services:
  strapiexample:
    image: strapi/strapi
    build: "true"
    container_name: strapiexample
    restart: unless-stopped
    env_file: .env
`
docker-compose up -d
services.strapiexample.build must be a string

I tried adding quotes ie  "build" the build got further but exited with

unable to prepare context: path "true" not found

have I miss understood here?

all the best 

Nathan

**Comment by sundersc** [comment]
After making the change, CFN template is generated as expected. However the command "amplify push" fails with the error message "The following resource(s) failed to create: [DeploymentAwaiter]" for me. This usually happens if there are errors in the docker file.

[Error with DeploymentAwaiter on amplify push #6421](https://github.com/aws-amplify/amplify-cli/issues/6421)

**Comment by nathanaerocloud** [comment]
Hi Sundersc,

I did not try the push being honest, I was testing it locally first with 

#docker-compose up -d

sounds like we still have an issue either way :(

**Comment by sundersc** [comment]
It looks like docker is using build value to set the relative path. I've tried with the below docker file (changed build value to ".") in local, it works fine for me. However when I do amplify push, it fails with the error message I mentioned before. We will look into this.

```yml
services:
  strapiexample:
    image: strapi/strapi
    build: .
    container_name: strapiexample
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
```

**Comment by nathanaerocloud** [comment]
Hi sundersc

Thank you for looking at this for us, I confirm that works locally for me also but fails with the following error when pushed to Amplify

The following resource(s) failed to create: [DeploymentAwaiter].

**Comment by nathanaerocloud** [comment]
Hi Sunderc

Just wondering have you made any progress on a fix? be great if we could get passed this issue

Many thanks

**Comment by nathanaerocloud** [comment]
Hi Sunderc

Is this issue something AWS will address? I would just like to know if it is intended to fix the bug at this time, if not then of course we can seek alternatives

all the best

**Comment by renebrandel** [comment]
Hi @nathanaerocloud - This is in our bug backlog now. We'll likely be able to look into it more this Friday. Feel free to share any more logs that you think might be helpful. cc @sundersc is going to pick this up.

**Comment by sundersc** [comment]
@nathanaerocloud Apologies for the delay. Here is the configuration worked for me. Can you try on your end?

Here is the content of **docker-compose.yml**: (removed image key and moved to Dockerfile)
```yml
version: "3"

services:
  strapiexample:
    build: 
      context: ./strapiexample
      dockerfile: Dockerfile 
    container_name: strapiexample
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    #    links:
    #      - mongo:mongo
    networks:
      - strapi-app-network
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:1337"

  mongoexample:
    image: mongo
    container_name: mongoexample
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - strapi-app-network
    volumes:
      - strapidata:/data/db
    ports:
      - "27017:27017"

networks:
  strapi-app-network:
    driver: bridge

volumes:
  strapidata:
```

Now, create a folder 'strapiexample' in src folder and create a file 'Dockerfile' (case-sensitive). 

```dockerfile
FROM public.ecr.aws/knowre/strapi:3.1.4-node12

ENV PORT=1337
EXPOSE 1337
```

<img src="https://user-images.githubusercontent.com/83315412/129432544-b0a914fb-3228-436a-a21b-4afc2c2513dc.png" width="40%" />

I had to change the docker image to use strapi from ECR gallery because docker hub was throttling requests from aws server. If you think that this is not the correct version for you, replace the first line in Dockerfile to 'FROM strapi/strapi'. This will make sure the container downloads the image from docker hub.

ECR strapi image:
https://gallery.ecr.aws/knowre/strapi

Docker Hub image:
https://hub.docker.com/r/strapi/strapi

If you had to use docker hub image and encounter throttling errors, you can authenticate your pull requests as described here.
https://docs.docker.com/docker-hub/download-rate-limit/#how-do-i-authenticate-pull-requests
