### ISSUE TITLE
Amplify CLI is converting cloudformation yaml types (bool + numbers) to strings

### ISSUE THREAD

**Issue by ingwinlu** [aws-amplify/amplify-cli#7819]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

5.2.0

### What operating system are you using?

Ubuntu WSL

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

I am using a custom resource to setup a step function (that is later called by my amplify project).
Setting up and getting the step function running was no problem until i needed to use a choice state.

```
---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Step Function to handle events'
Parameters:
  env:
    Type: String
  functioneventHelperArn:
    Type: String
Resources:
  # Step functions state machine
  eventStateMachine:
    Type: 'AWS::StepFunctions::StateMachine'
    Properties:
      Definition:
        Comment: Handle incoming events
        StartAt: getActiveEvent
        States:
          getActiveEvent:
            Type: Task
            Resource: !Ref functioneventHelperArn
            Parameters:
              task: 'getActiveEvent'
              event.$: '$.event'
            ResultPath: '$.activeEvent'
            Next: choiceHasActive
          choiceHasActive:
            Type: Choice
            Choices:
              - Variable: '$.activeEvent'
                IsPresent: true
                Next: change
            Default: create
          change:
            Type: Succeed
          create:
            Type: Succeed
          # unexpectedState:
          #   Type: Fail
          #   Cause: Unexpected State
      RoleArn: !GetAtt 'RoleEventStateMachine.Arn'
      StateMachineType: 'EXPRESS'
      StateMachineName: !Join ['-', ['EventStateMachine', !Ref env]]
```

This results in `Reason: Resource handler returned message: "Invalid State Machine Definition: 'SCHEMA_VALIDATION_FAILED: Expected value of type Boolean at /States/choiceHasActive/Choices[0]/IsPresent' (Service: AWSStepFunctions; Status Code: 400; Error Code: InvalidDefinition; Request ID: 86d62caf-051d-4f22-982c-3945cedb3458; Proxy: null)" (RequestToken: 743801b0-6b92-a7ff-e264-578c15f90c4e, HandlerErrorCode: InvalidRequest)`

I also tried out inserting numbers for related number based choices -> they also get converted to strings.

I found something similar on the SAM repo https://github.com/aws/serverless-application-model/issues/531 without resolution except a workaround using a String (which is harder to read / maintain and as such not a good alternative in the long term).

### Expected behavior

Amplify CLI is NOT changing the types of my yml cloudformation resources which allows me to use yml for my step function definitions.

### Reproduction steps

See description
