### ISSUE TITLE
How to extend generated CloudFormation templates

### ISSUE THREAD

**Issue by ceich** [aws-amplify/amplify-cli#795]
**Which Category is your question related to?**
API
**What AWS Services are you utilizing?**
AppSync, Cognito, Dynamo, S3
**Provide additional details e.g. code snippets**
In a comment on #766, @undefobj mentioned that it was possible to cleanly edit generated CF templates in such a way that the next generation did not overwrite the changes. He suggested opening a new issue so as not to clutter that RFC. So, here it is!

**Comment by ceich** [comment]
@olivoil opened a related issue, #530, and closed it soon after, saying that `amplify api push --no-gql-override` does what he wanted. I can find no documentation of that flag, BTW.

**Comment by olivoil** [comment]
I used the flag to not modify the changes I made to the template before pushing. Not a great long term solution as it did overwrite my changes when I explicitly regenerated with `gql-compile`, but it was enough for my immediate need back then

**Comment by kaustavghosh06** [comment]
@ceich For AppSync we'll be introducing Custom resolvers and Custom CFN support soon (it is being actively tested).

For the other services, have you tried modifying the Cloudformation files in the amplify/backend dir?
Did any of the operations override these files?

You can take a look at the our git homepage -> https://github.com/aws-amplify/amplify-cli for the list of commands which has a description of the --no-gql-override flag.

**Comment by ceich** [comment]
@kaustavghosh06 Thanks for the update. I have not tried updating the CFN files yet. I just today realized that CFN does not support Cognito Hosted UI at all, so moving to Amplify CLI is not a priority for me.

I think the description of `--no-gql-override` may be missing a word (I've added it in brackets):
> The 'no-gql-override' flag does not automatically compile your annotated GraphQL schema and will **[not]** override your local AppSync resolvers and templates.

**Comment by kulikala** [comment]
I'm using Auth resources and I want to modify `AuthRole`.

I edited the generated CloudFormation template: `amplify/backend/awscloudformation/nested-cloudformation-stack.yml`
(I'm using `@aws-amplify/cli@multienv` by the way)

When I did `amplify push`, the stack template had been overwritten.
`--no-gql-override` did not help for this.

Any suggestion?

**Comment by kaustavghosh06** [comment]
@kulikala `amplify/backend/awscloudformation/nested-cloudformation-stack.yml` is a runtime file which gets re-generated on every push. What exactly are you looking to add in the AuthRole? So if you're adding some policies tied to say storage resource, you could modify the storage Cloudformation file located in `amplify/backend/storage/<resource-name>/cloudformation-template.json` and add custom policies to the authRole.

**Comment by ceich** [comment]
@kaustavghosh06 wrote:
> ... you could modify the storage Cloudformation file located in `amplify/backend/storage/<resource-name>/cloudformation-template.json` and add ...

Are you saying that templates are fair game for customization and won't be overwritten (as long as I don't remove that category)?

**Comment by kulikala** [comment]
@kaustavghosh06
> What exactly are you looking to add in the AuthRole?

Here's extraction of one of policies I need:
```yml
PolicyDocument:
  Version: '2012-10-17'
  Statement:
    - Sid: 1
      Effect: Allow
      Action:
        - cognito-idp:AdminEnableUser
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminDisableUser
        - cognito-idp:AdminGetUser
        - cognito-idp:adminDeleteUser
        - cognito-idp:ListUsers
      Resource:
        - !Sub
          - arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPoolId}
          - UserPoolId: !GetAtt cognitoxxxxxxxx.Outputs.UserPoolId
```

In this case, customizing `amplify/backend/auth/cognitoxxxxxxxx/cognitoxxxxxxxx-cloudformation-template.yml` is the best solution for adding custom policies to the authRole?

---

> `amplify/backend/awscloudformation/nested-cloudformation-stack.yml` is a runtime file which gets re-generated on every push.

Do you mean you can add `nested-cloudformation-stack.yml` to `.gitignore` file and not supposed to be maintained under version control system?

`amplify init` generates `.gitignore` with some of amplify files but it seems `amplify/backend/awscloudformation` dir is not in there.

Here's the copy of generated ones:
```gitignore
#amplify
amplify/\#current-cloud-backend
amplify/.config/local-*
amplify/backend/amplify-meta.json
aws-exports.js
awsconfiguration.json
```
