### ISSUE TITLE
Generated type, ModelAttributeTypes, typescript: Enum member names cannot start with lowercase 'a' through 'z

### ISSUE THREAD

**Issue by Nxtra** [aws-amplify/amplify-cli#7962]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm i @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v12.20.1

### Amplify CLI Version

5.3.0

### What operating system are you using?

MacOS

### Amplify Categories

api

### Amplify Commands

codegen

### Describe the bug

I generated types for my project which uses typescript using `amplify codegen types`.

This is my `graphqlconfig.yml`.

```
projects:
  myapp:
    schemaPath: amplify/backend/api/myapp/build/schema.graphql
    includes:
      - src/graphql/**/queries.ts
      - src/graphql/**/mutations.ts
      - src/graphql/**/subscriptions.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        maxDepth: 3
extensions:
  amplify:
    version: 3
```

This also generates automatically the following enum: 
```
export enum ModelAttributeTypes {
  binary = 'binary',
  binarySet = 'binarySet',
  bool = 'bool',
  list = 'list',
  map = 'map',
  number = 'number',
  numberSet = 'numberSet',
  string = 'string',
  stringSet = 'stringSet',
  _null = '_null'
}
```

My project does not compile with the error **_Parsing error: Enum member names cannot start with lowercase 'a' through 'z'._**

How can I disable this rule which complains about Parsing error: Enum member names cannot start with lowercase 'a' through 'z'.

Does anyone know how to fix this? I am not sure it's an Amplify fault. But if `Enum member names cannot start with lowercase 'a' through 'z'.` actually is a typescript standard. Then the Amplify framework violates this standard while generating `ModelAttributeTypes`

### Expected behavior

The project compiles with typescript.

### Reproduction steps

Prerequisit: configure typescript 
1. amplify codegen types
2. npm start

### GraphQL schema(s)

/

### Log output

<details>

```
# Put your logs below this line


```

</details>
