### ISSUE TITLE
InvalidParameterException: client_id, client_secret and authorize_scopes are all required idp details

### ISSUE THREAD

**Issue by henobi** [aws-amplify/amplify-cli#8266]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication, REST API

### Amplify Categories

auth, function, api

### Environment information

<details>

```
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 167.04 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.7.0 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.20.3 - /usr/local/bin/npm
    Watchman: 2021.08.02.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 93.0.4577.82
    Firefox: 92.0
    Safari: 14.1.1
  npmGlobalPackages:
    @aws-amplify/cli: 0.2.2-multienv.1
    express-generator: 4.16.1
    firebase-tools: 9.10.0
    npm: 7.20.3
    pnpm: 5.18.9
    react-native-cli: 2.0.1
    sass: 1.32.11
    typescript: 3.9.9



```

</details>

### Describe the bug

We added auth to our application with `amplify add auth` and choose the "Default with Social" and added Facebook and Google SignIn (Amplify asked for the facebook id & secret, google id, ....) and everythings worked fine and the social login in the frontend worked. After the next deployment with `amplify push` that contained no changes to the auth the update of the stack fails with the following detailed error in cloud watch:

```
{
    "Status": "FAILED",
    "Reason": "See the details in CloudWatch Log Stream: 2021/09/23/[$LATEST]45161df026574067a9678add6aad67a1",
    "PhysicalResourceId": "2021/09/23/[$LATEST]45161df026574067a9678add6aad67a1",
    "StackId": "arn:aws:cloudformation:eu-central-1:.......",
    "RequestId": "9fe9e56e-4984-46a7-a86e-ee431b9cddad",
    "LogicalResourceId": "HostedUIProvidersCustomResourceInputs",
    "NoEcho": false,
    "Data": {
        "err": {
            "message": "client_id, client_secret and authorize_scopes are all required idp details.",
            "code": "InvalidParameterException",
            "time": "2021-09-23T22:20:17.201Z",
            "requestId": "64171589-5e86-487b-869c-83b698072efa",
            "statusCode": 400,
            "retryable": false,
            "retryDelay": 92.76778608494173
        }
    }
}
```

Where do we have to configure the client_id, client_secret and authorize_scopes?

### Expected behavior

The stack should build successfully.

### Reproduction steps

1. Setup a new amplify project
2. `Apply default configuration with Social Provider (Federation)` and add Google and Facebook with Hosted UI
3. `amplify push`
4. Do some changes e.g change token validity from 30 to 90 days and run  `amplify push` again.
5. Now the deployment fails

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by attilah** [comment]
@henobi could you provide more details on how did you run `auth update`, as I tried it and everything worked successfully. How did you change the token validity?

Could you confirm what version of the CLI are you using `amplify --version` and where is it loaded from?

Asking because in your environment information I see something suspicious: `@aws-amplify/cli: 0.2.2-multienv.1` is that the version of Amplify CLI you are using? That's a not supported old tagged release you should remove that from your machine and update

**Comment by josefaidt** [comment]
Hey @henobi to add on to what @attilah has asked, may you post the error you're receiving on push? I believe this may be related to https://github.com/aws-amplify/amplify-cli/issues/7685

Also if there is some difference in the auth resource's `parameters.json` file after updating the unrelated resource, may you post the diff?

**Comment by henobi** [comment]
Hi guys,

thank you very much for the support and your answers.
I now solved the error by manually configure the social providers in the auth cloud formation file and now it is working fine.

The Version was Ampify `5.3.0`. I loaded it via npm.
But the error also occured in the AWS Amplify Build Tool.

So for me the problem is fixed.
But in case you want to do further analysis on the problem, here is my config file:

team-provider-info.json
```json
{
  "staging": {
    "awscloudformation": {
      "AuthRoleName": "amplify-....-authRole",
      .....
    },
    "categories": {
      "auth": {
        "assetsquare13fa9d2e": {}
      },
.....
}
```

parameters.json
```
{
  "identityPoolName": "......_identitypool_13fa9d2e",
  "allowUnauthenticatedIdentities": false,
  "resourceNameTruncated": ".....13fa9d2e",
  "userPoolName": "......13fa9d2e_userpool_13fa9d2e",
  "autoVerifiedAttributes": ["email"],
  "mfaConfiguration": "OPTIONAL",
  "mfaTypes": ["SMS Text Message"],
  "smsAuthenticationMessage": "Your authentication code is {####}",
  "smsVerificationMessage": "Your verification code is {####}",
  "emailVerificationSubject": "Your verification code",
  "emailVerificationMessage": "Your verification code is {####}",
  "defaultPasswordPolicy": false,
  "passwordPolicyMinLength": 8,
  "passwordPolicyCharacters": [],
  "requiredAttributes": ["email"],
  "aliasAttributes": [],
  "userpoolClientGenerateSecret": false,
  "userpoolClientRefreshTokenValidity": "90",
  "userpoolClientWriteAttributes": ["email"],
  "userpoolClientReadAttributes": ["email"],
  "userpoolClientLambdaRole": "......_userpoolclient_lambda_role",
  "userpoolClientSetAttributes": false,
  "sharedId": "13fa9d2e",
  "resourceName": ".....13fa9d2e",
  "authSelections": "identityPoolAndUserPool",
  "authRoleArn": {
    "Fn::GetAtt": ["AuthRole", "Arn"]
  },
  "unauthRoleArn": {
    "Fn::GetAtt": ["UnauthRole", "Arn"]
  },
  "useDefault": "manual",
  "usernameAttributes": ["email"],
  "userPoolGroupList": [],
  "serviceName": "Cognito",
  "usernameCaseSensitive": false,
  "dependsOn": [
    {
      "category": "function",
      "resourceName": ".....PostConfirmation",
      "triggerProvider": "Cognito",
      "attributes": ["Arn", "Name"]
    },
    {
      "category": "function",
      "resourceName": "......PreTokenGeneration",
      "triggerProvider": "Cognito",
      "attributes": ["Arn", "Name"]
    }
  ],
  "thirdPartyAuth": true,
  "userPoolGroups": false,
  "adminQueries": false,
  "triggers": "{\n  \"PostConfirmation\": [\n    \"custom\"\n  ],\n  \"PreTokenGeneration\": [\n    \"alter-claims\"\n  ]\n}",
  "hostedUI": false,
  "parentStack": {
    "Ref": "AWS::StackId"
  },
  "authTriggerConnections": "[\n  {\n    \"triggerType\": \"PostConfirmation\",\n    \"lambdaFunctionName\": \"assetsquare13fa9d2ePostConfirmation\"\n  },\n  {\n    \"triggerType\": \"PreTokenGeneration\",\n    \"lambdaFunctionName\": \"assetsquare13fa9d2ePreTokenGeneration\"\n  }\n]",
  "breakCircularDependency": true,
  "permissions": [],
  "authProviders": [
    "graph.facebook.com",
    "accounts.google.com",
    "appleid.apple.com"
  ]
}

```

**Comment by josefaidt** [comment]
Hey @henobi :wave: thanks for providing those additional details, and glad to hear you are back up and running! To clarify, can you post the diff of what needed to be changed?

**Comment by evanlarkin10** [comment]
I'm also having this error. I deployed it fine and its working correctly in my first environment, but when I moved it forward to a testing environment and tried to amplify push it there, it fails with that same error. parameters.json are the same for both, still confused where to add client_id, client_secret and authorize_scopes. @josefaidt Have you managed to resolve it for yourself?

**Comment by prachijaveri** [comment]
We are running into the same issue and our prod deployments are blocked due to this. Can you please suggest a fix for the same.

**Comment by henobi** [comment]
We fixed that issue by removing the lambda code which sets the social login from the CloudFormation file and configuration everything by cloud formation on our own.

```yaml

  UserPoolClient:
    Type: 'AWS::Cognito::UserPoolClient'
    Properties:
      ClientName: myapp_app_client
      AllowedOAuthFlows: ['code']
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        ['phone', 'email', 'openid', 'profile', 'aws.cognito.signin.user.admin']
      CallbackURLs:
        [
          'myapp://oauth/signin',
          'https://example.com/'
        ]
      LogoutURLs:
        [
          'myapp://oauth/signout',
          'https://example.com/'
        ]
      ReadAttributes: !Ref userpoolClientReadAttributes
      WriteAttributes: !Ref userpoolClientWriteAttributes
      SupportedIdentityProviders:
        ['COGNITO', 'Facebook', 'Google', 'SignInWithApple']
      GenerateSecret: !Ref userpoolClientGenerateSecret
      RefreshTokenValidity: !Ref userpoolClientRefreshTokenValidity
      UserPoolId: !Ref UserPool
    DependsOn:
      - UserPool
      - UserPoolIdentityProviderFacebook
      - UserPoolIdentityProviderGoogle
      - UserPoolIdentityProviderApple

  ## Login with Google
  UserPoolIdentityProviderGoogle:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      UserPoolId: !Ref UserPool
      ProviderName: 'Google'
      ProviderDetails:
        client_id: !Ref  googleClientId
        client_secret:  !Ref  googleClientSecret
        authorize_scopes: 'openid email profile'
      ProviderType: 'Google'
      AttributeMapping:
        email: 'email'
        username: 'sub'
        given_name: 'given_name'
        family_name: 'family_name'
        picture: 'picture'
        email_verified: 'email_verified'
        locale: 'locale'
  ## Login with Facebook
  UserPoolIdentityProviderFacebook:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      UserPoolId: !Ref UserPool
      ProviderName: 'Facebook'
      ProviderDetails:
        client_id:  !Ref facebookClientId
        client_secret: !Ref facebookSecret
        authorize_scopes: 'email,public_profile'
      ProviderType: 'Facebook'
      AttributeMapping:
        email: 'email'
        username: 'id'
        given_name: 'first_name'
        family_name: 'last_name'
        locale: 'locale'
        picture: 'picture'

  ## Login with Apple Sign In
  UserPoolIdentityProviderApple:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      UserPoolId: !Ref UserPool
      ProviderName: 'SignInWithApple'
      ProviderDetails:
        client_id: !Ref appleClientId
        team_id:  !Ref appleTeamId
        key_id:  !Ref appleKeyId
        authorize_scopes: 'email name'
      ProviderType: 'SignInWithApple'
      AttributeMapping:
        email: 'email'
        username: 'sub'
        given_name: 'firstName'
        family_name: 'lastName'


  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref UserPool
      Domain: !Join ['-', [!Ref hostedUIDomainName, !Ref env]]

```

Now everything is working perfectly fine for us.
I hope that helps you!
