### ISSUE TITLE
amplify codegen using relative path to current dir, not to project root

### ISSUE THREAD

**Issue by attilah** [aws-amplify/amplify-cli#886]
I've the following content in file ```.graphqlconfig.yml```:

```yml
projects:
  sampleproject:
    schemaPath: amplify/backend/function/src/graphql/schema.json
    includes:
      - dataloader/src/appsync/*.ts
    excludes:
      - amplify/**
    extensions:
      amplify:
        graphQLApiId: <...>
        codeGenTarget: typescript
        generatedFileName: dataloader/src/API.ts
        docsFilePath: dataloader/src/graphql
        region: us-east-1
      endpoints:
        prod: >-
          <...>
```

If I create a dir named 'foobar' and make that the current directory, upon executing ```amplify codegen``` the CLI creates the schemaPath and docsFilePath, generatedFileName files/dirs in 'foobar', not relative to the project's root where the yaml file is.

Not related to the bug, but I don't know why docsFilePath points to the location where the query/mutation/subscription typescript files will be generated...and API.ts is empty for me (I assume because it is a graphql api?

**To Reproduce**

Follow the steps in the description above.

**Expected behavior**
Files should be generated relative to the project's root, not the current dir.

CLI is the latest version.
