### ISSUE TITLE
Amplify auth overwrite: configure AWS::Cognito::UserPoolDomain 

### ISSUE THREAD

**Issue by henobi** [aws-amplify/amplify-cli#9273]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

7.6.3

### What operating system are you using?

mac

### Amplify Categories

auth

### Amplify Commands

push

### Describe the bug

I the former version of amplify we modified the cloudformation yaml file to add a custom cognito login domain.

```
Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref UserPool
      Domain: !Join ['', [!Ref env, '.example.com']]
      CustomDomainConfig:
        CertificateArn: !Ref authSSLCertificateArn
```

Now we are kind of stuck, because we do not see a possibility to configure this in the new `override.ts`.

### Expected behavior

Possibility to configure custom resources in the auth cloud formation file.

### Reproduction steps

-

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>
