### ISSUE TITLE
CustomerError: Missing frontend definition in buildspec

### ISSUE THREAD

**Issue by GGG1998** [aws-amplify/amplify-cli#9301]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.1.0

### Amplify CLI Version

7.6.3

### What operating system are you using?

MAC

### Amplify Categories

function, api, hosting

### Amplify Commands

push

### Describe the bug

I have application with function rest api. I don't have frontend just backend nothing more. When I push changes to branch, builder run and shows error: `!!! CustomerError: Missing frontend definition in buildspec`
If I add frontend with empty formula: it will remove files which run api. Command amplify push work perfect, why builder can't do this same?
```
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  artifacts:
    baseDirectory: ./
    files:
      - 'README.md'
```

### Expected behavior

I Expected that builder will push files from branch as like I do it locally with amplify push

### Reproduction steps

1. git push
2. WAIT FOR STATUS/MONITOR PIPELINE
3. Error or files are remove/access denied.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>
