### ISSUE TITLE
Empty backend step -> build phase

### ISSUE THREAD

**Issue by GanymedeIndustries** [aws-amplify/amplify-cli#9367]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

12.21.0

### Amplify CLI Version

7.6.5

### What operating system are you using?

Mac

### Amplify Categories

auth, storage, function, api, hosting

### Amplify Commands

Not applicable

### Describe the bug

When the app is being built after pushing to git, the Build pipeline(?) now fails when before it was working. Specifically the frontend step fails with the first error in there being:

```
/codebuild/output/src391767292/src/video-production-ui/amplify.sh: line 5: amplify: command not found
```

Which I am assuming because of the previous backend phase not being executed (or maybe it is but just not logging it as it does take time):

```
                                 # Starting phase: build
2021-12-22T00:42:37.399Z [INFO]: # Completed phase: build
```

Previous successful builds will log about how the backend was pulled in and consequently build the backend env. Nothing has changed since when this has started failing and am using the stock amplify.yml, albeit using yarn instead of npm:

```
version: 1
backend:
  phases:
    build:
      commands:
        # - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - if [ "${AWS_BRANCH}" = "development" ]; then yarn run build --mode development; fi
        - if [ "${AWS_BRANCH}" != "development" ]; then yarn run build; fi
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

It did successfully build once after a bit of failures, but the only difference between the previous failure and the successful build was removing the `- '# Execute Amplify CLI with the helper script'` comment from the amplify.yml file (was clutching at straws at the time). The next commit after that failed, which that commit still retained the missing comment in the amplify.yml file

Redeploying through the amplify console also does not work. I did NOT redeploy on that successful build as it was early morning and needed to sleep

### Expected behavior

The backend build phase to run. As I said, I'm assuming that that is the reason why the frontend fails, but I want to run it to check for sure.

### Reproduction steps

1. Push a commit

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>
